`timescale 1ns / 1ps

module MIG_DDR4(
    input                                   mig_clk                                        ,
    input                                   mig_rst_n                                      ,
    output    wire                          mig_ddr4_clk                                   ,
    input                                   mig_ddr4_rst_n                                 ,
    output    wire                          mig_ddr4_calib_complete                        ,
    output    wire                          mig_ddr4_ui_clk_sync_rst                       ,

    input               [ 7:0]              s_axi_mem_awid                                 ,
    input               [31:0]              s_axi_mem_awaddr                               ,
    input               [ 7:0]              s_axi_mem_awlen                                ,
    input               [ 2:0]              s_axi_mem_awsize                               ,
    input               [ 1:0]              s_axi_mem_awburst                              ,
    input                                   s_axi_mem_awlock                               ,
    input               [ 3:0]              s_axi_mem_awcache                              ,
    input               [ 2:0]              s_axi_mem_awprot                               ,
    input               [ 3:0]              s_axi_mem_awqos                                ,
    input                                   s_axi_mem_awvalid                              ,
    output    wire                          s_axi_mem_awready                              ,

    input               [255:0]             s_axi_mem_wdata                                ,
    input               [31:0]              s_axi_mem_wstrb                                ,
    input                                   s_axi_mem_wlast                                ,
    input                                   s_axi_mem_wvalid                               ,
    output    wire                          s_axi_mem_wready                               ,

    output    wire      [ 7:0]              s_axi_mem_bid                                  ,
    output    wire      [ 1:0]              s_axi_mem_bresp                                ,
    output    wire                          s_axi_mem_bvalid                               ,
    input                                   s_axi_mem_bready                               ,

    input               [ 7:0]              s_axi_mem_arid                                 ,
    input               [31:0]              s_axi_mem_araddr                               ,
    input               [ 7:0]              s_axi_mem_arlen                                ,
    input               [ 2:0]              s_axi_mem_arsize                               ,
    input               [ 1:0]              s_axi_mem_arburst                              ,
    input                                   s_axi_mem_arlock                               ,
    input               [ 3:0]              s_axi_mem_arcache                              ,
    input               [ 2:0]              s_axi_mem_arprot                               ,
    input               [ 3:0]              s_axi_mem_arqos                                ,
    input                                   s_axi_mem_arvalid                              ,
    output    wire                          s_axi_mem_arready                              ,

    output    wire      [ 7:0]              s_axi_mem_rid                                  ,
    output    wire      [255:0]             s_axi_mem_rdata                                ,
    output    wire      [ 1:0]              s_axi_mem_rresp                                ,
    output    wire                          s_axi_mem_rlast                                ,
    output    wire                          s_axi_mem_rvalid                               ,
    input                                   s_axi_mem_rready                               ,

    output    wire      [16:0]              ddr4_adr                                       ,
    output    wire      [ 1:0]              ddr4_ba                                        ,
    output    wire                          ddr4_bg                                        ,
    output    wire                          ddr4_act_n                                     ,
    output    wire                          ddr4_ck_t                                      ,
    output    wire                          ddr4_ck_c                                      ,
    output    wire                          ddr4_cke                                       ,
    output    wire                          ddr4_cs_n                                      ,
    output    wire                          ddr4_odt                                       ,
    output    wire                          ddr4_reset_n                                   ,
    inout     wire      [ 7:0]              ddr4_dm_dbi_n                                  ,
    inout     wire      [63:0]              ddr4_dq                                        ,
    inout     wire      [ 7:0]              ddr4_dqs_t                                     ,
    inout     wire      [ 7:0]              ddr4_dqs_c
);

//////////////////////////////////////////////////
//1. DDR4 Core
//////////////////////////////////////////////////
MIG_DDR4_CORE mig_ddr4_core(
    .c0_sys_clk_i                        (mig_clk                                      ),
    .sys_rst                             (~mig_rst_n                                   ),
    .c0_ddr4_ui_clk                      (mig_ddr4_clk                                 ),
    .c0_ddr4_aresetn                     (mig_ddr4_rst_n                               ),
    .c0_init_calib_complete              (mig_ddr4_calib_complete                      ),
    .c0_ddr4_ui_clk_sync_rst             (mig_ddr4_ui_clk_sync_rst                     ),
    .c0_ddr4_s_axi_awid                  (s_axi_mem_awid                               ),
    .c0_ddr4_s_axi_awaddr                (s_axi_mem_awaddr                             ),
    .c0_ddr4_s_axi_awlen                 (s_axi_mem_awlen                              ),
    .c0_ddr4_s_axi_awsize                (s_axi_mem_awsize                             ),
    .c0_ddr4_s_axi_awburst               (s_axi_mem_awburst                            ),
    .c0_ddr4_s_axi_awlock                (s_axi_mem_awlock                             ),
    .c0_ddr4_s_axi_awcache               (s_axi_mem_awcache                            ),
    .c0_ddr4_s_axi_awprot                (s_axi_mem_awprot                             ),
    .c0_ddr4_s_axi_awqos                 (s_axi_mem_awqos                              ),
    .c0_ddr4_s_axi_awvalid               (s_axi_mem_awvalid                            ),
    .c0_ddr4_s_axi_awready               (s_axi_mem_awready                            ),
    .c0_ddr4_s_axi_wdata                 (s_axi_mem_wdata                              ),
    .c0_ddr4_s_axi_wstrb                 (s_axi_mem_wstrb                              ),
    .c0_ddr4_s_axi_wlast                 (s_axi_mem_wlast                              ),
    .c0_ddr4_s_axi_wvalid                (s_axi_mem_wvalid                             ),
    .c0_ddr4_s_axi_wready                (s_axi_mem_wready                             ),
    .c0_ddr4_s_axi_bid                   (s_axi_mem_bid                                ),
    .c0_ddr4_s_axi_bresp                 (s_axi_mem_bresp                              ),
    .c0_ddr4_s_axi_bvalid                (s_axi_mem_bvalid                             ),
    .c0_ddr4_s_axi_bready                (s_axi_mem_bready                             ),
    .c0_ddr4_s_axi_arid                  (s_axi_mem_arid                               ),
    .c0_ddr4_s_axi_araddr                (s_axi_mem_araddr                             ),
    .c0_ddr4_s_axi_arlen                 (s_axi_mem_arlen                              ),
    .c0_ddr4_s_axi_arsize                (s_axi_mem_arsize                             ),
    .c0_ddr4_s_axi_arburst               (s_axi_mem_arburst                            ),
    .c0_ddr4_s_axi_arlock                (s_axi_mem_arlock                             ),
    .c0_ddr4_s_axi_arcache               (s_axi_mem_arcache                            ),
    .c0_ddr4_s_axi_arprot                (s_axi_mem_arprot                             ),
    .c0_ddr4_s_axi_arqos                 (s_axi_mem_arqos                              ),
    .c0_ddr4_s_axi_arvalid               (s_axi_mem_arvalid                            ),
    .c0_ddr4_s_axi_arready               (s_axi_mem_arready                            ),
    .c0_ddr4_s_axi_rid                   (s_axi_mem_rid                                ),
    .c0_ddr4_s_axi_rdata                 (s_axi_mem_rdata                              ),
    .c0_ddr4_s_axi_rresp                 (s_axi_mem_rresp                              ),
    .c0_ddr4_s_axi_rlast                 (s_axi_mem_rlast                              ),
    .c0_ddr4_s_axi_rvalid                (s_axi_mem_rvalid                             ),
    .c0_ddr4_s_axi_rready                (s_axi_mem_rready                             ),
    .c0_ddr4_adr                         (ddr4_adr                                     ),
    .c0_ddr4_ba                          (ddr4_ba                                      ),
    .c0_ddr4_bg                          (ddr4_bg                                      ),
    .c0_ddr4_act_n                       (ddr4_act_n                                   ),
    .c0_ddr4_ck_t                        (ddr4_ck_t                                    ),
    .c0_ddr4_ck_c                        (ddr4_ck_c                                    ),
    .c0_ddr4_cke                         (ddr4_cke                                     ),
    .c0_ddr4_cs_n                        (ddr4_cs_n                                    ),
    .c0_ddr4_odt                         (ddr4_odt                                     ),
    .c0_ddr4_reset_n                     (ddr4_reset_n                                 ),
    .c0_ddr4_dm_dbi_n                    (ddr4_dm_dbi_n                                ),
    .c0_ddr4_dq                          (ddr4_dq                                      ),
    .c0_ddr4_dqs_t                       (ddr4_dqs_t                                   ),
    .c0_ddr4_dqs_c                       (ddr4_dqs_c                                   ),
    .dbg_clk                             (                                             ),
    .dbg_bus                             (                                             )
);

endmodule
