`timescale 1ns / 1ps

module DMA_TOP(
    input                                   sys_clk                                        ,
    input                                   sys_rst_n                                      ,
    input                                   dma_clk                                        ,
    input                                   dma_rst_n                                      ,

    input               [ 7:0]              s_axi_awaddr                                   ,
    input               [ 2:0]              s_axi_awprot                                   ,
    input                                   s_axi_awvalid                                  ,
    output    wire                          s_axi_awready                                  ,
    input               [31:0]              s_axi_wdata                                    ,
    input               [ 3:0]              s_axi_wstrb                                    ,
    input                                   s_axi_wvalid                                   ,
    output    wire                          s_axi_wready                                   ,
    output    wire      [ 1:0]              s_axi_bresp                                    ,
    output    wire                          s_axi_bvalid                                   ,
    input                                   s_axi_bready                                   ,
    input               [ 7:0]              s_axi_araddr                                   ,
    input               [ 2:0]              s_axi_arprot                                   ,
    input                                   s_axi_arvalid                                  ,
    output    wire                          s_axi_arready                                  ,
    output    wire      [31:0]              s_axi_rdata                                    ,
    output    wire      [ 1:0]              s_axi_rresp                                    ,
    output    wire                          s_axi_rvalid                                   ,
    input                                   s_axi_rready                                   ,

    input               [31:0]              s00_axis_tdata                                 ,
    input                                   s00_axis_tlast                                 ,
    input                                   s00_axis_tvalid                                ,
    output    wire                          s00_axis_tready                                ,

    input               [31:0]              s01_axis_tdata                                 ,
    input                                   s01_axis_tlast                                 ,
    input                                   s01_axis_tvalid                                ,
    output    wire                          s01_axis_tready                                ,

    input               [31:0]              s02_axis_tdata                                 ,
    input                                   s02_axis_tlast                                 ,
    input                                   s02_axis_tvalid                                ,
    output    wire                          s02_axis_tready                                ,

    input               [31:0]              s03_axis_tdata                                 ,
    input                                   s03_axis_tlast                                 ,
    input                                   s03_axis_tvalid                                ,
    output    wire                          s03_axis_tready                                ,

    input               [31:0]              s04_axis_tdata                                 ,
    input                                   s04_axis_tlast                                 ,
    input                                   s04_axis_tvalid                                ,
    output    wire                          s04_axis_tready                                ,

    input               [31:0]              s05_axis_tdata                                 ,
    input                                   s05_axis_tlast                                 ,
    input                                   s05_axis_tvalid                                ,
    output    wire                          s05_axis_tready                                ,

    input               [31:0]              s06_axis_tdata                                 ,
    input                                   s06_axis_tlast                                 ,
    input                                   s06_axis_tvalid                                ,
    output    wire                          s06_axis_tready                                ,

    input               [31:0]              s07_axis_tdata                                 ,
    input                                   s07_axis_tlast                                 ,
    input                                   s07_axis_tvalid                                ,
    output    wire                          s07_axis_tready                                ,

    output    wire      [ 3:0]              m_axi_awid                                     ,
    output    wire      [31:0]              m_axi_awaddr                                   ,
    output    wire      [ 7:0]              m_axi_awlen                                    ,
    output    wire      [ 2:0]              m_axi_awsize                                   ,
    output    wire      [ 1:0]              m_axi_awburst                                  ,
    output    wire                          m_axi_awlock                                   ,
    output    wire      [ 3:0]              m_axi_awcache                                  ,
    output    wire      [ 2:0]              m_axi_awprot                                   ,
    output    wire      [ 3:0]              m_axi_awqos                                    ,
    output    wire                          m_axi_awvalid                                  ,
    input                                   m_axi_awready                                  ,
    output    wire      [255:0]             m_axi_wdata                                    ,
    output    wire      [31:0]              m_axi_wstrb                                    ,
    output    wire                          m_axi_wlast                                    ,
    output    wire                          m_axi_wvalid                                   ,
    input                                   m_axi_wready                                   ,
    input               [ 3:0]              m_axi_bid                                      ,
    input               [ 1:0]              m_axi_bresp                                    ,
    input                                   m_axi_bvalid                                   ,
    output    wire                          m_axi_bready                                   ,

    output    wire                          dma_irq
);

parameter                                   UDLY                     = 1                   ;

wire                    [31:0]              ch0_addr                                       ;
wire                    [31:0]              ch0_num                                        ;
wire                    [31:0]              ch0_ctl                                        ;
wire                    [31:0]              ch1_addr                                       ;
wire                    [31:0]              ch1_num                                        ;
wire                    [31:0]              ch1_ctl                                        ;
wire                    [31:0]              ch2_addr                                       ;
wire                    [31:0]              ch2_num                                        ;
wire                    [31:0]              ch2_ctl                                        ;
wire                    [31:0]              ch3_addr                                       ;
wire                    [31:0]              ch3_num                                        ;
wire                    [31:0]              ch3_ctl                                        ;
wire                    [31:0]              ch4_addr                                       ;
wire                    [31:0]              ch4_num                                        ;
wire                    [31:0]              ch4_ctl                                        ;
wire                    [31:0]              ch5_addr                                       ;
wire                    [31:0]              ch5_num                                        ;
wire                    [31:0]              ch5_ctl                                        ;
wire                    [31:0]              ch6_addr                                       ;
wire                    [31:0]              ch6_num                                        ;
wire                    [31:0]              ch6_ctl                                        ;
wire                    [31:0]              ch7_addr                                       ;
wire                    [31:0]              ch7_num                                        ;
wire                    [31:0]              ch7_ctl                                        ;

wire                    [ 7:0]              chn_busy                                       ;
wire                    [ 7:0]              fifo_empty                                     ;
wire                    [ 7:0]              fifo_full                                      ;
wire                    [ 7:0]              half_trans                                     ;
wire                    [ 7:0]              trans_comp                                     ;
wire                    [ 7:0]              axi_error                                      ;
wire                    [ 7:0]              chn_busy_sync                                  ;
wire                    [ 7:0]              fifo_empty_sync                                ;
wire                    [ 7:0]              fifo_full_sync                                 ;
wire                    [ 7:0]              half_trans_sync                                ;
wire                    [ 7:0]              trans_comp_sync                                ;
wire                    [ 7:0]              axi_error_sync                                 ;

wire                    [ 7:0]              chn_awid                                       ;
wire                    [255:0]             chn_awaddr                                     ;
wire                    [63:0]              chn_awlen                                      ;
wire                    [23:0]              chn_awsize                                     ;
wire                    [15:0]              chn_awburst                                    ;
wire                    [ 7:0]              chn_awlock                                     ;
wire                    [31:0]              chn_awcache                                    ;
wire                    [23:0]              chn_awprot                                     ;
wire                    [31:0]              chn_awqos                                      ;
wire                    [ 7:0]              chn_awvalid                                    ;
wire                    [ 7:0]              chn_awready                                    ;
wire                    [2047:0]            chn_wdata                                      ;
wire                    [255:0]             chn_wstrb                                      ;
wire                    [ 7:0]              chn_wlast                                      ;
wire                    [ 7:0]              chn_wvalid                                     ;
wire                    [ 7:0]              chn_wready                                     ;
wire                    [ 7:0]              chn_bid                                        ;
wire                    [15:0]              chn_bresp                                      ;
wire                    [ 7:0]              chn_bvalid                                     ;
wire                    [ 7:0]              chn_bready                                     ;

//////////////////////////////////////////////////
//1. Register Block
//////////////////////////////////////////////////
DMA_REG dma_reg(
    .sys_clk                             (sys_clk                                      ) ,
    .sys_rst_n                           (sys_rst_n                                    ) ,
    .s_axi_awaddr                        (s_axi_awaddr                                 ) ,
    .s_axi_awprot                        (s_axi_awprot                                 ) ,
    .s_axi_awvalid                       (s_axi_awvalid                                ) ,
    .s_axi_awready                       (s_axi_awready                                ) ,
    .s_axi_wdata                         (s_axi_wdata                                  ) ,
    .s_axi_wstrb                         (s_axi_wstrb                                  ) ,
    .s_axi_wvalid                        (s_axi_wvalid                                 ) ,
    .s_axi_wready                        (s_axi_wready                                 ) ,
    .s_axi_bresp                         (s_axi_bresp                                  ) ,
    .s_axi_bvalid                        (s_axi_bvalid                                 ) ,
    .s_axi_bready                        (s_axi_bready                                 ) ,
    .s_axi_araddr                        (s_axi_araddr                                 ) ,
    .s_axi_arprot                        (s_axi_arprot                                 ) ,
    .s_axi_arvalid                       (s_axi_arvalid                                ) ,
    .s_axi_arready                       (s_axi_arready                                ) ,
    .s_axi_rdata                         (s_axi_rdata                                  ) ,
    .s_axi_rresp                         (s_axi_rresp                                  ) ,
    .s_axi_rvalid                        (s_axi_rvalid                                 ) ,
    .s_axi_rready                        (s_axi_rready                                 ) ,
    .ch0_addr                            (ch0_addr                                     ) ,
    .ch0_num                             (ch0_num                                      ) ,
    .ch0_ctl                             (ch0_ctl                                      ) ,
    .ch1_addr                            (ch1_addr                                     ) ,
    .ch1_num                             (ch1_num                                      ) ,
    .ch1_ctl                             (ch1_ctl                                      ) ,
    .ch2_addr                            (ch2_addr                                     ) ,
    .ch2_num                             (ch2_num                                      ) ,
    .ch2_ctl                             (ch2_ctl                                      ) ,
    .ch3_addr                            (ch3_addr                                     ) ,
    .ch3_num                             (ch3_num                                      ) ,
    .ch3_ctl                             (ch3_ctl                                      ) ,
    .ch4_addr                            (ch4_addr                                     ) ,
    .ch4_num                             (ch4_num                                      ) ,
    .ch4_ctl                             (ch4_ctl                                      ) ,
    .ch5_addr                            (ch5_addr                                     ) ,
    .ch5_num                             (ch5_num                                      ) ,
    .ch5_ctl                             (ch5_ctl                                      ) ,
    .ch6_addr                            (ch6_addr                                     ) ,
    .ch6_num                             (ch6_num                                      ) ,
    .ch6_ctl                             (ch6_ctl                                      ) ,
    .ch7_addr                            (ch7_addr                                     ) ,
    .ch7_num                             (ch7_num                                      ) ,
    .ch7_ctl                             (ch7_ctl                                      ) ,
    .chn_busy_sync                       (chn_busy_sync                                ) ,
    .fifo_empty_sync                     (fifo_empty_sync                              ) ,
    .fifo_full_sync                      (fifo_full_sync                               ) ,
    .half_trans_sync                     (half_trans_sync                              ) ,
    .trans_comp_sync                     (trans_comp_sync                              ) ,
    .axi_error_sync                      (axi_error_sync                               ) ,
    .dma_irq                             (dma_irq                                      )
);

//////////////////////////////////////////////////
//2. Channel Engines
//////////////////////////////////////////////////
DMA_CHN dma_chn0(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s00_axis_tdata                               ) ,
    .s_axis_tlast                        (s00_axis_tlast                               ) ,
    .s_axis_tvalid                       (s00_axis_tvalid                              ) ,
    .s_axis_tready                       (s00_axis_tready                              ) ,
    .chn_addr                            (ch0_addr                                     ) ,
    .chn_num                             (ch0_num                                      ) ,
    .chn_ctl                             (ch0_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[0]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[31:0]                             ) ,
    .m_axi_awlen                         (chn_awlen[7:0]                               ) ,
    .m_axi_awsize                        (chn_awsize[2:0]                              ) ,
    .m_axi_awburst                       (chn_awburst[1:0]                             ) ,
    .m_axi_awlock                        (chn_awlock[0]                                ) ,
    .m_axi_awcache                       (chn_awcache[3:0]                             ) ,
    .m_axi_awprot                        (chn_awprot[2:0]                              ) ,
    .m_axi_awqos                         (chn_awqos[3:0]                               ) ,
    .m_axi_awvalid                       (chn_awvalid[0]                               ) ,
    .m_axi_awready                       (chn_awready[0]                               ) ,
    .m_axi_wdata                         (chn_wdata[255:0]                             ) ,
    .m_axi_wstrb                         (chn_wstrb[31:0]                              ) ,
    .m_axi_wlast                         (chn_wlast[0]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[0]                                ) ,
    .m_axi_wready                        (chn_wready[0]                                ) ,
    .m_axi_bid                           (chn_bid[0]                                   ) ,
    .m_axi_bresp                         (chn_bresp[1:0]                               ) ,
    .m_axi_bvalid                        (chn_bvalid[0]                                ) ,
    .m_axi_bready                        (chn_bready[0]                                ) ,
    .chn_busy                            (chn_busy[0]                                  ) ,
    .fifo_empty                          (fifo_empty[0]                                ) ,
    .fifo_full                           (fifo_full[0]                                 ) ,
    .half_trans                          (half_trans[0]                                ) ,
    .trans_comp                          (trans_comp[0]                                ) ,
    .axi_error                           (axi_error[0]                                 )
);

DMA_CHN dma_chn1(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s01_axis_tdata                               ) ,
    .s_axis_tlast                        (s01_axis_tlast                               ) ,
    .s_axis_tvalid                       (s01_axis_tvalid                              ) ,
    .s_axis_tready                       (s01_axis_tready                              ) ,
    .chn_addr                            (ch1_addr                                     ) ,
    .chn_num                             (ch1_num                                      ) ,
    .chn_ctl                             (ch1_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[1]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[63:32]                            ) ,
    .m_axi_awlen                         (chn_awlen[15:8]                              ) ,
    .m_axi_awsize                        (chn_awsize[5:3]                              ) ,
    .m_axi_awburst                       (chn_awburst[3:2]                             ) ,
    .m_axi_awlock                        (chn_awlock[1]                                ) ,
    .m_axi_awcache                       (chn_awcache[7:4]                             ) ,
    .m_axi_awprot                        (chn_awprot[5:3]                              ) ,
    .m_axi_awqos                         (chn_awqos[7:4]                               ) ,
    .m_axi_awvalid                       (chn_awvalid[1]                               ) ,
    .m_axi_awready                       (chn_awready[1]                               ) ,
    .m_axi_wdata                         (chn_wdata[511:256]                           ) ,
    .m_axi_wstrb                         (chn_wstrb[63:32]                             ) ,
    .m_axi_wlast                         (chn_wlast[1]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[1]                                ) ,
    .m_axi_wready                        (chn_wready[1]                                ) ,
    .m_axi_bid                           (chn_bid[1]                                   ) ,
    .m_axi_bresp                         (chn_bresp[3:2]                               ) ,
    .m_axi_bvalid                        (chn_bvalid[1]                                ) ,
    .m_axi_bready                        (chn_bready[1]                                ) ,
    .chn_busy                            (chn_busy[1]                                  ) ,
    .fifo_empty                          (fifo_empty[1]                                ) ,
    .fifo_full                           (fifo_full[1]                                 ) ,
    .half_trans                          (half_trans[1]                                ) ,
    .trans_comp                          (trans_comp[1]                                ) ,
    .axi_error                           (axi_error[1]                                 )
);

DMA_CHN dma_chn2(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s02_axis_tdata                               ) ,
    .s_axis_tlast                        (s02_axis_tlast                               ) ,
    .s_axis_tvalid                       (s02_axis_tvalid                              ) ,
    .s_axis_tready                       (s02_axis_tready                              ) ,
    .chn_addr                            (ch2_addr                                     ) ,
    .chn_num                             (ch2_num                                      ) ,
    .chn_ctl                             (ch2_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[2]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[95:64]                            ) ,
    .m_axi_awlen                         (chn_awlen[23:16]                             ) ,
    .m_axi_awsize                        (chn_awsize[8:6]                              ) ,
    .m_axi_awburst                       (chn_awburst[5:4]                             ) ,
    .m_axi_awlock                        (chn_awlock[2]                                ) ,
    .m_axi_awcache                       (chn_awcache[11:8]                            ) ,
    .m_axi_awprot                        (chn_awprot[8:6]                              ) ,
    .m_axi_awqos                         (chn_awqos[11:8]                              ) ,
    .m_axi_awvalid                       (chn_awvalid[2]                               ) ,
    .m_axi_awready                       (chn_awready[2]                               ) ,
    .m_axi_wdata                         (chn_wdata[767:512]                           ) ,
    .m_axi_wstrb                         (chn_wstrb[95:64]                             ) ,
    .m_axi_wlast                         (chn_wlast[2]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[2]                                ) ,
    .m_axi_wready                        (chn_wready[2]                                ) ,
    .m_axi_bid                           (chn_bid[2]                                   ) ,
    .m_axi_bresp                         (chn_bresp[5:4]                               ) ,
    .m_axi_bvalid                        (chn_bvalid[2]                                ) ,
    .m_axi_bready                        (chn_bready[2]                                ) ,
    .chn_busy                            (chn_busy[2]                                  ) ,
    .fifo_empty                          (fifo_empty[2]                                ) ,
    .fifo_full                           (fifo_full[2]                                 ) ,
    .half_trans                          (half_trans[2]                                ) ,
    .trans_comp                          (trans_comp[2]                                ) ,
    .axi_error                           (axi_error[2]                                 )
);

DMA_CHN dma_chn3(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s03_axis_tdata                               ) ,
    .s_axis_tlast                        (s03_axis_tlast                               ) ,
    .s_axis_tvalid                       (s03_axis_tvalid                              ) ,
    .s_axis_tready                       (s03_axis_tready                              ) ,
    .chn_addr                            (ch3_addr                                     ) ,
    .chn_num                             (ch3_num                                      ) ,
    .chn_ctl                             (ch3_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[3]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[127:96]                           ) ,
    .m_axi_awlen                         (chn_awlen[31:24]                             ) ,
    .m_axi_awsize                        (chn_awsize[11:9]                             ) ,
    .m_axi_awburst                       (chn_awburst[7:6]                             ) ,
    .m_axi_awlock                        (chn_awlock[3]                                ) ,
    .m_axi_awcache                       (chn_awcache[15:12]                           ) ,
    .m_axi_awprot                        (chn_awprot[11:9]                             ) ,
    .m_axi_awqos                         (chn_awqos[15:12]                             ) ,
    .m_axi_awvalid                       (chn_awvalid[3]                               ) ,
    .m_axi_awready                       (chn_awready[3]                               ) ,
    .m_axi_wdata                         (chn_wdata[1023:768]                          ) ,
    .m_axi_wstrb                         (chn_wstrb[127:96]                            ) ,
    .m_axi_wlast                         (chn_wlast[3]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[3]                                ) ,
    .m_axi_wready                        (chn_wready[3]                                ) ,
    .m_axi_bid                           (chn_bid[3]                                   ) ,
    .m_axi_bresp                         (chn_bresp[7:6]                               ) ,
    .m_axi_bvalid                        (chn_bvalid[3]                                ) ,
    .m_axi_bready                        (chn_bready[3]                                ) ,
    .chn_busy                            (chn_busy[3]                                  ) ,
    .fifo_empty                          (fifo_empty[3]                                ) ,
    .fifo_full                           (fifo_full[3]                                 ) ,
    .half_trans                          (half_trans[3]                                ) ,
    .trans_comp                          (trans_comp[3]                                ) ,
    .axi_error                           (axi_error[3]                                 )
);

DMA_CHN dma_chn4(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s04_axis_tdata                               ) ,
    .s_axis_tlast                        (s04_axis_tlast                               ) ,
    .s_axis_tvalid                       (s04_axis_tvalid                              ) ,
    .s_axis_tready                       (s04_axis_tready                              ) ,
    .chn_addr                            (ch4_addr                                     ) ,
    .chn_num                             (ch4_num                                      ) ,
    .chn_ctl                             (ch4_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[4]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[159:128]                          ) ,
    .m_axi_awlen                         (chn_awlen[39:32]                             ) ,
    .m_axi_awsize                        (chn_awsize[14:12]                            ) ,
    .m_axi_awburst                       (chn_awburst[9:8]                             ) ,
    .m_axi_awlock                        (chn_awlock[4]                                ) ,
    .m_axi_awcache                       (chn_awcache[19:16]                           ) ,
    .m_axi_awprot                        (chn_awprot[14:12]                            ) ,
    .m_axi_awqos                         (chn_awqos[19:16]                             ) ,
    .m_axi_awvalid                       (chn_awvalid[4]                               ) ,
    .m_axi_awready                       (chn_awready[4]                               ) ,
    .m_axi_wdata                         (chn_wdata[1279:1024]                         ) ,
    .m_axi_wstrb                         (chn_wstrb[159:128]                           ) ,
    .m_axi_wlast                         (chn_wlast[4]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[4]                                ) ,
    .m_axi_wready                        (chn_wready[4]                                ) ,
    .m_axi_bid                           (chn_bid[4]                                   ) ,
    .m_axi_bresp                         (chn_bresp[9:8]                               ) ,
    .m_axi_bvalid                        (chn_bvalid[4]                                ) ,
    .m_axi_bready                        (chn_bready[4]                                ) ,
    .chn_busy                            (chn_busy[4]                                  ) ,
    .fifo_empty                          (fifo_empty[4]                                ) ,
    .fifo_full                           (fifo_full[4]                                 ) ,
    .half_trans                          (half_trans[4]                                ) ,
    .trans_comp                          (trans_comp[4]                                ) ,
    .axi_error                           (axi_error[4]                                 )
);

DMA_CHN dma_chn5(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s05_axis_tdata                               ) ,
    .s_axis_tlast                        (s05_axis_tlast                               ) ,
    .s_axis_tvalid                       (s05_axis_tvalid                              ) ,
    .s_axis_tready                       (s05_axis_tready                              ) ,
    .chn_addr                            (ch5_addr                                     ) ,
    .chn_num                             (ch5_num                                      ) ,
    .chn_ctl                             (ch5_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[5]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[191:160]                          ) ,
    .m_axi_awlen                         (chn_awlen[47:40]                             ) ,
    .m_axi_awsize                        (chn_awsize[17:15]                            ) ,
    .m_axi_awburst                       (chn_awburst[11:10]                           ) ,
    .m_axi_awlock                        (chn_awlock[5]                                ) ,
    .m_axi_awcache                       (chn_awcache[23:20]                           ) ,
    .m_axi_awprot                        (chn_awprot[17:15]                            ) ,
    .m_axi_awqos                         (chn_awqos[23:20]                             ) ,
    .m_axi_awvalid                       (chn_awvalid[5]                               ) ,
    .m_axi_awready                       (chn_awready[5]                               ) ,
    .m_axi_wdata                         (chn_wdata[1535:1280]                         ) ,
    .m_axi_wstrb                         (chn_wstrb[191:160]                           ) ,
    .m_axi_wlast                         (chn_wlast[5]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[5]                                ) ,
    .m_axi_wready                        (chn_wready[5]                                ) ,
    .m_axi_bid                           (chn_bid[5]                                   ) ,
    .m_axi_bresp                         (chn_bresp[11:10]                             ) ,
    .m_axi_bvalid                        (chn_bvalid[5]                                ) ,
    .m_axi_bready                        (chn_bready[5]                                ) ,
    .chn_busy                            (chn_busy[5]                                  ) ,
    .fifo_empty                          (fifo_empty[5]                                ) ,
    .fifo_full                           (fifo_full[5]                                 ) ,
    .half_trans                          (half_trans[5]                                ) ,
    .trans_comp                          (trans_comp[5]                                ) ,
    .axi_error                           (axi_error[5]                                 )
);

DMA_CHN dma_chn6(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s06_axis_tdata                               ) ,
    .s_axis_tlast                        (s06_axis_tlast                               ) ,
    .s_axis_tvalid                       (s06_axis_tvalid                              ) ,
    .s_axis_tready                       (s06_axis_tready                              ) ,
    .chn_addr                            (ch6_addr                                     ) ,
    .chn_num                             (ch6_num                                      ) ,
    .chn_ctl                             (ch6_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[6]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[223:192]                          ) ,
    .m_axi_awlen                         (chn_awlen[55:48]                             ) ,
    .m_axi_awsize                        (chn_awsize[20:18]                            ) ,
    .m_axi_awburst                       (chn_awburst[13:12]                           ) ,
    .m_axi_awlock                        (chn_awlock[6]                                ) ,
    .m_axi_awcache                       (chn_awcache[27:24]                           ) ,
    .m_axi_awprot                        (chn_awprot[20:18]                            ) ,
    .m_axi_awqos                         (chn_awqos[27:24]                             ) ,
    .m_axi_awvalid                       (chn_awvalid[6]                               ) ,
    .m_axi_awready                       (chn_awready[6]                               ) ,
    .m_axi_wdata                         (chn_wdata[1791:1536]                         ) ,
    .m_axi_wstrb                         (chn_wstrb[223:192]                           ) ,
    .m_axi_wlast                         (chn_wlast[6]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[6]                                ) ,
    .m_axi_wready                        (chn_wready[6]                                ) ,
    .m_axi_bid                           (chn_bid[6]                                   ) ,
    .m_axi_bresp                         (chn_bresp[13:12]                             ) ,
    .m_axi_bvalid                        (chn_bvalid[6]                                ) ,
    .m_axi_bready                        (chn_bready[6]                                ) ,
    .chn_busy                            (chn_busy[6]                                  ) ,
    .fifo_empty                          (fifo_empty[6]                                ) ,
    .fifo_full                           (fifo_full[6]                                 ) ,
    .half_trans                          (half_trans[6]                                ) ,
    .trans_comp                          (trans_comp[6]                                ) ,
    .axi_error                           (axi_error[6]                                 )
);

DMA_CHN dma_chn7(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s_axis_tdata                        (s07_axis_tdata                               ) ,
    .s_axis_tlast                        (s07_axis_tlast                               ) ,
    .s_axis_tvalid                       (s07_axis_tvalid                              ) ,
    .s_axis_tready                       (s07_axis_tready                              ) ,
    .chn_addr                            (ch7_addr                                     ) ,
    .chn_num                             (ch7_num                                      ) ,
    .chn_ctl                             (ch7_ctl                                      ) ,
    .m_axi_awid                          (chn_awid[7]                                  ) ,
    .m_axi_awaddr                        (chn_awaddr[255:224]                          ) ,
    .m_axi_awlen                         (chn_awlen[63:56]                             ) ,
    .m_axi_awsize                        (chn_awsize[23:21]                            ) ,
    .m_axi_awburst                       (chn_awburst[15:14]                           ) ,
    .m_axi_awlock                        (chn_awlock[7]                                ) ,
    .m_axi_awcache                       (chn_awcache[31:28]                           ) ,
    .m_axi_awprot                        (chn_awprot[23:21]                            ) ,
    .m_axi_awqos                         (chn_awqos[31:28]                             ) ,
    .m_axi_awvalid                       (chn_awvalid[7]                               ) ,
    .m_axi_awready                       (chn_awready[7]                               ) ,
    .m_axi_wdata                         (chn_wdata[2047:1792]                         ) ,
    .m_axi_wstrb                         (chn_wstrb[255:224]                           ) ,
    .m_axi_wlast                         (chn_wlast[7]                                 ) ,
    .m_axi_wvalid                        (chn_wvalid[7]                                ) ,
    .m_axi_wready                        (chn_wready[7]                                ) ,
    .m_axi_bid                           (chn_bid[7]                                   ) ,
    .m_axi_bresp                         (chn_bresp[15:14]                             ) ,
    .m_axi_bvalid                        (chn_bvalid[7]                                ) ,
    .m_axi_bready                        (chn_bready[7]                                ) ,
    .chn_busy                            (chn_busy[7]                                  ) ,
    .fifo_empty                          (fifo_empty[7]                                ) ,
    .fifo_full                           (fifo_full[7]                                 ) ,
    .half_trans                          (half_trans[7]                                ) ,
    .trans_comp                          (trans_comp[7]                                ) ,
    .axi_error                           (axi_error[7]                                 )
);

//////////////////////////////////////////////////
//3. Return Synchronization
//////////////////////////////////////////////////
DMA_SYNC dma_sync(
    .sys_clk                             (sys_clk                                      ) ,
    .sys_rst_n                           (sys_rst_n                                    ) ,
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .chn_busy                            (chn_busy                                     ) ,
    .chn_busy_sync                       (chn_busy_sync                                ) ,
    .fifo_empty                          (fifo_empty                                   ) ,
    .fifo_empty_sync                     (fifo_empty_sync                              ) ,
    .fifo_full                           (fifo_full                                    ) ,
    .fifo_full_sync                      (fifo_full_sync                               ) ,
    .half_trans                          (half_trans                                   ) ,
    .half_trans_sync                     (half_trans_sync                              ) ,
    .trans_comp                          (trans_comp                                   ) ,
    .trans_comp_sync                     (trans_comp_sync                              ) ,
    .axi_error                           (axi_error                                    ) ,
    .axi_error_sync                      (axi_error_sync                               )
);

//////////////////////////////////////////////////
//4. Write Arbitration
//////////////////////////////////////////////////
DMA_ARB dma_arb(
    .dma_clk                             (dma_clk                                      ) ,
    .dma_rst_n                           (dma_rst_n                                    ) ,
    .s00_axi_awid                        (chn_awid[0]                                  ) ,
    .s00_axi_awaddr                      (chn_awaddr[31:0]                             ) ,
    .s00_axi_awlen                       (chn_awlen[7:0]                               ) ,
    .s00_axi_awsize                      (chn_awsize[2:0]                              ) ,
    .s00_axi_awburst                     (chn_awburst[1:0]                             ) ,
    .s00_axi_awlock                      (chn_awlock[0]                                ) ,
    .s00_axi_awcache                     (chn_awcache[3:0]                             ) ,
    .s00_axi_awprot                      (chn_awprot[2:0]                              ) ,
    .s00_axi_awqos                       (chn_awqos[3:0]                               ) ,
    .s00_axi_awvalid                     (chn_awvalid[0]                               ) ,
    .s00_axi_awready                     (chn_awready[0]                               ) ,
    .s00_axi_wdata                       (chn_wdata[255:0]                             ) ,
    .s00_axi_wstrb                       (chn_wstrb[31:0]                              ) ,
    .s00_axi_wlast                       (chn_wlast[0]                                 ) ,
    .s00_axi_wvalid                      (chn_wvalid[0]                                ) ,
    .s00_axi_wready                      (chn_wready[0]                                ) ,
    .s00_axi_bid                         (chn_bid[0]                                   ) ,
    .s00_axi_bresp                       (chn_bresp[1:0]                               ) ,
    .s00_axi_bvalid                      (chn_bvalid[0]                                ) ,
    .s00_axi_bready                      (chn_bready[0]                                ) ,
    .s01_axi_awid                        (chn_awid[1]                                  ) ,
    .s01_axi_awaddr                      (chn_awaddr[63:32]                            ) ,
    .s01_axi_awlen                       (chn_awlen[15:8]                              ) ,
    .s01_axi_awsize                      (chn_awsize[5:3]                              ) ,
    .s01_axi_awburst                     (chn_awburst[3:2]                             ) ,
    .s01_axi_awlock                      (chn_awlock[1]                                ) ,
    .s01_axi_awcache                     (chn_awcache[7:4]                             ) ,
    .s01_axi_awprot                      (chn_awprot[5:3]                              ) ,
    .s01_axi_awqos                       (chn_awqos[7:4]                               ) ,
    .s01_axi_awvalid                     (chn_awvalid[1]                               ) ,
    .s01_axi_awready                     (chn_awready[1]                               ) ,
    .s01_axi_wdata                       (chn_wdata[511:256]                           ) ,
    .s01_axi_wstrb                       (chn_wstrb[63:32]                             ) ,
    .s01_axi_wlast                       (chn_wlast[1]                                 ) ,
    .s01_axi_wvalid                      (chn_wvalid[1]                                ) ,
    .s01_axi_wready                      (chn_wready[1]                                ) ,
    .s01_axi_bid                         (chn_bid[1]                                   ) ,
    .s01_axi_bresp                       (chn_bresp[3:2]                               ) ,
    .s01_axi_bvalid                      (chn_bvalid[1]                                ) ,
    .s01_axi_bready                      (chn_bready[1]                                ) ,
    .s02_axi_awid                        (chn_awid[2]                                  ) ,
    .s02_axi_awaddr                      (chn_awaddr[95:64]                            ) ,
    .s02_axi_awlen                       (chn_awlen[23:16]                             ) ,
    .s02_axi_awsize                      (chn_awsize[8:6]                              ) ,
    .s02_axi_awburst                     (chn_awburst[5:4]                             ) ,
    .s02_axi_awlock                      (chn_awlock[2]                                ) ,
    .s02_axi_awcache                     (chn_awcache[11:8]                            ) ,
    .s02_axi_awprot                      (chn_awprot[8:6]                              ) ,
    .s02_axi_awqos                       (chn_awqos[11:8]                              ) ,
    .s02_axi_awvalid                     (chn_awvalid[2]                               ) ,
    .s02_axi_awready                     (chn_awready[2]                               ) ,
    .s02_axi_wdata                       (chn_wdata[767:512]                           ) ,
    .s02_axi_wstrb                       (chn_wstrb[95:64]                             ) ,
    .s02_axi_wlast                       (chn_wlast[2]                                 ) ,
    .s02_axi_wvalid                      (chn_wvalid[2]                                ) ,
    .s02_axi_wready                      (chn_wready[2]                                ) ,
    .s02_axi_bid                         (chn_bid[2]                                   ) ,
    .s02_axi_bresp                       (chn_bresp[5:4]                               ) ,
    .s02_axi_bvalid                      (chn_bvalid[2]                                ) ,
    .s02_axi_bready                      (chn_bready[2]                                ) ,
    .s03_axi_awid                        (chn_awid[3]                                  ) ,
    .s03_axi_awaddr                      (chn_awaddr[127:96]                           ) ,
    .s03_axi_awlen                       (chn_awlen[31:24]                             ) ,
    .s03_axi_awsize                      (chn_awsize[11:9]                             ) ,
    .s03_axi_awburst                     (chn_awburst[7:6]                             ) ,
    .s03_axi_awlock                      (chn_awlock[3]                                ) ,
    .s03_axi_awcache                     (chn_awcache[15:12]                           ) ,
    .s03_axi_awprot                      (chn_awprot[11:9]                             ) ,
    .s03_axi_awqos                       (chn_awqos[15:12]                             ) ,
    .s03_axi_awvalid                     (chn_awvalid[3]                               ) ,
    .s03_axi_awready                     (chn_awready[3]                               ) ,
    .s03_axi_wdata                       (chn_wdata[1023:768]                          ) ,
    .s03_axi_wstrb                       (chn_wstrb[127:96]                            ) ,
    .s03_axi_wlast                       (chn_wlast[3]                                 ) ,
    .s03_axi_wvalid                      (chn_wvalid[3]                                ) ,
    .s03_axi_wready                      (chn_wready[3]                                ) ,
    .s03_axi_bid                         (chn_bid[3]                                   ) ,
    .s03_axi_bresp                       (chn_bresp[7:6]                               ) ,
    .s03_axi_bvalid                      (chn_bvalid[3]                                ) ,
    .s03_axi_bready                      (chn_bready[3]                                ) ,
    .s04_axi_awid                        (chn_awid[4]                                  ) ,
    .s04_axi_awaddr                      (chn_awaddr[159:128]                          ) ,
    .s04_axi_awlen                       (chn_awlen[39:32]                             ) ,
    .s04_axi_awsize                      (chn_awsize[14:12]                            ) ,
    .s04_axi_awburst                     (chn_awburst[9:8]                             ) ,
    .s04_axi_awlock                      (chn_awlock[4]                                ) ,
    .s04_axi_awcache                     (chn_awcache[19:16]                           ) ,
    .s04_axi_awprot                      (chn_awprot[14:12]                            ) ,
    .s04_axi_awqos                       (chn_awqos[19:16]                             ) ,
    .s04_axi_awvalid                     (chn_awvalid[4]                               ) ,
    .s04_axi_awready                     (chn_awready[4]                               ) ,
    .s04_axi_wdata                       (chn_wdata[1279:1024]                         ) ,
    .s04_axi_wstrb                       (chn_wstrb[159:128]                           ) ,
    .s04_axi_wlast                       (chn_wlast[4]                                 ) ,
    .s04_axi_wvalid                      (chn_wvalid[4]                                ) ,
    .s04_axi_wready                      (chn_wready[4]                                ) ,
    .s04_axi_bid                         (chn_bid[4]                                   ) ,
    .s04_axi_bresp                       (chn_bresp[9:8]                               ) ,
    .s04_axi_bvalid                      (chn_bvalid[4]                                ) ,
    .s04_axi_bready                      (chn_bready[4]                                ) ,
    .s05_axi_awid                        (chn_awid[5]                                  ) ,
    .s05_axi_awaddr                      (chn_awaddr[191:160]                          ) ,
    .s05_axi_awlen                       (chn_awlen[47:40]                             ) ,
    .s05_axi_awsize                      (chn_awsize[17:15]                            ) ,
    .s05_axi_awburst                     (chn_awburst[11:10]                           ) ,
    .s05_axi_awlock                      (chn_awlock[5]                                ) ,
    .s05_axi_awcache                     (chn_awcache[23:20]                           ) ,
    .s05_axi_awprot                      (chn_awprot[17:15]                            ) ,
    .s05_axi_awqos                       (chn_awqos[23:20]                             ) ,
    .s05_axi_awvalid                     (chn_awvalid[5]                               ) ,
    .s05_axi_awready                     (chn_awready[5]                               ) ,
    .s05_axi_wdata                       (chn_wdata[1535:1280]                         ) ,
    .s05_axi_wstrb                       (chn_wstrb[191:160]                           ) ,
    .s05_axi_wlast                       (chn_wlast[5]                                 ) ,
    .s05_axi_wvalid                      (chn_wvalid[5]                                ) ,
    .s05_axi_wready                      (chn_wready[5]                                ) ,
    .s05_axi_bid                         (chn_bid[5]                                   ) ,
    .s05_axi_bresp                       (chn_bresp[11:10]                             ) ,
    .s05_axi_bvalid                      (chn_bvalid[5]                                ) ,
    .s05_axi_bready                      (chn_bready[5]                                ) ,
    .s06_axi_awid                        (chn_awid[6]                                  ) ,
    .s06_axi_awaddr                      (chn_awaddr[223:192]                          ) ,
    .s06_axi_awlen                       (chn_awlen[55:48]                             ) ,
    .s06_axi_awsize                      (chn_awsize[20:18]                            ) ,
    .s06_axi_awburst                     (chn_awburst[13:12]                           ) ,
    .s06_axi_awlock                      (chn_awlock[6]                                ) ,
    .s06_axi_awcache                     (chn_awcache[27:24]                           ) ,
    .s06_axi_awprot                      (chn_awprot[20:18]                            ) ,
    .s06_axi_awqos                       (chn_awqos[27:24]                             ) ,
    .s06_axi_awvalid                     (chn_awvalid[6]                               ) ,
    .s06_axi_awready                     (chn_awready[6]                               ) ,
    .s06_axi_wdata                       (chn_wdata[1791:1536]                         ) ,
    .s06_axi_wstrb                       (chn_wstrb[223:192]                           ) ,
    .s06_axi_wlast                       (chn_wlast[6]                                 ) ,
    .s06_axi_wvalid                      (chn_wvalid[6]                                ) ,
    .s06_axi_wready                      (chn_wready[6]                                ) ,
    .s06_axi_bid                         (chn_bid[6]                                   ) ,
    .s06_axi_bresp                       (chn_bresp[13:12]                             ) ,
    .s06_axi_bvalid                      (chn_bvalid[6]                                ) ,
    .s06_axi_bready                      (chn_bready[6]                                ) ,
    .s07_axi_awid                        (chn_awid[7]                                  ) ,
    .s07_axi_awaddr                      (chn_awaddr[255:224]                          ) ,
    .s07_axi_awlen                       (chn_awlen[63:56]                             ) ,
    .s07_axi_awsize                      (chn_awsize[23:21]                            ) ,
    .s07_axi_awburst                     (chn_awburst[15:14]                           ) ,
    .s07_axi_awlock                      (chn_awlock[7]                                ) ,
    .s07_axi_awcache                     (chn_awcache[31:28]                           ) ,
    .s07_axi_awprot                      (chn_awprot[23:21]                            ) ,
    .s07_axi_awqos                       (chn_awqos[31:28]                             ) ,
    .s07_axi_awvalid                     (chn_awvalid[7]                               ) ,
    .s07_axi_awready                     (chn_awready[7]                               ) ,
    .s07_axi_wdata                       (chn_wdata[2047:1792]                         ) ,
    .s07_axi_wstrb                       (chn_wstrb[255:224]                           ) ,
    .s07_axi_wlast                       (chn_wlast[7]                                 ) ,
    .s07_axi_wvalid                      (chn_wvalid[7]                                ) ,
    .s07_axi_wready                      (chn_wready[7]                                ) ,
    .s07_axi_bid                         (chn_bid[7]                                   ) ,
    .s07_axi_bresp                       (chn_bresp[15:14]                             ) ,
    .s07_axi_bvalid                      (chn_bvalid[7]                                ) ,
    .s07_axi_bready                      (chn_bready[7]                                ) ,
    .m00_axi_awid                        (m_axi_awid                                   ) ,
    .m00_axi_awaddr                      (m_axi_awaddr                                 ) ,
    .m00_axi_awlen                       (m_axi_awlen                                  ) ,
    .m00_axi_awsize                      (m_axi_awsize                                 ) ,
    .m00_axi_awburst                     (m_axi_awburst                                ) ,
    .m00_axi_awlock                      (m_axi_awlock                                 ) ,
    .m00_axi_awcache                     (m_axi_awcache                                ) ,
    .m00_axi_awprot                      (m_axi_awprot                                 ) ,
    .m00_axi_awqos                       (m_axi_awqos                                  ) ,
    .m00_axi_awvalid                     (m_axi_awvalid                                ) ,
    .m00_axi_awready                     (m_axi_awready                                ) ,
    .m00_axi_wdata                       (m_axi_wdata                                  ) ,
    .m00_axi_wstrb                       (m_axi_wstrb                                  ) ,
    .m00_axi_wlast                       (m_axi_wlast                                  ) ,
    .m00_axi_wvalid                      (m_axi_wvalid                                 ) ,
    .m00_axi_wready                      (m_axi_wready                                 ) ,
    .m00_axi_bid                         (m_axi_bid                                    ) ,
    .m00_axi_bresp                       (m_axi_bresp                                  ) ,
    .m00_axi_bvalid                      (m_axi_bvalid                                 ) ,
    .m00_axi_bready                      (m_axi_bready                                 )
);

endmodule
