`timescale 1ns / 1ps

module DMA_ARB(
    input                                   dma_clk                                        ,
    input                                   dma_rst_n                                      ,

    input                                   s00_axi_awid                                   ,
    input               [31:0]              s00_axi_awaddr                                 ,
    input               [ 7:0]              s00_axi_awlen                                  ,
    input               [ 2:0]              s00_axi_awsize                                 ,
    input               [ 1:0]              s00_axi_awburst                                ,
    input                                   s00_axi_awlock                                 ,
    input               [ 3:0]              s00_axi_awcache                                ,
    input               [ 2:0]              s00_axi_awprot                                 ,
    input               [ 3:0]              s00_axi_awqos                                  ,
    input                                   s00_axi_awvalid                                ,
    output    wire                          s00_axi_awready                                ,
    input               [255:0]             s00_axi_wdata                                  ,
    input               [31:0]              s00_axi_wstrb                                  ,
    input                                   s00_axi_wlast                                  ,
    input                                   s00_axi_wvalid                                 ,
    output    wire                          s00_axi_wready                                 ,
    output    wire                          s00_axi_bid                                    ,
    output    wire      [ 1:0]              s00_axi_bresp                                  ,
    output    wire                          s00_axi_bvalid                                 ,
    input                                   s00_axi_bready                                 ,

    input                                   s01_axi_awid                                   ,
    input               [31:0]              s01_axi_awaddr                                 ,
    input               [ 7:0]              s01_axi_awlen                                  ,
    input               [ 2:0]              s01_axi_awsize                                 ,
    input               [ 1:0]              s01_axi_awburst                                ,
    input                                   s01_axi_awlock                                 ,
    input               [ 3:0]              s01_axi_awcache                                ,
    input               [ 2:0]              s01_axi_awprot                                 ,
    input               [ 3:0]              s01_axi_awqos                                  ,
    input                                   s01_axi_awvalid                                ,
    output    wire                          s01_axi_awready                                ,
    input               [255:0]             s01_axi_wdata                                  ,
    input               [31:0]              s01_axi_wstrb                                  ,
    input                                   s01_axi_wlast                                  ,
    input                                   s01_axi_wvalid                                 ,
    output    wire                          s01_axi_wready                                 ,
    output    wire                          s01_axi_bid                                    ,
    output    wire      [ 1:0]              s01_axi_bresp                                  ,
    output    wire                          s01_axi_bvalid                                 ,
    input                                   s01_axi_bready                                 ,

    input                                   s02_axi_awid                                   ,
    input               [31:0]              s02_axi_awaddr                                 ,
    input               [ 7:0]              s02_axi_awlen                                  ,
    input               [ 2:0]              s02_axi_awsize                                 ,
    input               [ 1:0]              s02_axi_awburst                                ,
    input                                   s02_axi_awlock                                 ,
    input               [ 3:0]              s02_axi_awcache                                ,
    input               [ 2:0]              s02_axi_awprot                                 ,
    input               [ 3:0]              s02_axi_awqos                                  ,
    input                                   s02_axi_awvalid                                ,
    output    wire                          s02_axi_awready                                ,
    input               [255:0]             s02_axi_wdata                                  ,
    input               [31:0]              s02_axi_wstrb                                  ,
    input                                   s02_axi_wlast                                  ,
    input                                   s02_axi_wvalid                                 ,
    output    wire                          s02_axi_wready                                 ,
    output    wire                          s02_axi_bid                                    ,
    output    wire      [ 1:0]              s02_axi_bresp                                  ,
    output    wire                          s02_axi_bvalid                                 ,
    input                                   s02_axi_bready                                 ,

    input                                   s03_axi_awid                                   ,
    input               [31:0]              s03_axi_awaddr                                 ,
    input               [ 7:0]              s03_axi_awlen                                  ,
    input               [ 2:0]              s03_axi_awsize                                 ,
    input               [ 1:0]              s03_axi_awburst                                ,
    input                                   s03_axi_awlock                                 ,
    input               [ 3:0]              s03_axi_awcache                                ,
    input               [ 2:0]              s03_axi_awprot                                 ,
    input               [ 3:0]              s03_axi_awqos                                  ,
    input                                   s03_axi_awvalid                                ,
    output    wire                          s03_axi_awready                                ,
    input               [255:0]             s03_axi_wdata                                  ,
    input               [31:0]              s03_axi_wstrb                                  ,
    input                                   s03_axi_wlast                                  ,
    input                                   s03_axi_wvalid                                 ,
    output    wire                          s03_axi_wready                                 ,
    output    wire                          s03_axi_bid                                    ,
    output    wire      [ 1:0]              s03_axi_bresp                                  ,
    output    wire                          s03_axi_bvalid                                 ,
    input                                   s03_axi_bready                                 ,

    input                                   s04_axi_awid                                   ,
    input               [31:0]              s04_axi_awaddr                                 ,
    input               [ 7:0]              s04_axi_awlen                                  ,
    input               [ 2:0]              s04_axi_awsize                                 ,
    input               [ 1:0]              s04_axi_awburst                                ,
    input                                   s04_axi_awlock                                 ,
    input               [ 3:0]              s04_axi_awcache                                ,
    input               [ 2:0]              s04_axi_awprot                                 ,
    input               [ 3:0]              s04_axi_awqos                                  ,
    input                                   s04_axi_awvalid                                ,
    output    wire                          s04_axi_awready                                ,
    input               [255:0]             s04_axi_wdata                                  ,
    input               [31:0]              s04_axi_wstrb                                  ,
    input                                   s04_axi_wlast                                  ,
    input                                   s04_axi_wvalid                                 ,
    output    wire                          s04_axi_wready                                 ,
    output    wire                          s04_axi_bid                                    ,
    output    wire      [ 1:0]              s04_axi_bresp                                  ,
    output    wire                          s04_axi_bvalid                                 ,
    input                                   s04_axi_bready                                 ,

    input                                   s05_axi_awid                                   ,
    input               [31:0]              s05_axi_awaddr                                 ,
    input               [ 7:0]              s05_axi_awlen                                  ,
    input               [ 2:0]              s05_axi_awsize                                 ,
    input               [ 1:0]              s05_axi_awburst                                ,
    input                                   s05_axi_awlock                                 ,
    input               [ 3:0]              s05_axi_awcache                                ,
    input               [ 2:0]              s05_axi_awprot                                 ,
    input               [ 3:0]              s05_axi_awqos                                  ,
    input                                   s05_axi_awvalid                                ,
    output    wire                          s05_axi_awready                                ,
    input               [255:0]             s05_axi_wdata                                  ,
    input               [31:0]              s05_axi_wstrb                                  ,
    input                                   s05_axi_wlast                                  ,
    input                                   s05_axi_wvalid                                 ,
    output    wire                          s05_axi_wready                                 ,
    output    wire                          s05_axi_bid                                    ,
    output    wire      [ 1:0]              s05_axi_bresp                                  ,
    output    wire                          s05_axi_bvalid                                 ,
    input                                   s05_axi_bready                                 ,

    input                                   s06_axi_awid                                   ,
    input               [31:0]              s06_axi_awaddr                                 ,
    input               [ 7:0]              s06_axi_awlen                                  ,
    input               [ 2:0]              s06_axi_awsize                                 ,
    input               [ 1:0]              s06_axi_awburst                                ,
    input                                   s06_axi_awlock                                 ,
    input               [ 3:0]              s06_axi_awcache                                ,
    input               [ 2:0]              s06_axi_awprot                                 ,
    input               [ 3:0]              s06_axi_awqos                                  ,
    input                                   s06_axi_awvalid                                ,
    output    wire                          s06_axi_awready                                ,
    input               [255:0]             s06_axi_wdata                                  ,
    input               [31:0]              s06_axi_wstrb                                  ,
    input                                   s06_axi_wlast                                  ,
    input                                   s06_axi_wvalid                                 ,
    output    wire                          s06_axi_wready                                 ,
    output    wire                          s06_axi_bid                                    ,
    output    wire      [ 1:0]              s06_axi_bresp                                  ,
    output    wire                          s06_axi_bvalid                                 ,
    input                                   s06_axi_bready                                 ,

    input                                   s07_axi_awid                                   ,
    input               [31:0]              s07_axi_awaddr                                 ,
    input               [ 7:0]              s07_axi_awlen                                  ,
    input               [ 2:0]              s07_axi_awsize                                 ,
    input               [ 1:0]              s07_axi_awburst                                ,
    input                                   s07_axi_awlock                                 ,
    input               [ 3:0]              s07_axi_awcache                                ,
    input               [ 2:0]              s07_axi_awprot                                 ,
    input               [ 3:0]              s07_axi_awqos                                  ,
    input                                   s07_axi_awvalid                                ,
    output    wire                          s07_axi_awready                                ,
    input               [255:0]             s07_axi_wdata                                  ,
    input               [31:0]              s07_axi_wstrb                                  ,
    input                                   s07_axi_wlast                                  ,
    input                                   s07_axi_wvalid                                 ,
    output    wire                          s07_axi_wready                                 ,
    output    wire                          s07_axi_bid                                    ,
    output    wire      [ 1:0]              s07_axi_bresp                                  ,
    output    wire                          s07_axi_bvalid                                 ,
    input                                   s07_axi_bready                                 ,

    output    wire      [ 3:0]              m00_axi_awid                                   ,
    output    wire      [31:0]              m00_axi_awaddr                                 ,
    output    wire      [ 7:0]              m00_axi_awlen                                  ,
    output    wire      [ 2:0]              m00_axi_awsize                                 ,
    output    wire      [ 1:0]              m00_axi_awburst                                ,
    output    wire                          m00_axi_awlock                                 ,
    output    wire      [ 3:0]              m00_axi_awcache                                ,
    output    wire      [ 2:0]              m00_axi_awprot                                 ,
    output    wire      [ 3:0]              m00_axi_awqos                                  ,
    output    wire                          m00_axi_awvalid                                ,
    input                                   m00_axi_awready                                ,
    output    wire      [255:0]             m00_axi_wdata                                  ,
    output    wire      [31:0]              m00_axi_wstrb                                  ,
    output    wire                          m00_axi_wlast                                  ,
    output    wire                          m00_axi_wvalid                                 ,
    input                                   m00_axi_wready                                 ,
    input               [ 3:0]              m00_axi_bid                                    ,
    input               [ 1:0]              m00_axi_bresp                                  ,
    input                                   m00_axi_bvalid                                 ,
    output    wire                          m00_axi_bready
);

parameter                                   UDLY                     = 1                   ;

//////////////////////////////////////////////////
//1. AXI Interconnect
//////////////////////////////////////////////////
DMA_ARB_AXI_INTERCONNECT dma_arb_axi_interconnect(
    .INTERCONNECT_ACLK                   (dma_clk                                      ),
    .INTERCONNECT_ARESETN                (dma_rst_n                                    ),
    .S00_AXI_ACLK                        (dma_clk                                      ),
    .S00_AXI_ARESET_OUT_N                (                                             ),
    .S00_AXI_AWID                        (s00_axi_awid                                 ),
    .S00_AXI_AWADDR                      (s00_axi_awaddr                               ),
    .S00_AXI_AWLEN                       (s00_axi_awlen                                ),
    .S00_AXI_AWSIZE                      (s00_axi_awsize                               ),
    .S00_AXI_AWBURST                     (s00_axi_awburst                              ),
    .S00_AXI_AWLOCK                      (s00_axi_awlock                               ),
    .S00_AXI_AWCACHE                     (s00_axi_awcache                              ),
    .S00_AXI_AWPROT                      (s00_axi_awprot                               ),
    .S00_AXI_AWQOS                       (s00_axi_awqos                                ),
    .S00_AXI_AWVALID                     (s00_axi_awvalid                              ),
    .S00_AXI_AWREADY                     (s00_axi_awready                              ),
    .S00_AXI_WDATA                       (s00_axi_wdata                                ),
    .S00_AXI_WSTRB                       (s00_axi_wstrb                                ),
    .S00_AXI_WLAST                       (s00_axi_wlast                                ),
    .S00_AXI_WVALID                      (s00_axi_wvalid                               ),
    .S00_AXI_WREADY                      (s00_axi_wready                               ),
    .S00_AXI_BID                         (s00_axi_bid                                  ),
    .S00_AXI_BRESP                       (s00_axi_bresp                                ),
    .S00_AXI_BVALID                      (s00_axi_bvalid                               ),
    .S00_AXI_BREADY                      (s00_axi_bready                               ),
    .S00_AXI_ARID                        (1'd0                                         ),
    .S00_AXI_ARADDR                      (32'd0                                        ),
    .S00_AXI_ARLEN                       (8'd0                                         ),
    .S00_AXI_ARSIZE                      (3'd0                                         ),
    .S00_AXI_ARBURST                     (2'd0                                         ),
    .S00_AXI_ARLOCK                      (1'd0                                         ),
    .S00_AXI_ARCACHE                     (4'd0                                         ),
    .S00_AXI_ARPROT                      (3'd0                                         ),
    .S00_AXI_ARQOS                       (4'd0                                         ),
    .S00_AXI_ARVALID                     (1'd0                                         ),
    .S00_AXI_ARREADY                     (                                             ),
    .S00_AXI_RID                         (                                             ),
    .S00_AXI_RDATA                       (                                             ),
    .S00_AXI_RRESP                       (                                             ),
    .S00_AXI_RLAST                       (                                             ),
    .S00_AXI_RVALID                      (                                             ),
    .S00_AXI_RREADY                      (1'd0                                         ),
    .S01_AXI_ACLK                        (dma_clk                                      ),
    .S01_AXI_ARESET_OUT_N                (                                             ),
    .S01_AXI_AWID                        (s01_axi_awid                                 ),
    .S01_AXI_AWADDR                      (s01_axi_awaddr                               ),
    .S01_AXI_AWLEN                       (s01_axi_awlen                                ),
    .S01_AXI_AWSIZE                      (s01_axi_awsize                               ),
    .S01_AXI_AWBURST                     (s01_axi_awburst                              ),
    .S01_AXI_AWLOCK                      (s01_axi_awlock                               ),
    .S01_AXI_AWCACHE                     (s01_axi_awcache                              ),
    .S01_AXI_AWPROT                      (s01_axi_awprot                               ),
    .S01_AXI_AWQOS                       (s01_axi_awqos                                ),
    .S01_AXI_AWVALID                     (s01_axi_awvalid                              ),
    .S01_AXI_AWREADY                     (s01_axi_awready                              ),
    .S01_AXI_WDATA                       (s01_axi_wdata                                ),
    .S01_AXI_WSTRB                       (s01_axi_wstrb                                ),
    .S01_AXI_WLAST                       (s01_axi_wlast                                ),
    .S01_AXI_WVALID                      (s01_axi_wvalid                               ),
    .S01_AXI_WREADY                      (s01_axi_wready                               ),
    .S01_AXI_BID                         (s01_axi_bid                                  ),
    .S01_AXI_BRESP                       (s01_axi_bresp                                ),
    .S01_AXI_BVALID                      (s01_axi_bvalid                               ),
    .S01_AXI_BREADY                      (s01_axi_bready                               ),
    .S01_AXI_ARID                        (1'd0                                         ),
    .S01_AXI_ARADDR                      (32'd0                                        ),
    .S01_AXI_ARLEN                       (8'd0                                         ),
    .S01_AXI_ARSIZE                      (3'd0                                         ),
    .S01_AXI_ARBURST                     (2'd0                                         ),
    .S01_AXI_ARLOCK                      (1'd0                                         ),
    .S01_AXI_ARCACHE                     (4'd0                                         ),
    .S01_AXI_ARPROT                      (3'd0                                         ),
    .S01_AXI_ARQOS                       (4'd0                                         ),
    .S01_AXI_ARVALID                     (1'd0                                         ),
    .S01_AXI_ARREADY                     (                                             ),
    .S01_AXI_RID                         (                                             ),
    .S01_AXI_RDATA                       (                                             ),
    .S01_AXI_RRESP                       (                                             ),
    .S01_AXI_RLAST                       (                                             ),
    .S01_AXI_RVALID                      (                                             ),
    .S01_AXI_RREADY                      (1'd0                                         ),
    .S02_AXI_ACLK                        (dma_clk                                      ),
    .S02_AXI_ARESET_OUT_N                (                                             ),
    .S02_AXI_AWID                        (s02_axi_awid                                 ),
    .S02_AXI_AWADDR                      (s02_axi_awaddr                               ),
    .S02_AXI_AWLEN                       (s02_axi_awlen                                ),
    .S02_AXI_AWSIZE                      (s02_axi_awsize                               ),
    .S02_AXI_AWBURST                     (s02_axi_awburst                              ),
    .S02_AXI_AWLOCK                      (s02_axi_awlock                               ),
    .S02_AXI_AWCACHE                     (s02_axi_awcache                              ),
    .S02_AXI_AWPROT                      (s02_axi_awprot                               ),
    .S02_AXI_AWQOS                       (s02_axi_awqos                                ),
    .S02_AXI_AWVALID                     (s02_axi_awvalid                              ),
    .S02_AXI_AWREADY                     (s02_axi_awready                              ),
    .S02_AXI_WDATA                       (s02_axi_wdata                                ),
    .S02_AXI_WSTRB                       (s02_axi_wstrb                                ),
    .S02_AXI_WLAST                       (s02_axi_wlast                                ),
    .S02_AXI_WVALID                      (s02_axi_wvalid                               ),
    .S02_AXI_WREADY                      (s02_axi_wready                               ),
    .S02_AXI_BID                         (s02_axi_bid                                  ),
    .S02_AXI_BRESP                       (s02_axi_bresp                                ),
    .S02_AXI_BVALID                      (s02_axi_bvalid                               ),
    .S02_AXI_BREADY                      (s02_axi_bready                               ),
    .S02_AXI_ARID                        (1'd0                                         ),
    .S02_AXI_ARADDR                      (32'd0                                        ),
    .S02_AXI_ARLEN                       (8'd0                                         ),
    .S02_AXI_ARSIZE                      (3'd0                                         ),
    .S02_AXI_ARBURST                     (2'd0                                         ),
    .S02_AXI_ARLOCK                      (1'd0                                         ),
    .S02_AXI_ARCACHE                     (4'd0                                         ),
    .S02_AXI_ARPROT                      (3'd0                                         ),
    .S02_AXI_ARQOS                       (4'd0                                         ),
    .S02_AXI_ARVALID                     (1'd0                                         ),
    .S02_AXI_ARREADY                     (                                             ),
    .S02_AXI_RID                         (                                             ),
    .S02_AXI_RDATA                       (                                             ),
    .S02_AXI_RRESP                       (                                             ),
    .S02_AXI_RLAST                       (                                             ),
    .S02_AXI_RVALID                      (                                             ),
    .S02_AXI_RREADY                      (1'd0                                         ),
    .S03_AXI_ACLK                        (dma_clk                                      ),
    .S03_AXI_ARESET_OUT_N                (                                             ),
    .S03_AXI_AWID                        (s03_axi_awid                                 ),
    .S03_AXI_AWADDR                      (s03_axi_awaddr                               ),
    .S03_AXI_AWLEN                       (s03_axi_awlen                                ),
    .S03_AXI_AWSIZE                      (s03_axi_awsize                               ),
    .S03_AXI_AWBURST                     (s03_axi_awburst                              ),
    .S03_AXI_AWLOCK                      (s03_axi_awlock                               ),
    .S03_AXI_AWCACHE                     (s03_axi_awcache                              ),
    .S03_AXI_AWPROT                      (s03_axi_awprot                               ),
    .S03_AXI_AWQOS                       (s03_axi_awqos                                ),
    .S03_AXI_AWVALID                     (s03_axi_awvalid                              ),
    .S03_AXI_AWREADY                     (s03_axi_awready                              ),
    .S03_AXI_WDATA                       (s03_axi_wdata                                ),
    .S03_AXI_WSTRB                       (s03_axi_wstrb                                ),
    .S03_AXI_WLAST                       (s03_axi_wlast                                ),
    .S03_AXI_WVALID                      (s03_axi_wvalid                               ),
    .S03_AXI_WREADY                      (s03_axi_wready                               ),
    .S03_AXI_BID                         (s03_axi_bid                                  ),
    .S03_AXI_BRESP                       (s03_axi_bresp                                ),
    .S03_AXI_BVALID                      (s03_axi_bvalid                               ),
    .S03_AXI_BREADY                      (s03_axi_bready                               ),
    .S03_AXI_ARID                        (1'd0                                         ),
    .S03_AXI_ARADDR                      (32'd0                                        ),
    .S03_AXI_ARLEN                       (8'd0                                         ),
    .S03_AXI_ARSIZE                      (3'd0                                         ),
    .S03_AXI_ARBURST                     (2'd0                                         ),
    .S03_AXI_ARLOCK                      (1'd0                                         ),
    .S03_AXI_ARCACHE                     (4'd0                                         ),
    .S03_AXI_ARPROT                      (3'd0                                         ),
    .S03_AXI_ARQOS                       (4'd0                                         ),
    .S03_AXI_ARVALID                     (1'd0                                         ),
    .S03_AXI_ARREADY                     (                                             ),
    .S03_AXI_RID                         (                                             ),
    .S03_AXI_RDATA                       (                                             ),
    .S03_AXI_RRESP                       (                                             ),
    .S03_AXI_RLAST                       (                                             ),
    .S03_AXI_RVALID                      (                                             ),
    .S03_AXI_RREADY                      (1'd0                                         ),
    .S04_AXI_ACLK                        (dma_clk                                      ),
    .S04_AXI_ARESET_OUT_N                (                                             ),
    .S04_AXI_AWID                        (s04_axi_awid                                 ),
    .S04_AXI_AWADDR                      (s04_axi_awaddr                               ),
    .S04_AXI_AWLEN                       (s04_axi_awlen                                ),
    .S04_AXI_AWSIZE                      (s04_axi_awsize                               ),
    .S04_AXI_AWBURST                     (s04_axi_awburst                              ),
    .S04_AXI_AWLOCK                      (s04_axi_awlock                               ),
    .S04_AXI_AWCACHE                     (s04_axi_awcache                              ),
    .S04_AXI_AWPROT                      (s04_axi_awprot                               ),
    .S04_AXI_AWQOS                       (s04_axi_awqos                                ),
    .S04_AXI_AWVALID                     (s04_axi_awvalid                              ),
    .S04_AXI_AWREADY                     (s04_axi_awready                              ),
    .S04_AXI_WDATA                       (s04_axi_wdata                                ),
    .S04_AXI_WSTRB                       (s04_axi_wstrb                                ),
    .S04_AXI_WLAST                       (s04_axi_wlast                                ),
    .S04_AXI_WVALID                      (s04_axi_wvalid                               ),
    .S04_AXI_WREADY                      (s04_axi_wready                               ),
    .S04_AXI_BID                         (s04_axi_bid                                  ),
    .S04_AXI_BRESP                       (s04_axi_bresp                                ),
    .S04_AXI_BVALID                      (s04_axi_bvalid                               ),
    .S04_AXI_BREADY                      (s04_axi_bready                               ),
    .S04_AXI_ARID                        (1'd0                                         ),
    .S04_AXI_ARADDR                      (32'd0                                        ),
    .S04_AXI_ARLEN                       (8'd0                                         ),
    .S04_AXI_ARSIZE                      (3'd0                                         ),
    .S04_AXI_ARBURST                     (2'd0                                         ),
    .S04_AXI_ARLOCK                      (1'd0                                         ),
    .S04_AXI_ARCACHE                     (4'd0                                         ),
    .S04_AXI_ARPROT                      (3'd0                                         ),
    .S04_AXI_ARQOS                       (4'd0                                         ),
    .S04_AXI_ARVALID                     (1'd0                                         ),
    .S04_AXI_ARREADY                     (                                             ),
    .S04_AXI_RID                         (                                             ),
    .S04_AXI_RDATA                       (                                             ),
    .S04_AXI_RRESP                       (                                             ),
    .S04_AXI_RLAST                       (                                             ),
    .S04_AXI_RVALID                      (                                             ),
    .S04_AXI_RREADY                      (1'd0                                         ),
    .S05_AXI_ACLK                        (dma_clk                                      ),
    .S05_AXI_ARESET_OUT_N                (                                             ),
    .S05_AXI_AWID                        (s05_axi_awid                                 ),
    .S05_AXI_AWADDR                      (s05_axi_awaddr                               ),
    .S05_AXI_AWLEN                       (s05_axi_awlen                                ),
    .S05_AXI_AWSIZE                      (s05_axi_awsize                               ),
    .S05_AXI_AWBURST                     (s05_axi_awburst                              ),
    .S05_AXI_AWLOCK                      (s05_axi_awlock                               ),
    .S05_AXI_AWCACHE                     (s05_axi_awcache                              ),
    .S05_AXI_AWPROT                      (s05_axi_awprot                               ),
    .S05_AXI_AWQOS                       (s05_axi_awqos                                ),
    .S05_AXI_AWVALID                     (s05_axi_awvalid                              ),
    .S05_AXI_AWREADY                     (s05_axi_awready                              ),
    .S05_AXI_WDATA                       (s05_axi_wdata                                ),
    .S05_AXI_WSTRB                       (s05_axi_wstrb                                ),
    .S05_AXI_WLAST                       (s05_axi_wlast                                ),
    .S05_AXI_WVALID                      (s05_axi_wvalid                               ),
    .S05_AXI_WREADY                      (s05_axi_wready                               ),
    .S05_AXI_BID                         (s05_axi_bid                                  ),
    .S05_AXI_BRESP                       (s05_axi_bresp                                ),
    .S05_AXI_BVALID                      (s05_axi_bvalid                               ),
    .S05_AXI_BREADY                      (s05_axi_bready                               ),
    .S05_AXI_ARID                        (1'd0                                         ),
    .S05_AXI_ARADDR                      (32'd0                                        ),
    .S05_AXI_ARLEN                       (8'd0                                         ),
    .S05_AXI_ARSIZE                      (3'd0                                         ),
    .S05_AXI_ARBURST                     (2'd0                                         ),
    .S05_AXI_ARLOCK                      (1'd0                                         ),
    .S05_AXI_ARCACHE                     (4'd0                                         ),
    .S05_AXI_ARPROT                      (3'd0                                         ),
    .S05_AXI_ARQOS                       (4'd0                                         ),
    .S05_AXI_ARVALID                     (1'd0                                         ),
    .S05_AXI_ARREADY                     (                                             ),
    .S05_AXI_RID                         (                                             ),
    .S05_AXI_RDATA                       (                                             ),
    .S05_AXI_RRESP                       (                                             ),
    .S05_AXI_RLAST                       (                                             ),
    .S05_AXI_RVALID                      (                                             ),
    .S05_AXI_RREADY                      (1'd0                                         ),
    .S06_AXI_ACLK                        (dma_clk                                      ),
    .S06_AXI_ARESET_OUT_N                (                                             ),
    .S06_AXI_AWID                        (s06_axi_awid                                 ),
    .S06_AXI_AWADDR                      (s06_axi_awaddr                               ),
    .S06_AXI_AWLEN                       (s06_axi_awlen                                ),
    .S06_AXI_AWSIZE                      (s06_axi_awsize                               ),
    .S06_AXI_AWBURST                     (s06_axi_awburst                              ),
    .S06_AXI_AWLOCK                      (s06_axi_awlock                               ),
    .S06_AXI_AWCACHE                     (s06_axi_awcache                              ),
    .S06_AXI_AWPROT                      (s06_axi_awprot                               ),
    .S06_AXI_AWQOS                       (s06_axi_awqos                                ),
    .S06_AXI_AWVALID                     (s06_axi_awvalid                              ),
    .S06_AXI_AWREADY                     (s06_axi_awready                              ),
    .S06_AXI_WDATA                       (s06_axi_wdata                                ),
    .S06_AXI_WSTRB                       (s06_axi_wstrb                                ),
    .S06_AXI_WLAST                       (s06_axi_wlast                                ),
    .S06_AXI_WVALID                      (s06_axi_wvalid                               ),
    .S06_AXI_WREADY                      (s06_axi_wready                               ),
    .S06_AXI_BID                         (s06_axi_bid                                  ),
    .S06_AXI_BRESP                       (s06_axi_bresp                                ),
    .S06_AXI_BVALID                      (s06_axi_bvalid                               ),
    .S06_AXI_BREADY                      (s06_axi_bready                               ),
    .S06_AXI_ARID                        (1'd0                                         ),
    .S06_AXI_ARADDR                      (32'd0                                        ),
    .S06_AXI_ARLEN                       (8'd0                                         ),
    .S06_AXI_ARSIZE                      (3'd0                                         ),
    .S06_AXI_ARBURST                     (2'd0                                         ),
    .S06_AXI_ARLOCK                      (1'd0                                         ),
    .S06_AXI_ARCACHE                     (4'd0                                         ),
    .S06_AXI_ARPROT                      (3'd0                                         ),
    .S06_AXI_ARQOS                       (4'd0                                         ),
    .S06_AXI_ARVALID                     (1'd0                                         ),
    .S06_AXI_ARREADY                     (                                             ),
    .S06_AXI_RID                         (                                             ),
    .S06_AXI_RDATA                       (                                             ),
    .S06_AXI_RRESP                       (                                             ),
    .S06_AXI_RLAST                       (                                             ),
    .S06_AXI_RVALID                      (                                             ),
    .S06_AXI_RREADY                      (1'd0                                         ),
    .S07_AXI_ACLK                        (dma_clk                                      ),
    .S07_AXI_ARESET_OUT_N                (                                             ),
    .S07_AXI_AWID                        (s07_axi_awid                                 ),
    .S07_AXI_AWADDR                      (s07_axi_awaddr                               ),
    .S07_AXI_AWLEN                       (s07_axi_awlen                                ),
    .S07_AXI_AWSIZE                      (s07_axi_awsize                               ),
    .S07_AXI_AWBURST                     (s07_axi_awburst                              ),
    .S07_AXI_AWLOCK                      (s07_axi_awlock                               ),
    .S07_AXI_AWCACHE                     (s07_axi_awcache                              ),
    .S07_AXI_AWPROT                      (s07_axi_awprot                               ),
    .S07_AXI_AWQOS                       (s07_axi_awqos                                ),
    .S07_AXI_AWVALID                     (s07_axi_awvalid                              ),
    .S07_AXI_AWREADY                     (s07_axi_awready                              ),
    .S07_AXI_WDATA                       (s07_axi_wdata                                ),
    .S07_AXI_WSTRB                       (s07_axi_wstrb                                ),
    .S07_AXI_WLAST                       (s07_axi_wlast                                ),
    .S07_AXI_WVALID                      (s07_axi_wvalid                               ),
    .S07_AXI_WREADY                      (s07_axi_wready                               ),
    .S07_AXI_BID                         (s07_axi_bid                                  ),
    .S07_AXI_BRESP                       (s07_axi_bresp                                ),
    .S07_AXI_BVALID                      (s07_axi_bvalid                               ),
    .S07_AXI_BREADY                      (s07_axi_bready                               ),
    .S07_AXI_ARID                        (1'd0                                         ),
    .S07_AXI_ARADDR                      (32'd0                                        ),
    .S07_AXI_ARLEN                       (8'd0                                         ),
    .S07_AXI_ARSIZE                      (3'd0                                         ),
    .S07_AXI_ARBURST                     (2'd0                                         ),
    .S07_AXI_ARLOCK                      (1'd0                                         ),
    .S07_AXI_ARCACHE                     (4'd0                                         ),
    .S07_AXI_ARPROT                      (3'd0                                         ),
    .S07_AXI_ARQOS                       (4'd0                                         ),
    .S07_AXI_ARVALID                     (1'd0                                         ),
    .S07_AXI_ARREADY                     (                                             ),
    .S07_AXI_RID                         (                                             ),
    .S07_AXI_RDATA                       (                                             ),
    .S07_AXI_RRESP                       (                                             ),
    .S07_AXI_RLAST                       (                                             ),
    .S07_AXI_RVALID                      (                                             ),
    .S07_AXI_RREADY                      (1'd0                                         ),
    .M00_AXI_ACLK                        (dma_clk                                      ),
    .M00_AXI_ARESET_OUT_N                (                                             ),
    .M00_AXI_AWID                        (m00_axi_awid                                 ),
    .M00_AXI_AWADDR                      (m00_axi_awaddr                               ),
    .M00_AXI_AWLEN                       (m00_axi_awlen                                ),
    .M00_AXI_AWSIZE                      (m00_axi_awsize                               ),
    .M00_AXI_AWBURST                     (m00_axi_awburst                              ),
    .M00_AXI_AWLOCK                      (m00_axi_awlock                               ),
    .M00_AXI_AWCACHE                     (m00_axi_awcache                              ),
    .M00_AXI_AWPROT                      (m00_axi_awprot                               ),
    .M00_AXI_AWQOS                       (m00_axi_awqos                                ),
    .M00_AXI_AWVALID                     (m00_axi_awvalid                              ),
    .M00_AXI_AWREADY                     (m00_axi_awready                              ),
    .M00_AXI_WDATA                       (m00_axi_wdata                                ),
    .M00_AXI_WSTRB                       (m00_axi_wstrb                                ),
    .M00_AXI_WLAST                       (m00_axi_wlast                                ),
    .M00_AXI_WVALID                      (m00_axi_wvalid                               ),
    .M00_AXI_WREADY                      (m00_axi_wready                               ),
    .M00_AXI_BID                         (m00_axi_bid                                  ),
    .M00_AXI_BRESP                       (m00_axi_bresp                                ),
    .M00_AXI_BVALID                      (m00_axi_bvalid                               ),
    .M00_AXI_BREADY                      (m00_axi_bready                               ),
    .M00_AXI_ARID                        (                                             ),
    .M00_AXI_ARADDR                      (                                             ),
    .M00_AXI_ARLEN                       (                                             ),
    .M00_AXI_ARSIZE                      (                                             ),
    .M00_AXI_ARBURST                     (                                             ),
    .M00_AXI_ARLOCK                      (                                             ),
    .M00_AXI_ARCACHE                     (                                             ),
    .M00_AXI_ARPROT                      (                                             ),
    .M00_AXI_ARQOS                       (                                             ),
    .M00_AXI_ARVALID                     (                                             ),
    .M00_AXI_ARREADY                     (1'd0                                         ),
    .M00_AXI_RID                         (4'd0                                         ),
    .M00_AXI_RDATA                       (256'd0                                       ),
    .M00_AXI_RRESP                       (2'd0                                         ),
    .M00_AXI_RLAST                       (1'd0                                         ),
    .M00_AXI_RVALID                      (1'd0                                         ),
    .M00_AXI_RREADY                      (                                             )
);

endmodule
