`timescale 1ns / 1ps

module BUS_ARB(
    input                                   s01_axi_clk                                    ,
    input                                   s01_axi_rst_n                                  ,
    input                                   s00_axi_clk                                    ,
    input                                   s00_axi_rst_n                                  ,
    input                                   mig_ddr4_clk                                   ,
    input                                   mig_ddr4_rst_n                                 ,

    input               [ 3:0]              s00_axi_awid                                   ,
    input               [31:0]              s00_axi_awaddr                                 ,
    input               [ 7:0]              s00_axi_awlen                                  ,
    input               [ 2:0]              s00_axi_awsize                                 ,
    input               [ 1:0]              s00_axi_awburst                                ,
    input                                   s00_axi_awlock                                 ,
    input               [ 3:0]              s00_axi_awcache                                ,
    input               [ 2:0]              s00_axi_awprot                                 ,
    input               [ 3:0]              s00_axi_awqos                                  ,
    input                                   s00_axi_awvalid                                ,
    output    wire                          s00_axi_awready                                ,
    input               [255:0]             s00_axi_wdata                                  ,
    input               [31:0]              s00_axi_wstrb                                  ,
    input                                   s00_axi_wlast                                  ,
    input                                   s00_axi_wvalid                                 ,
    output    wire                          s00_axi_wready                                 ,
    output    wire      [ 3:0]              s00_axi_bid                                    ,
    output    wire      [ 1:0]              s00_axi_bresp                                  ,
    output    wire                          s00_axi_bvalid                                 ,
    input                                   s00_axi_bready                                 ,

    input               [31:0]              s01_axi_awaddr                                 ,
    input               [ 2:0]              s01_axi_awprot                                 ,
    input                                   s01_axi_awvalid                                ,
    output    wire                          s01_axi_awready                                ,
    input               [31:0]              s01_axi_wdata                                  ,
    input               [ 3:0]              s01_axi_wstrb                                  ,
    input                                   s01_axi_wvalid                                 ,
    output    wire                          s01_axi_wready                                 ,
    output    wire      [ 1:0]              s01_axi_bresp                                  ,
    output    wire                          s01_axi_bvalid                                 ,
    input                                   s01_axi_bready                                 ,
    input               [31:0]              s01_axi_araddr                                 ,
    input               [ 2:0]              s01_axi_arprot                                 ,
    input                                   s01_axi_arvalid                                ,
    output    wire                          s01_axi_arready                                ,
    output    wire      [31:0]              s01_axi_rdata                                  ,
    output    wire      [ 1:0]              s01_axi_rresp                                  ,
    output    wire                          s01_axi_rvalid                                 ,
    input                                   s01_axi_rready                                 ,

    output    wire      [ 7:0]              m_axi_mem_awid                                 ,
    output    wire      [31:0]              m_axi_mem_awaddr                               ,
    output    wire      [ 7:0]              m_axi_mem_awlen                                ,
    output    wire      [ 2:0]              m_axi_mem_awsize                               ,
    output    wire      [ 1:0]              m_axi_mem_awburst                              ,
    output    wire                          m_axi_mem_awlock                               ,
    output    wire      [ 3:0]              m_axi_mem_awcache                              ,
    output    wire      [ 2:0]              m_axi_mem_awprot                               ,
    output    wire      [ 3:0]              m_axi_mem_awqos                                ,
    output    wire                          m_axi_mem_awvalid                              ,
    input                                   m_axi_mem_awready                              ,
    output    wire      [255:0]             m_axi_mem_wdata                                ,
    output    wire      [31:0]              m_axi_mem_wstrb                                ,
    output    wire                          m_axi_mem_wlast                                ,
    output    wire                          m_axi_mem_wvalid                               ,
    input                                   m_axi_mem_wready                               ,
    input               [ 7:0]              m_axi_mem_bid                                  ,
    input               [ 1:0]              m_axi_mem_bresp                                ,
    input                                   m_axi_mem_bvalid                               ,
    output    wire                          m_axi_mem_bready                               ,
    output    wire      [ 7:0]              m_axi_mem_arid                                 ,
    output    wire      [31:0]              m_axi_mem_araddr                               ,
    output    wire      [ 7:0]              m_axi_mem_arlen                                ,
    output    wire      [ 2:0]              m_axi_mem_arsize                               ,
    output    wire      [ 1:0]              m_axi_mem_arburst                              ,
    output    wire                          m_axi_mem_arlock                               ,
    output    wire      [ 3:0]              m_axi_mem_arcache                              ,
    output    wire      [ 2:0]              m_axi_mem_arprot                               ,
    output    wire      [ 3:0]              m_axi_mem_arqos                                ,
    output    wire                          m_axi_mem_arvalid                              ,
    input                                   m_axi_mem_arready                              ,
    input               [ 7:0]              m_axi_mem_rid                                  ,
    input               [255:0]             m_axi_mem_rdata                                ,
    input               [ 1:0]              m_axi_mem_rresp                                ,
    input                                   m_axi_mem_rlast                                ,
    input                                   m_axi_mem_rvalid                               ,
    output    wire                          m_axi_mem_rready
);

wire                    [31:0]              s01_full_axi_awaddr                            ;
wire                    [ 7:0]              s01_full_axi_awlen                             ;
wire                    [ 2:0]              s01_full_axi_awsize                            ;
wire                    [ 1:0]              s01_full_axi_awburst                           ;
wire                                        s01_full_axi_awlock                            ;
wire                    [ 3:0]              s01_full_axi_awcache                           ;
wire                    [ 2:0]              s01_full_axi_awprot                            ;
wire                    [ 3:0]              s01_full_axi_awqos                             ;
wire                                        s01_full_axi_awvalid                           ;
wire                                        s01_full_axi_awready                           ;
wire                    [31:0]              s01_full_axi_wdata                             ;
wire                    [ 3:0]              s01_full_axi_wstrb                             ;
wire                                        s01_full_axi_wlast                             ;
wire                                        s01_full_axi_wvalid                            ;
wire                                        s01_full_axi_wready                            ;
wire                    [ 1:0]              s01_full_axi_bresp                             ;
wire                                        s01_full_axi_bvalid                            ;
wire                                        s01_full_axi_bready                            ;
wire                    [31:0]              s01_full_axi_araddr                            ;
wire                    [ 7:0]              s01_full_axi_arlen                             ;
wire                    [ 2:0]              s01_full_axi_arsize                            ;
wire                    [ 1:0]              s01_full_axi_arburst                           ;
wire                                        s01_full_axi_arlock                            ;
wire                    [ 3:0]              s01_full_axi_arcache                           ;
wire                    [ 2:0]              s01_full_axi_arprot                            ;
wire                    [ 3:0]              s01_full_axi_arqos                             ;
wire                                        s01_full_axi_arvalid                           ;
wire                                        s01_full_axi_arready                           ;
wire                    [31:0]              s01_full_axi_rdata                             ;
wire                    [ 1:0]              s01_full_axi_rresp                             ;
wire                                        s01_full_axi_rlast                             ;
wire                                        s01_full_axi_rvalid                            ;
wire                                        s01_full_axi_rready                            ;

//////////////////////////////////////////////////
//1. S01 AXI Protocol Conversion
//////////////////////////////////////////////////
BUS_ARB_ASU_AXI_PROTOCOL_CONVERTER bus_arb_s01_axi_protocol_converter(
    .aclk                                (s01_axi_clk                                  ),
    .aresetn                             (s01_axi_rst_n                                ),
    .s_axi_awaddr                        (s01_axi_awaddr                               ),
    .s_axi_awprot                        (s01_axi_awprot                               ),
    .s_axi_awvalid                       (s01_axi_awvalid                              ),
    .s_axi_awready                       (s01_axi_awready                              ),
    .s_axi_wdata                         (s01_axi_wdata                                ),
    .s_axi_wstrb                         (s01_axi_wstrb                                ),
    .s_axi_wvalid                        (s01_axi_wvalid                               ),
    .s_axi_wready                        (s01_axi_wready                               ),
    .s_axi_bresp                         (s01_axi_bresp                                ),
    .s_axi_bvalid                        (s01_axi_bvalid                               ),
    .s_axi_bready                        (s01_axi_bready                               ),
    .s_axi_araddr                        (s01_axi_araddr                               ),
    .s_axi_arprot                        (s01_axi_arprot                               ),
    .s_axi_arvalid                       (s01_axi_arvalid                              ),
    .s_axi_arready                       (s01_axi_arready                              ),
    .s_axi_rdata                         (s01_axi_rdata                                ),
    .s_axi_rresp                         (s01_axi_rresp                                ),
    .s_axi_rvalid                        (s01_axi_rvalid                               ),
    .s_axi_rready                        (s01_axi_rready                               ),
    .m_axi_awaddr                        (s01_full_axi_awaddr                          ),
    .m_axi_awlen                         (s01_full_axi_awlen                           ),
    .m_axi_awsize                        (s01_full_axi_awsize                          ),
    .m_axi_awburst                       (s01_full_axi_awburst                         ),
    .m_axi_awlock                        (s01_full_axi_awlock                          ),
    .m_axi_awcache                       (s01_full_axi_awcache                         ),
    .m_axi_awprot                        (s01_full_axi_awprot                          ),
    .m_axi_awregion                      (                                             ),
    .m_axi_awqos                         (s01_full_axi_awqos                           ),
    .m_axi_awvalid                       (s01_full_axi_awvalid                         ),
    .m_axi_awready                       (s01_full_axi_awready                         ),
    .m_axi_wdata                         (s01_full_axi_wdata                           ),
    .m_axi_wstrb                         (s01_full_axi_wstrb                           ),
    .m_axi_wlast                         (s01_full_axi_wlast                           ),
    .m_axi_wvalid                        (s01_full_axi_wvalid                          ),
    .m_axi_wready                        (s01_full_axi_wready                          ),
    .m_axi_bresp                         (s01_full_axi_bresp                           ),
    .m_axi_bvalid                        (s01_full_axi_bvalid                          ),
    .m_axi_bready                        (s01_full_axi_bready                          ),
    .m_axi_araddr                        (s01_full_axi_araddr                          ),
    .m_axi_arlen                         (s01_full_axi_arlen                           ),
    .m_axi_arsize                        (s01_full_axi_arsize                          ),
    .m_axi_arburst                       (s01_full_axi_arburst                         ),
    .m_axi_arlock                        (s01_full_axi_arlock                          ),
    .m_axi_arcache                       (s01_full_axi_arcache                         ),
    .m_axi_arprot                        (s01_full_axi_arprot                          ),
    .m_axi_arregion                      (                                             ),
    .m_axi_arqos                         (s01_full_axi_arqos                           ),
    .m_axi_arvalid                       (s01_full_axi_arvalid                         ),
    .m_axi_arready                       (s01_full_axi_arready                         ),
    .m_axi_rdata                         (s01_full_axi_rdata                           ),
    .m_axi_rresp                         (s01_full_axi_rresp                           ),
    .m_axi_rlast                         (s01_full_axi_rlast                           ),
    .m_axi_rvalid                        (s01_full_axi_rvalid                          ),
    .m_axi_rready                        (s01_full_axi_rready                          )
);

//////////////////////////////////////////////////
//2. AXI Interconnect
//////////////////////////////////////////////////
BUS_ARB_AXI_INTERCONNECT bus_arb_axi_interconnect(
    .INTERCONNECT_ACLK                   (mig_ddr4_clk                                 ),
    .INTERCONNECT_ARESETN                (mig_ddr4_rst_n                               ),
    .S00_AXI_ARESET_OUT_N                (                                             ),
    .S00_AXI_ACLK                        (s00_axi_clk                                  ),
    .S00_AXI_AWID                        (s00_axi_awid                                 ),
    .S00_AXI_AWADDR                      (s00_axi_awaddr                               ),
    .S00_AXI_AWLEN                       (s00_axi_awlen                                ),
    .S00_AXI_AWSIZE                      (s00_axi_awsize                               ),
    .S00_AXI_AWBURST                     (s00_axi_awburst                              ),
    .S00_AXI_AWLOCK                      (s00_axi_awlock                               ),
    .S00_AXI_AWCACHE                     (s00_axi_awcache                              ),
    .S00_AXI_AWPROT                      (s00_axi_awprot                               ),
    .S00_AXI_AWQOS                       (s00_axi_awqos                                ),
    .S00_AXI_AWVALID                     (s00_axi_awvalid                              ),
    .S00_AXI_AWREADY                     (s00_axi_awready                              ),
    .S00_AXI_WDATA                       (s00_axi_wdata                                ),
    .S00_AXI_WSTRB                       (s00_axi_wstrb                                ),
    .S00_AXI_WLAST                       (s00_axi_wlast                                ),
    .S00_AXI_WVALID                      (s00_axi_wvalid                               ),
    .S00_AXI_WREADY                      (s00_axi_wready                               ),
    .S00_AXI_BID                         (s00_axi_bid                                  ),
    .S00_AXI_BRESP                       (s00_axi_bresp                                ),
    .S00_AXI_BVALID                      (s00_axi_bvalid                               ),
    .S00_AXI_BREADY                      (s00_axi_bready                               ),
    .S00_AXI_ARID                        (4'd0                                         ),
    .S00_AXI_ARADDR                      (32'd0                                        ),
    .S00_AXI_ARLEN                       (8'd0                                         ),
    .S00_AXI_ARSIZE                      (3'd0                                         ),
    .S00_AXI_ARBURST                     (2'd0                                         ),
    .S00_AXI_ARLOCK                      (1'd0                                         ),
    .S00_AXI_ARCACHE                     (4'd0                                         ),
    .S00_AXI_ARPROT                      (3'd0                                         ),
    .S00_AXI_ARQOS                       (4'd0                                         ),
    .S00_AXI_ARVALID                     (1'd0                                         ),
    .S00_AXI_ARREADY                     (                                             ),
    .S00_AXI_RID                         (                                             ),
    .S00_AXI_RDATA                       (                                             ),
    .S00_AXI_RRESP                       (                                             ),
    .S00_AXI_RLAST                       (                                             ),
    .S00_AXI_RVALID                      (                                             ),
    .S00_AXI_RREADY                      (1'd0                                         ),
    .S01_AXI_ARESET_OUT_N                (                                             ),
    .S01_AXI_ACLK                        (s01_axi_clk                                  ),
    .S01_AXI_AWID                        (4'd0                                         ),
    .S01_AXI_AWADDR                      (s01_full_axi_awaddr                          ),
    .S01_AXI_AWLEN                       (s01_full_axi_awlen                           ),
    .S01_AXI_AWSIZE                      (s01_full_axi_awsize                          ),
    .S01_AXI_AWBURST                     (s01_full_axi_awburst                         ),
    .S01_AXI_AWLOCK                      (s01_full_axi_awlock                          ),
    .S01_AXI_AWCACHE                     (s01_full_axi_awcache                         ),
    .S01_AXI_AWPROT                      (s01_full_axi_awprot                          ),
    .S01_AXI_AWQOS                       (s01_full_axi_awqos                           ),
    .S01_AXI_AWVALID                     (s01_full_axi_awvalid                         ),
    .S01_AXI_AWREADY                     (s01_full_axi_awready                         ),
    .S01_AXI_WDATA                       (s01_full_axi_wdata                           ),
    .S01_AXI_WSTRB                       (s01_full_axi_wstrb                           ),
    .S01_AXI_WLAST                       (s01_full_axi_wlast                           ),
    .S01_AXI_WVALID                      (s01_full_axi_wvalid                          ),
    .S01_AXI_WREADY                      (s01_full_axi_wready                          ),
    .S01_AXI_BID                         (                                             ),
    .S01_AXI_BRESP                       (s01_full_axi_bresp                           ),
    .S01_AXI_BVALID                      (s01_full_axi_bvalid                          ),
    .S01_AXI_BREADY                      (s01_full_axi_bready                          ),
    .S01_AXI_ARID                        (4'd0                                         ),
    .S01_AXI_ARADDR                      (s01_full_axi_araddr                          ),
    .S01_AXI_ARLEN                       (s01_full_axi_arlen                           ),
    .S01_AXI_ARSIZE                      (s01_full_axi_arsize                          ),
    .S01_AXI_ARBURST                     (s01_full_axi_arburst                         ),
    .S01_AXI_ARLOCK                      (s01_full_axi_arlock                          ),
    .S01_AXI_ARCACHE                     (s01_full_axi_arcache                         ),
    .S01_AXI_ARPROT                      (s01_full_axi_arprot                          ),
    .S01_AXI_ARQOS                       (s01_full_axi_arqos                           ),
    .S01_AXI_ARVALID                     (s01_full_axi_arvalid                         ),
    .S01_AXI_ARREADY                     (s01_full_axi_arready                         ),
    .S01_AXI_RID                         (                                             ),
    .S01_AXI_RDATA                       (s01_full_axi_rdata                           ),
    .S01_AXI_RRESP                       (s01_full_axi_rresp                           ),
    .S01_AXI_RLAST                       (s01_full_axi_rlast                           ),
    .S01_AXI_RVALID                      (s01_full_axi_rvalid                          ),
    .S01_AXI_RREADY                      (s01_full_axi_rready                          ),
    .M00_AXI_ARESET_OUT_N                (                                             ),
    .M00_AXI_ACLK                        (mig_ddr4_clk                                 ),
    .M00_AXI_AWID                        (m_axi_mem_awid                               ),
    .M00_AXI_AWADDR                      (m_axi_mem_awaddr                             ),
    .M00_AXI_AWLEN                       (m_axi_mem_awlen                              ),
    .M00_AXI_AWSIZE                      (m_axi_mem_awsize                             ),
    .M00_AXI_AWBURST                     (m_axi_mem_awburst                            ),
    .M00_AXI_AWLOCK                      (m_axi_mem_awlock                             ),
    .M00_AXI_AWCACHE                     (m_axi_mem_awcache                            ),
    .M00_AXI_AWPROT                      (m_axi_mem_awprot                             ),
    .M00_AXI_AWQOS                       (m_axi_mem_awqos                              ),
    .M00_AXI_AWVALID                     (m_axi_mem_awvalid                            ),
    .M00_AXI_AWREADY                     (m_axi_mem_awready                            ),
    .M00_AXI_WDATA                       (m_axi_mem_wdata                              ),
    .M00_AXI_WSTRB                       (m_axi_mem_wstrb                              ),
    .M00_AXI_WLAST                       (m_axi_mem_wlast                              ),
    .M00_AXI_WVALID                      (m_axi_mem_wvalid                             ),
    .M00_AXI_WREADY                      (m_axi_mem_wready                             ),
    .M00_AXI_BID                         (m_axi_mem_bid                                ),
    .M00_AXI_BRESP                       (m_axi_mem_bresp                              ),
    .M00_AXI_BVALID                      (m_axi_mem_bvalid                             ),
    .M00_AXI_BREADY                      (m_axi_mem_bready                             ),
    .M00_AXI_ARID                        (m_axi_mem_arid                               ),
    .M00_AXI_ARADDR                      (m_axi_mem_araddr                             ),
    .M00_AXI_ARLEN                       (m_axi_mem_arlen                              ),
    .M00_AXI_ARSIZE                      (m_axi_mem_arsize                             ),
    .M00_AXI_ARBURST                     (m_axi_mem_arburst                            ),
    .M00_AXI_ARLOCK                      (m_axi_mem_arlock                             ),
    .M00_AXI_ARCACHE                     (m_axi_mem_arcache                            ),
    .M00_AXI_ARPROT                      (m_axi_mem_arprot                             ),
    .M00_AXI_ARQOS                       (m_axi_mem_arqos                              ),
    .M00_AXI_ARVALID                     (m_axi_mem_arvalid                            ),
    .M00_AXI_ARREADY                     (m_axi_mem_arready                            ),
    .M00_AXI_RID                         (m_axi_mem_rid                                ),
    .M00_AXI_RDATA                       (m_axi_mem_rdata                              ),
    .M00_AXI_RRESP                       (m_axi_mem_rresp                              ),
    .M00_AXI_RLAST                       (m_axi_mem_rlast                              ),
    .M00_AXI_RVALID                      (m_axi_mem_rvalid                             ),
    .M00_AXI_RREADY                      (m_axi_mem_rready                             )
);

endmodule
