`timescale 1ns / 1ps

// =====
// 1. System Integration
// =====
module ADC_TOP(
    input  wire                             sys_clk             ,
    input  wire                             adc_clk             ,
    input  wire                             afe_clk             ,
    input  wire [7:0]                       jesd_clk            ,
    input  wire                             sys_rst_n           ,
    input  wire                             adc_rst_n           ,
    input  wire                             afe_rst_n           ,
    input  wire [7:0]                       jesd_rst_n          ,
    input  wire                             sysref_in           ,
    input  wire [15:0]                      s_axi_awaddr        ,
    input  wire                             s_axi_awvalid       ,
    output wire                             s_axi_awready       ,
    input  wire [31:0]                      s_axi_wdata         ,
    input  wire [3:0]                       s_axi_wstrb         ,
    input  wire                             s_axi_wvalid        ,
    output wire                             s_axi_wready        ,
    output wire [1:0]                       s_axi_bresp         ,
    output wire                             s_axi_bvalid        ,
    input  wire                             s_axi_bready        ,
    input  wire [15:0]                      s_axi_araddr        ,
    input  wire                             s_axi_arvalid       ,
    output wire                             s_axi_arready       ,
    output wire [31:0]                      s_axi_rdata         ,
    output wire [1:0]                       s_axi_rresp         ,
    output wire                             s_axi_rvalid        ,
    input  wire                             s_axi_rready        ,
    input  wire [63:0]                      afe0_rx_data        ,
    input  wire [7:0]                       afe0_rx_charisk     ,
    input  wire [7:0]                       afe0_rx_disperr     ,
    input  wire [7:0]                       afe0_rx_notintable  ,
    input  wire                             afe0_rx_reset_done  ,
    input  wire                             afe0_pll_lock       ,
    input  wire [1:0]                       afe0_byte_aligned   ,
    output wire                             afe0_rx_encommalign ,
    output wire                             afe0_sync_n         ,
    input  wire [63:0]                      afe1_rx_data        ,
    input  wire [7:0]                       afe1_rx_charisk     ,
    input  wire [7:0]                       afe1_rx_disperr     ,
    input  wire [7:0]                       afe1_rx_notintable  ,
    input  wire                             afe1_rx_reset_done  ,
    input  wire                             afe1_pll_lock       ,
    input  wire [1:0]                       afe1_byte_aligned   ,
    output wire                             afe1_rx_encommalign ,
    output wire                             afe1_sync_n         ,
    input  wire [63:0]                      afe2_rx_data        ,
    input  wire [7:0]                       afe2_rx_charisk     ,
    input  wire [7:0]                       afe2_rx_disperr     ,
    input  wire [7:0]                       afe2_rx_notintable  ,
    input  wire                             afe2_rx_reset_done  ,
    input  wire                             afe2_pll_lock       ,
    input  wire [1:0]                       afe2_byte_aligned   ,
    output wire                             afe2_rx_encommalign ,
    output wire                             afe2_sync_n         ,
    input  wire [63:0]                      afe3_rx_data        ,
    input  wire [7:0]                       afe3_rx_charisk     ,
    input  wire [7:0]                       afe3_rx_disperr     ,
    input  wire [7:0]                       afe3_rx_notintable  ,
    input  wire                             afe3_rx_reset_done  ,
    input  wire                             afe3_pll_lock       ,
    input  wire [1:0]                       afe3_byte_aligned   ,
    output wire                             afe3_rx_encommalign ,
    output wire                             afe3_sync_n         ,
    input  wire [63:0]                      afe4_rx_data        ,
    input  wire [7:0]                       afe4_rx_charisk     ,
    input  wire [7:0]                       afe4_rx_disperr     ,
    input  wire [7:0]                       afe4_rx_notintable  ,
    input  wire                             afe4_rx_reset_done  ,
    input  wire                             afe4_pll_lock       ,
    input  wire [1:0]                       afe4_byte_aligned   ,
    output wire                             afe4_rx_encommalign ,
    output wire                             afe4_sync_n         ,
    input  wire [63:0]                      afe5_rx_data        ,
    input  wire [7:0]                       afe5_rx_charisk     ,
    input  wire [7:0]                       afe5_rx_disperr     ,
    input  wire [7:0]                       afe5_rx_notintable  ,
    input  wire                             afe5_rx_reset_done  ,
    input  wire                             afe5_pll_lock       ,
    input  wire [1:0]                       afe5_byte_aligned   ,
    output wire                             afe5_rx_encommalign ,
    output wire                             afe5_sync_n         ,
    input  wire [63:0]                      afe6_rx_data        ,
    input  wire [7:0]                       afe6_rx_charisk     ,
    input  wire [7:0]                       afe6_rx_disperr     ,
    input  wire [7:0]                       afe6_rx_notintable  ,
    input  wire                             afe6_rx_reset_done  ,
    input  wire                             afe6_pll_lock       ,
    input  wire [1:0]                       afe6_byte_aligned   ,
    output wire                             afe6_rx_encommalign ,
    output wire                             afe6_sync_n         ,
    input  wire [63:0]                      afe7_rx_data        ,
    input  wire [7:0]                       afe7_rx_charisk     ,
    input  wire [7:0]                       afe7_rx_disperr     ,
    input  wire [7:0]                       afe7_rx_notintable  ,
    input  wire                             afe7_rx_reset_done  ,
    input  wire                             afe7_pll_lock       ,
    input  wire [1:0]                       afe7_byte_aligned   ,
    output wire                             afe7_rx_encommalign ,
    output wire                             afe7_sync_n         ,
    output wire [511:0]                     m_axis_afe0_tdata   ,
    output wire [63:0]                      m_axis_afe0_tkeep   ,
    output wire                             m_axis_afe0_tvalid  ,
    output wire                             m_axis_afe0_tlast   ,
    input  wire                             m_axis_afe0_tready  ,
    output wire                             tgc0_slope          ,
    output wire                             tgc0_up_dn          ,
    output wire                             tgc0_prof1          ,
    output wire                             tgc0_prof2          ,
    output wire [511:0]                     m_axis_afe1_tdata   ,
    output wire [63:0]                      m_axis_afe1_tkeep   ,
    output wire                             m_axis_afe1_tvalid  ,
    output wire                             m_axis_afe1_tlast   ,
    input  wire                             m_axis_afe1_tready  ,
    output wire                             tgc1_slope          ,
    output wire                             tgc1_up_dn          ,
    output wire                             tgc1_prof1          ,
    output wire                             tgc1_prof2          ,
    output wire [511:0]                     m_axis_afe2_tdata   ,
    output wire [63:0]                      m_axis_afe2_tkeep   ,
    output wire                             m_axis_afe2_tvalid  ,
    output wire                             m_axis_afe2_tlast   ,
    input  wire                             m_axis_afe2_tready  ,
    output wire                             tgc2_slope          ,
    output wire                             tgc2_up_dn          ,
    output wire                             tgc2_prof1          ,
    output wire                             tgc2_prof2          ,
    output wire [511:0]                     m_axis_afe3_tdata   ,
    output wire [63:0]                      m_axis_afe3_tkeep   ,
    output wire                             m_axis_afe3_tvalid  ,
    output wire                             m_axis_afe3_tlast   ,
    input  wire                             m_axis_afe3_tready  ,
    output wire                             tgc3_slope          ,
    output wire                             tgc3_up_dn          ,
    output wire                             tgc3_prof1          ,
    output wire                             tgc3_prof2          ,
    output wire [511:0]                     m_axis_afe4_tdata   ,
    output wire [63:0]                      m_axis_afe4_tkeep   ,
    output wire                             m_axis_afe4_tvalid  ,
    output wire                             m_axis_afe4_tlast   ,
    input  wire                             m_axis_afe4_tready  ,
    output wire                             tgc4_slope          ,
    output wire                             tgc4_up_dn          ,
    output wire                             tgc4_prof1          ,
    output wire                             tgc4_prof2          ,
    output wire [511:0]                     m_axis_afe5_tdata   ,
    output wire [63:0]                      m_axis_afe5_tkeep   ,
    output wire                             m_axis_afe5_tvalid  ,
    output wire                             m_axis_afe5_tlast   ,
    input  wire                             m_axis_afe5_tready  ,
    output wire                             tgc5_slope          ,
    output wire                             tgc5_up_dn          ,
    output wire                             tgc5_prof1          ,
    output wire                             tgc5_prof2          ,
    output wire [511:0]                     m_axis_afe6_tdata   ,
    output wire [63:0]                      m_axis_afe6_tkeep   ,
    output wire                             m_axis_afe6_tvalid  ,
    output wire                             m_axis_afe6_tlast   ,
    input  wire                             m_axis_afe6_tready  ,
    output wire                             tgc6_slope          ,
    output wire                             tgc6_up_dn          ,
    output wire                             tgc6_prof1          ,
    output wire                             tgc6_prof2          ,
    output wire [511:0]                     m_axis_afe7_tdata   ,
    output wire [63:0]                      m_axis_afe7_tkeep   ,
    output wire                             m_axis_afe7_tvalid  ,
    output wire                             m_axis_afe7_tlast   ,
    input  wire                             m_axis_afe7_tready  ,
    output wire                             tgc7_slope          ,
    output wire                             tgc7_up_dn          ,
    output wire                             tgc7_prof1          ,
    output wire                             tgc7_prof2
);

wire [7:0]                                  afe_en_sys                                  ;
wire [7:0]                                  fifo_clr_sys                                ;
wire [1:0]                                  smp_prec                                    ;
wire [1:0]                                  smp_mode                                    ;
wire                                        frame_fmt                                   ;
wire [1:0]                                  dec_del_mode                                ;
wire [7:0]                                  dec_m                                       ;
wire [7:0]                                  tgc_mask_sys                                ;
wire [1:0]                                  tgc_profile_sys                             ;
wire                                        tgc_up_dn_sys                               ;
wire                                        tgc_slope_sys                               ;
wire                                        tgc_req_sys                                 ;
wire [7:0]                                  afe_en_adc                                  ;
wire                                        tgc_req_afe                                 ;
wire [7:0]                                  tgc_mask_afe                                ;
wire [1:0]                                  tgc_profile_afe                             ;
wire                                        tgc_up_dn_afe                               ;
wire                                        tgc_slope_afe                               ;
wire [7:0]                                  tgc_slope_vec                               ;
wire [7:0]                                  tgc_up_dn_vec                               ;
wire [7:0]                                  tgc_prof1_vec                               ;
wire [7:0]                                  tgc_prof2_vec                               ;
wire                                        tgc_busy_afe                                ;
wire                                        tgc_done_afe                                ;
wire                                        tgc_busy_sys                                ;
wire                                        tgc_done_sys                                ;

wire [7:0]                                  link_ready_adc                              ;
wire [7:0]                                  fifo_empty_adc                              ;
wire [7:0]                                  fifo_full_adc                               ;
wire [7:0]                                  afe_idle_adc                                ;
wire [7:0]                                  pll_lock_adc                                ;
wire [7:0]                                  rx_reset_done_adc                           ;
wire [15:0]                                 lane_ready_adc                              ;
wire [15:0]                                 byte_aligned_adc                            ;
wire [15:0]                                 comma_detected_adc                          ;
wire [7:0]                                  fifo_overflow_evt_afe                       ;
wire [7:0]                                  data_drop_evt_adc                           ;
wire [7:0]                                  link_error_evt_adc                          ;
wire [7:0]                                  sysref_seen_evt_adc                         ;
wire [15:0]                                 disparity_evt_adc                           ;
wire [15:0]                                 notintable_evt_adc                          ;

wire [7:0]                                  link_ready_sys                              ;
wire [7:0]                                  fifo_empty_sys                              ;
wire [7:0]                                  fifo_full_sys                               ;
wire [7:0]                                  afe_idle_sys                                ;
wire [7:0]                                  pll_lock_sys                                ;
wire [7:0]                                  rx_reset_done_sys                           ;
wire [15:0]                                 lane_ready_sys                              ;
wire [15:0]                                 byte_aligned_sys                            ;
wire [15:0]                                 comma_detected_sys                          ;
wire                                        sysref_level_sys                            ;
wire [7:0]                                  fifo_overflow_evt_sys                       ;
wire [7:0]                                  data_drop_evt_sys                           ;
wire [7:0]                                  link_error_evt_sys                          ;
wire [7:0]                                  sysref_seen_evt_sys                         ;
wire [15:0]                                 disparity_evt_sys                           ;
wire [15:0]                                 notintable_evt_sys                          ;

assign tgc0_slope  = tgc_slope_vec[0];
assign tgc0_up_dn  = tgc_up_dn_vec[0];
assign tgc0_prof1  = tgc_prof1_vec[0];
assign tgc0_prof2  = tgc_prof2_vec[0];
assign tgc1_slope  = tgc_slope_vec[1];
assign tgc1_up_dn  = tgc_up_dn_vec[1];
assign tgc1_prof1  = tgc_prof1_vec[1];
assign tgc1_prof2  = tgc_prof2_vec[1];
assign tgc2_slope  = tgc_slope_vec[2];
assign tgc2_up_dn  = tgc_up_dn_vec[2];
assign tgc2_prof1  = tgc_prof1_vec[2];
assign tgc2_prof2  = tgc_prof2_vec[2];
assign tgc3_slope  = tgc_slope_vec[3];
assign tgc3_up_dn  = tgc_up_dn_vec[3];
assign tgc3_prof1  = tgc_prof1_vec[3];
assign tgc3_prof2  = tgc_prof2_vec[3];
assign tgc4_slope  = tgc_slope_vec[4];
assign tgc4_up_dn  = tgc_up_dn_vec[4];
assign tgc4_prof1  = tgc_prof1_vec[4];
assign tgc4_prof2  = tgc_prof2_vec[4];
assign tgc5_slope  = tgc_slope_vec[5];
assign tgc5_up_dn  = tgc_up_dn_vec[5];
assign tgc5_prof1  = tgc_prof1_vec[5];
assign tgc5_prof2  = tgc_prof2_vec[5];
assign tgc6_slope  = tgc_slope_vec[6];
assign tgc6_up_dn  = tgc_up_dn_vec[6];
assign tgc6_prof1  = tgc_prof1_vec[6];
assign tgc6_prof2  = tgc_prof2_vec[6];
assign tgc7_slope  = tgc_slope_vec[7];
assign tgc7_up_dn  = tgc_up_dn_vec[7];
assign tgc7_prof1  = tgc_prof1_vec[7];
assign tgc7_prof2  = tgc_prof2_vec[7];

ADC_REG adc_reg(
    .sys_clk                            (sys_clk                                     ),
    .sys_rst_n                          (sys_rst_n                                   ),
    .s_axi_awaddr                       (s_axi_awaddr                                ),
    .s_axi_awvalid                      (s_axi_awvalid                               ),
    .s_axi_awready                      (s_axi_awready                               ),
    .s_axi_wdata                        (s_axi_wdata                                 ),
    .s_axi_wstrb                        (s_axi_wstrb                                 ),
    .s_axi_wvalid                       (s_axi_wvalid                                ),
    .s_axi_wready                       (s_axi_wready                                ),
    .s_axi_bresp                        (s_axi_bresp                                 ),
    .s_axi_bvalid                       (s_axi_bvalid                                ),
    .s_axi_bready                       (s_axi_bready                                ),
    .s_axi_araddr                       (s_axi_araddr                                ),
    .s_axi_arvalid                      (s_axi_arvalid                               ),
    .s_axi_arready                      (s_axi_arready                               ),
    .s_axi_rdata                        (s_axi_rdata                                 ),
    .s_axi_rresp                        (s_axi_rresp                                 ),
    .s_axi_rvalid                       (s_axi_rvalid                                ),
    .s_axi_rready                       (s_axi_rready                                ),
    .link_ready                         (link_ready_sys                              ),
    .fifo_empty                         (fifo_empty_sys                              ),
    .fifo_full                          (fifo_full_sys                               ),
    .afe_idle                           (afe_idle_sys                                ),
    .pll_lock                           (pll_lock_sys                                ),
    .rx_reset_done                      (rx_reset_done_sys                           ),
    .lane_ready                         (lane_ready_sys                              ),
    .byte_aligned                       (byte_aligned_sys                            ),
    .comma_detected                     (comma_detected_sys                          ),
    .sysref_level                       (sysref_level_sys                            ),
    .fifo_overflow_evt                  (fifo_overflow_evt_sys                       ),
    .data_drop_evt                      (data_drop_evt_sys                           ),
    .link_error_evt                     (link_error_evt_sys                          ),
    .sysref_seen_evt                    (sysref_seen_evt_sys                         ),
    .disparity_evt                      (disparity_evt_sys                           ),
    .notintable_evt                     (notintable_evt_sys                          ),
    .tgc_busy                           (tgc_busy_sys                                ),
    .tgc_done                           (tgc_done_sys                                ),
    .afe_en                             (afe_en_sys                                  ),
    .fifo_clr                           (fifo_clr_sys                                ),
    .smp_prec                           (smp_prec                                    ),
    .smp_mode                           (smp_mode                                    ),
    .frame_fmt                          (frame_fmt                                   ),
    .dec_del_mode                       (dec_del_mode                                ),
    .dec_m                              (dec_m                                       ),
    .tgc_mask                           (tgc_mask_sys                                ),
    .tgc_profile_sel                    (tgc_profile_sys                             ),
    .tgc_up_dn                          (tgc_up_dn_sys                               ),
    .tgc_slope_trig                     (tgc_slope_sys                               ),
    .tgc_req                            (tgc_req_sys                                 )
);

ADC_SYNC adc_sync(
    .sys_clk                            (sys_clk                                     ),
    .sys_rst_n                          (sys_rst_n                                   ),
    .adc_clk                            (adc_clk                                     ),
    .adc_rst_n                          (adc_rst_n                                   ),
    .afe_clk                            (afe_clk                                     ),
    .afe_rst_n                          (afe_rst_n                                   ),
    .sysref                             (sysref_in                                   ),
    .afe_en_sys                         (afe_en_sys                                  ),
    .tgc_req_sys                        (tgc_req_sys                                 ),
    .tgc_mask_sys                       (tgc_mask_sys                                ),
    .tgc_profile_sys                    (tgc_profile_sys                             ),
    .tgc_up_dn_sys                      (tgc_up_dn_sys                               ),
    .tgc_slope_sys                      (tgc_slope_sys                               ),
    .link_ready_adc                     (link_ready_adc                              ),
    .fifo_empty_adc                     (fifo_empty_adc                              ),
    .fifo_full_adc                      (fifo_full_adc                               ),
    .afe_idle_adc                       (afe_idle_adc                                ),
    .pll_lock_adc                       (pll_lock_adc                                ),
    .rx_reset_done_adc                  (rx_reset_done_adc                           ),
    .lane_ready_adc                     (lane_ready_adc                              ),
    .byte_aligned_adc                   (byte_aligned_adc                            ),
    .comma_detected_adc                 (comma_detected_adc                          ),
    .data_drop_evt_adc                  (data_drop_evt_adc                           ),
    .link_error_evt_adc                 (link_error_evt_adc                          ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc                         ),
    .disparity_evt_adc                  (disparity_evt_adc                           ),
    .notintable_evt_adc                 (notintable_evt_adc                          ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe                       ),
    .tgc_busy_afe                       (tgc_busy_afe                                ),
    .tgc_done_afe                       (tgc_done_afe                                ),
    .afe_en_adc                         (afe_en_adc                                  ),
    .tgc_req_afe                        (tgc_req_afe                                 ),
    .tgc_mask_afe                       (tgc_mask_afe                                ),
    .tgc_profile_afe                    (tgc_profile_afe                             ),
    .tgc_up_dn_afe                      (tgc_up_dn_afe                               ),
    .tgc_slope_afe                      (tgc_slope_afe                               ),
    .link_ready_sys                     (link_ready_sys                              ),
    .fifo_empty_sys                     (fifo_empty_sys                              ),
    .fifo_full_sys                      (fifo_full_sys                               ),
    .afe_idle_sys                       (afe_idle_sys                                ),
    .pll_lock_sys                       (pll_lock_sys                                ),
    .rx_reset_done_sys                  (rx_reset_done_sys                           ),
    .lane_ready_sys                     (lane_ready_sys                              ),
    .byte_aligned_sys                   (byte_aligned_sys                            ),
    .comma_detected_sys                 (comma_detected_sys                          ),
    .sysref_level_sys                   (sysref_level_sys                            ),
    .fifo_overflow_evt_sys              (fifo_overflow_evt_sys                       ),
    .data_drop_evt_sys                  (data_drop_evt_sys                           ),
    .link_error_evt_sys                 (link_error_evt_sys                          ),
    .sysref_seen_evt_sys                (sysref_seen_evt_sys                         ),
    .disparity_evt_sys                  (disparity_evt_sys                           ),
    .notintable_evt_sys                 (notintable_evt_sys                          ),
    .tgc_busy_sys                       (tgc_busy_sys                                ),
    .tgc_done_sys                       (tgc_done_sys                                )
);

ADC_TGC adc_tgc(
    .afe_clk                            (afe_clk                                     ),
    .afe_rst_n                          (afe_rst_n                                   ),
    .tgc_req                            (tgc_req_afe                                 ),
    .afe_mask                           (tgc_mask_afe                                ),
    .profile_sel                        (tgc_profile_afe                             ),
    .up_dn                              (tgc_up_dn_afe                               ),
    .slope_trig                         (tgc_slope_afe                               ),
    .tgc_slope                          (tgc_slope_vec                               ),
    .tgc_up_dn                          (tgc_up_dn_vec                               ),
    .tgc_prof1                          (tgc_prof1_vec                               ),
    .tgc_prof2                          (tgc_prof2_vec                               ),
    .tgc_busy                           (tgc_busy_afe                                ),
    .tgc_done                           (tgc_done_afe                                )
);

ADC_CHN adc_chn0(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[0]                                  ),
    .jesd_rst_n                         (jesd_rst_n[0]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd0                                         ),
    .afe_en                             (afe_en_adc[0]                                ),
    .fifo_clr                           (fifo_clr_sys[0]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe0_rx_data                                 ),
    .phy_rx_charisk                     (afe0_rx_charisk                              ),
    .phy_rx_disperr                     (afe0_rx_disperr                              ),
    .phy_rx_notintable                  (afe0_rx_notintable                           ),
    .phy_rx_reset_done                  (afe0_rx_reset_done                           ),
    .phy_pll_lock                       (afe0_pll_lock                                ),
    .phy_byte_aligned                   (afe0_byte_aligned                            ),
    .phy_rx_encommalign                 (afe0_rx_encommalign                          ),
    .phy_sync_n                         (afe0_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe0_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe0_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe0_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe0_tlast                            ),
    .m_axis_tready                      (m_axis_afe0_tready                           ),
    .link_ready_adc                     (link_ready_adc[0]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[0]                            ),
    .fifo_full_adc                      (fifo_full_adc[0]                             ),
    .afe_idle_adc                       (afe_idle_adc[0]                              ),
    .pll_lock_adc                       (pll_lock_adc[0]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[0]                         ),
    .lane_ready_adc                     (lane_ready_adc[1:0]                          ),
    .byte_aligned_adc                   (byte_aligned_adc[1:0]                        ),
    .comma_detected_adc                 (comma_detected_adc[1:0]                      ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[0]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[0]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[0]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[0]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[1:0]                       ),
    .notintable_evt_adc                 (notintable_evt_adc[1:0]                      )
);

ADC_CHN adc_chn1(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[1]                                  ),
    .jesd_rst_n                         (jesd_rst_n[1]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd1                                         ),
    .afe_en                             (afe_en_adc[1]                                ),
    .fifo_clr                           (fifo_clr_sys[1]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe1_rx_data                                 ),
    .phy_rx_charisk                     (afe1_rx_charisk                              ),
    .phy_rx_disperr                     (afe1_rx_disperr                              ),
    .phy_rx_notintable                  (afe1_rx_notintable                           ),
    .phy_rx_reset_done                  (afe1_rx_reset_done                           ),
    .phy_pll_lock                       (afe1_pll_lock                                ),
    .phy_byte_aligned                   (afe1_byte_aligned                            ),
    .phy_rx_encommalign                 (afe1_rx_encommalign                          ),
    .phy_sync_n                         (afe1_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe1_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe1_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe1_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe1_tlast                            ),
    .m_axis_tready                      (m_axis_afe1_tready                           ),
    .link_ready_adc                     (link_ready_adc[1]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[1]                            ),
    .fifo_full_adc                      (fifo_full_adc[1]                             ),
    .afe_idle_adc                       (afe_idle_adc[1]                              ),
    .pll_lock_adc                       (pll_lock_adc[1]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[1]                         ),
    .lane_ready_adc                     (lane_ready_adc[3:2]                          ),
    .byte_aligned_adc                   (byte_aligned_adc[3:2]                        ),
    .comma_detected_adc                 (comma_detected_adc[3:2]                      ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[1]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[1]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[1]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[1]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[3:2]                       ),
    .notintable_evt_adc                 (notintable_evt_adc[3:2]                      )
);

ADC_CHN adc_chn2(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[2]                                  ),
    .jesd_rst_n                         (jesd_rst_n[2]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd2                                         ),
    .afe_en                             (afe_en_adc[2]                                ),
    .fifo_clr                           (fifo_clr_sys[2]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe2_rx_data                                 ),
    .phy_rx_charisk                     (afe2_rx_charisk                              ),
    .phy_rx_disperr                     (afe2_rx_disperr                              ),
    .phy_rx_notintable                  (afe2_rx_notintable                           ),
    .phy_rx_reset_done                  (afe2_rx_reset_done                           ),
    .phy_pll_lock                       (afe2_pll_lock                                ),
    .phy_byte_aligned                   (afe2_byte_aligned                            ),
    .phy_rx_encommalign                 (afe2_rx_encommalign                          ),
    .phy_sync_n                         (afe2_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe2_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe2_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe2_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe2_tlast                            ),
    .m_axis_tready                      (m_axis_afe2_tready                           ),
    .link_ready_adc                     (link_ready_adc[2]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[2]                            ),
    .fifo_full_adc                      (fifo_full_adc[2]                             ),
    .afe_idle_adc                       (afe_idle_adc[2]                              ),
    .pll_lock_adc                       (pll_lock_adc[2]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[2]                         ),
    .lane_ready_adc                     (lane_ready_adc[5:4]                          ),
    .byte_aligned_adc                   (byte_aligned_adc[5:4]                        ),
    .comma_detected_adc                 (comma_detected_adc[5:4]                      ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[2]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[2]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[2]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[2]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[5:4]                       ),
    .notintable_evt_adc                 (notintable_evt_adc[5:4]                      )
);

ADC_CHN adc_chn3(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[3]                                  ),
    .jesd_rst_n                         (jesd_rst_n[3]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd3                                         ),
    .afe_en                             (afe_en_adc[3]                                ),
    .fifo_clr                           (fifo_clr_sys[3]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe3_rx_data                                 ),
    .phy_rx_charisk                     (afe3_rx_charisk                              ),
    .phy_rx_disperr                     (afe3_rx_disperr                              ),
    .phy_rx_notintable                  (afe3_rx_notintable                           ),
    .phy_rx_reset_done                  (afe3_rx_reset_done                           ),
    .phy_pll_lock                       (afe3_pll_lock                                ),
    .phy_byte_aligned                   (afe3_byte_aligned                            ),
    .phy_rx_encommalign                 (afe3_rx_encommalign                          ),
    .phy_sync_n                         (afe3_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe3_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe3_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe3_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe3_tlast                            ),
    .m_axis_tready                      (m_axis_afe3_tready                           ),
    .link_ready_adc                     (link_ready_adc[3]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[3]                            ),
    .fifo_full_adc                      (fifo_full_adc[3]                             ),
    .afe_idle_adc                       (afe_idle_adc[3]                              ),
    .pll_lock_adc                       (pll_lock_adc[3]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[3]                         ),
    .lane_ready_adc                     (lane_ready_adc[7:6]                          ),
    .byte_aligned_adc                   (byte_aligned_adc[7:6]                        ),
    .comma_detected_adc                 (comma_detected_adc[7:6]                      ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[3]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[3]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[3]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[3]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[7:6]                       ),
    .notintable_evt_adc                 (notintable_evt_adc[7:6]                      )
);

ADC_CHN adc_chn4(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[4]                                  ),
    .jesd_rst_n                         (jesd_rst_n[4]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd4                                         ),
    .afe_en                             (afe_en_adc[4]                                ),
    .fifo_clr                           (fifo_clr_sys[4]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe4_rx_data                                 ),
    .phy_rx_charisk                     (afe4_rx_charisk                              ),
    .phy_rx_disperr                     (afe4_rx_disperr                              ),
    .phy_rx_notintable                  (afe4_rx_notintable                           ),
    .phy_rx_reset_done                  (afe4_rx_reset_done                           ),
    .phy_pll_lock                       (afe4_pll_lock                                ),
    .phy_byte_aligned                   (afe4_byte_aligned                            ),
    .phy_rx_encommalign                 (afe4_rx_encommalign                          ),
    .phy_sync_n                         (afe4_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe4_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe4_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe4_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe4_tlast                            ),
    .m_axis_tready                      (m_axis_afe4_tready                           ),
    .link_ready_adc                     (link_ready_adc[4]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[4]                            ),
    .fifo_full_adc                      (fifo_full_adc[4]                             ),
    .afe_idle_adc                       (afe_idle_adc[4]                              ),
    .pll_lock_adc                       (pll_lock_adc[4]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[4]                         ),
    .lane_ready_adc                     (lane_ready_adc[9:8]                          ),
    .byte_aligned_adc                   (byte_aligned_adc[9:8]                        ),
    .comma_detected_adc                 (comma_detected_adc[9:8]                      ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[4]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[4]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[4]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[4]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[9:8]                       ),
    .notintable_evt_adc                 (notintable_evt_adc[9:8]                      )
);

ADC_CHN adc_chn5(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[5]                                  ),
    .jesd_rst_n                         (jesd_rst_n[5]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd5                                         ),
    .afe_en                             (afe_en_adc[5]                                ),
    .fifo_clr                           (fifo_clr_sys[5]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe5_rx_data                                 ),
    .phy_rx_charisk                     (afe5_rx_charisk                              ),
    .phy_rx_disperr                     (afe5_rx_disperr                              ),
    .phy_rx_notintable                  (afe5_rx_notintable                           ),
    .phy_rx_reset_done                  (afe5_rx_reset_done                           ),
    .phy_pll_lock                       (afe5_pll_lock                                ),
    .phy_byte_aligned                   (afe5_byte_aligned                            ),
    .phy_rx_encommalign                 (afe5_rx_encommalign                          ),
    .phy_sync_n                         (afe5_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe5_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe5_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe5_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe5_tlast                            ),
    .m_axis_tready                      (m_axis_afe5_tready                           ),
    .link_ready_adc                     (link_ready_adc[5]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[5]                            ),
    .fifo_full_adc                      (fifo_full_adc[5]                             ),
    .afe_idle_adc                       (afe_idle_adc[5]                              ),
    .pll_lock_adc                       (pll_lock_adc[5]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[5]                         ),
    .lane_ready_adc                     (lane_ready_adc[11:10]                        ),
    .byte_aligned_adc                   (byte_aligned_adc[11:10]                      ),
    .comma_detected_adc                 (comma_detected_adc[11:10]                    ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[5]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[5]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[5]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[5]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[11:10]                     ),
    .notintable_evt_adc                 (notintable_evt_adc[11:10]                    )
);

ADC_CHN adc_chn6(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[6]                                  ),
    .jesd_rst_n                         (jesd_rst_n[6]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd6                                         ),
    .afe_en                             (afe_en_adc[6]                                ),
    .fifo_clr                           (fifo_clr_sys[6]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe6_rx_data                                 ),
    .phy_rx_charisk                     (afe6_rx_charisk                              ),
    .phy_rx_disperr                     (afe6_rx_disperr                              ),
    .phy_rx_notintable                  (afe6_rx_notintable                           ),
    .phy_rx_reset_done                  (afe6_rx_reset_done                           ),
    .phy_pll_lock                       (afe6_pll_lock                                ),
    .phy_byte_aligned                   (afe6_byte_aligned                            ),
    .phy_rx_encommalign                 (afe6_rx_encommalign                          ),
    .phy_sync_n                         (afe6_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe6_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe6_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe6_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe6_tlast                            ),
    .m_axis_tready                      (m_axis_afe6_tready                           ),
    .link_ready_adc                     (link_ready_adc[6]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[6]                            ),
    .fifo_full_adc                      (fifo_full_adc[6]                             ),
    .afe_idle_adc                       (afe_idle_adc[6]                              ),
    .pll_lock_adc                       (pll_lock_adc[6]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[6]                         ),
    .lane_ready_adc                     (lane_ready_adc[13:12]                        ),
    .byte_aligned_adc                   (byte_aligned_adc[13:12]                      ),
    .comma_detected_adc                 (comma_detected_adc[13:12]                    ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[6]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[6]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[6]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[6]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[13:12]                     ),
    .notintable_evt_adc                 (notintable_evt_adc[13:12]                    )
);

ADC_CHN adc_chn7(
    .adc_clk                            (adc_clk                                      ),
    .adc_rst_n                          (adc_rst_n                                    ),
    .afe_clk                            (afe_clk                                      ),
    .afe_rst_n                          (afe_rst_n                                    ),
    .jesd_clk                           (jesd_clk[7]                                  ),
    .jesd_rst_n                         (jesd_rst_n[7]                                ),
    .sysref                             (sysref_in                                    ),
    .afe_id                             (3'd7                                         ),
    .afe_en                             (afe_en_adc[7]                                ),
    .fifo_clr                           (fifo_clr_sys[7]                              ),
    .smp_prec                           (smp_prec                                     ),
    .smp_mode                           (smp_mode                                     ),
    .frame_fmt                          (frame_fmt                                    ),
    .dec_del_mode                       (dec_del_mode                                 ),
    .dec_m                              (dec_m                                        ),
    .phy_rx_data                        (afe7_rx_data                                 ),
    .phy_rx_charisk                     (afe7_rx_charisk                              ),
    .phy_rx_disperr                     (afe7_rx_disperr                              ),
    .phy_rx_notintable                  (afe7_rx_notintable                           ),
    .phy_rx_reset_done                  (afe7_rx_reset_done                           ),
    .phy_pll_lock                       (afe7_pll_lock                                ),
    .phy_byte_aligned                   (afe7_byte_aligned                            ),
    .phy_rx_encommalign                 (afe7_rx_encommalign                          ),
    .phy_sync_n                         (afe7_sync_n                                  ),
    .m_axis_tdata                       (m_axis_afe7_tdata                            ),
    .m_axis_tkeep                       (m_axis_afe7_tkeep                            ),
    .m_axis_tvalid                      (m_axis_afe7_tvalid                           ),
    .m_axis_tlast                       (m_axis_afe7_tlast                            ),
    .m_axis_tready                      (m_axis_afe7_tready                           ),
    .link_ready_adc                     (link_ready_adc[7]                            ),
    .fifo_empty_adc                     (fifo_empty_adc[7]                            ),
    .fifo_full_adc                      (fifo_full_adc[7]                             ),
    .afe_idle_adc                       (afe_idle_adc[7]                              ),
    .pll_lock_adc                       (pll_lock_adc[7]                              ),
    .rx_reset_done_adc                  (rx_reset_done_adc[7]                         ),
    .lane_ready_adc                     (lane_ready_adc[15:14]                        ),
    .byte_aligned_adc                   (byte_aligned_adc[15:14]                      ),
    .comma_detected_adc                 (comma_detected_adc[15:14]                    ),
    .fifo_overflow_evt_afe              (fifo_overflow_evt_afe[7]                     ),
    .data_drop_evt_adc                  (data_drop_evt_adc[7]                         ),
    .link_error_evt_adc                 (link_error_evt_adc[7]                        ),
    .sysref_seen_evt_adc                (sysref_seen_evt_adc[7]                       ),
    .disparity_evt_adc                  (disparity_evt_adc[15:14]                     ),
    .notintable_evt_adc                 (notintable_evt_adc[15:14]                    )
);

endmodule

