`timescale 1ns / 1ps

module ADC_TOP(
    input                                   sys_clk                                        ,
    input                                   sys_rst_n                                      ,
    input                                   adc_clk                                        ,
    input                                   adc_rst_n                                      ,
    input                                   afe_clk                                        ,
    input                                   afe_rst_n                                      ,
    input               [ 7:0]              jesd_clk                                       ,
    input               [ 7:0]              jesd_rst_n                                     ,
    input                                   sysref_in                                      ,
    input               [15:0]              s_axi_awaddr                                   ,
    input                                   s_axi_awvalid                                  ,
    output    wire                          s_axi_awready                                  ,
    input               [31:0]              s_axi_wdata                                    ,
    input               [ 3:0]              s_axi_wstrb                                    ,
    input                                   s_axi_wvalid                                   ,
    output    wire                          s_axi_wready                                   ,
    output    wire      [ 1:0]              s_axi_bresp                                    ,
    output    wire                          s_axi_bvalid                                   ,
    input                                   s_axi_bready                                   ,
    input               [15:0]              s_axi_araddr                                   ,
    input                                   s_axi_arvalid                                  ,
    output    wire                          s_axi_arready                                  ,
    output    wire      [31:0]              s_axi_rdata                                    ,
    output    wire      [ 1:0]              s_axi_rresp                                    ,
    output    wire                          s_axi_rvalid                                   ,
    input                                   s_axi_rready                                   ,
    input               [63:0]              afe0_rx_data                                   ,
    input               [ 7:0]              afe0_rx_charisk                                ,
    input               [ 7:0]              afe0_rx_disperr                                ,
    input               [ 7:0]              afe0_rx_notintable                             ,
    input                                   afe0_rx_reset_done                             ,
    input                                   afe0_pll_lock                                  ,
    input               [ 1:0]              afe0_byte_aligned                              ,
    output    wire                          afe0_rx_encommalign                            ,
    output    wire                          afe0_sync_n                                    ,
    input               [63:0]              afe1_rx_data                                   ,
    input               [ 7:0]              afe1_rx_charisk                                ,
    input               [ 7:0]              afe1_rx_disperr                                ,
    input               [ 7:0]              afe1_rx_notintable                             ,
    input                                   afe1_rx_reset_done                             ,
    input                                   afe1_pll_lock                                  ,
    input               [ 1:0]              afe1_byte_aligned                              ,
    output    wire                          afe1_rx_encommalign                            ,
    output    wire                          afe1_sync_n                                    ,
    input               [63:0]              afe2_rx_data                                   ,
    input               [ 7:0]              afe2_rx_charisk                                ,
    input               [ 7:0]              afe2_rx_disperr                                ,
    input               [ 7:0]              afe2_rx_notintable                             ,
    input                                   afe2_rx_reset_done                             ,
    input                                   afe2_pll_lock                                  ,
    input               [ 1:0]              afe2_byte_aligned                              ,
    output    wire                          afe2_rx_encommalign                            ,
    output    wire                          afe2_sync_n                                    ,
    input               [63:0]              afe3_rx_data                                   ,
    input               [ 7:0]              afe3_rx_charisk                                ,
    input               [ 7:0]              afe3_rx_disperr                                ,
    input               [ 7:0]              afe3_rx_notintable                             ,
    input                                   afe3_rx_reset_done                             ,
    input                                   afe3_pll_lock                                  ,
    input               [ 1:0]              afe3_byte_aligned                              ,
    output    wire                          afe3_rx_encommalign                            ,
    output    wire                          afe3_sync_n                                    ,
    input               [63:0]              afe4_rx_data                                   ,
    input               [ 7:0]              afe4_rx_charisk                                ,
    input               [ 7:0]              afe4_rx_disperr                                ,
    input               [ 7:0]              afe4_rx_notintable                             ,
    input                                   afe4_rx_reset_done                             ,
    input                                   afe4_pll_lock                                  ,
    input               [ 1:0]              afe4_byte_aligned                              ,
    output    wire                          afe4_rx_encommalign                            ,
    output    wire                          afe4_sync_n                                    ,
    input               [63:0]              afe5_rx_data                                   ,
    input               [ 7:0]              afe5_rx_charisk                                ,
    input               [ 7:0]              afe5_rx_disperr                                ,
    input               [ 7:0]              afe5_rx_notintable                             ,
    input                                   afe5_rx_reset_done                             ,
    input                                   afe5_pll_lock                                  ,
    input               [ 1:0]              afe5_byte_aligned                              ,
    output    wire                          afe5_rx_encommalign                            ,
    output    wire                          afe5_sync_n                                    ,
    input               [63:0]              afe6_rx_data                                   ,
    input               [ 7:0]              afe6_rx_charisk                                ,
    input               [ 7:0]              afe6_rx_disperr                                ,
    input               [ 7:0]              afe6_rx_notintable                             ,
    input                                   afe6_rx_reset_done                             ,
    input                                   afe6_pll_lock                                  ,
    input               [ 1:0]              afe6_byte_aligned                              ,
    output    wire                          afe6_rx_encommalign                            ,
    output    wire                          afe6_sync_n                                    ,
    input               [63:0]              afe7_rx_data                                   ,
    input               [ 7:0]              afe7_rx_charisk                                ,
    input               [ 7:0]              afe7_rx_disperr                                ,
    input               [ 7:0]              afe7_rx_notintable                             ,
    input                                   afe7_rx_reset_done                             ,
    input                                   afe7_pll_lock                                  ,
    input               [ 1:0]              afe7_byte_aligned                              ,
    output    wire                          afe7_rx_encommalign                            ,
    output    wire                          afe7_sync_n                                    ,
    output    wire      [511:0]             m_axis_afe0_tdata                              ,
    output    wire      [63:0]              m_axis_afe0_tkeep                              ,
    output    wire                          m_axis_afe0_tvalid                             ,
    output    wire                          m_axis_afe0_tlast                              ,
    input                                   m_axis_afe0_tready                             ,
    output    wire                          tgc0_slope                                     ,
    output    wire                          tgc0_up_dn                                     ,
    output    wire                          tgc0_prof1                                     ,
    output    wire                          tgc0_prof2                                     ,
    output    wire      [511:0]             m_axis_afe1_tdata                              ,
    output    wire      [63:0]              m_axis_afe1_tkeep                              ,
    output    wire                          m_axis_afe1_tvalid                             ,
    output    wire                          m_axis_afe1_tlast                              ,
    input                                   m_axis_afe1_tready                             ,
    output    wire                          tgc1_slope                                     ,
    output    wire                          tgc1_up_dn                                     ,
    output    wire                          tgc1_prof1                                     ,
    output    wire                          tgc1_prof2                                     ,
    output    wire      [511:0]             m_axis_afe2_tdata                              ,
    output    wire      [63:0]              m_axis_afe2_tkeep                              ,
    output    wire                          m_axis_afe2_tvalid                             ,
    output    wire                          m_axis_afe2_tlast                              ,
    input                                   m_axis_afe2_tready                             ,
    output    wire                          tgc2_slope                                     ,
    output    wire                          tgc2_up_dn                                     ,
    output    wire                          tgc2_prof1                                     ,
    output    wire                          tgc2_prof2                                     ,
    output    wire      [511:0]             m_axis_afe3_tdata                              ,
    output    wire      [63:0]              m_axis_afe3_tkeep                              ,
    output    wire                          m_axis_afe3_tvalid                             ,
    output    wire                          m_axis_afe3_tlast                              ,
    input                                   m_axis_afe3_tready                             ,
    output    wire                          tgc3_slope                                     ,
    output    wire                          tgc3_up_dn                                     ,
    output    wire                          tgc3_prof1                                     ,
    output    wire                          tgc3_prof2                                     ,
    output    wire      [511:0]             m_axis_afe4_tdata                              ,
    output    wire      [63:0]              m_axis_afe4_tkeep                              ,
    output    wire                          m_axis_afe4_tvalid                             ,
    output    wire                          m_axis_afe4_tlast                              ,
    input                                   m_axis_afe4_tready                             ,
    output    wire                          tgc4_slope                                     ,
    output    wire                          tgc4_up_dn                                     ,
    output    wire                          tgc4_prof1                                     ,
    output    wire                          tgc4_prof2                                     ,
    output    wire      [511:0]             m_axis_afe5_tdata                              ,
    output    wire      [63:0]              m_axis_afe5_tkeep                              ,
    output    wire                          m_axis_afe5_tvalid                             ,
    output    wire                          m_axis_afe5_tlast                              ,
    input                                   m_axis_afe5_tready                             ,
    output    wire                          tgc5_slope                                     ,
    output    wire                          tgc5_up_dn                                     ,
    output    wire                          tgc5_prof1                                     ,
    output    wire                          tgc5_prof2                                     ,
    output    wire      [511:0]             m_axis_afe6_tdata                              ,
    output    wire      [63:0]              m_axis_afe6_tkeep                              ,
    output    wire                          m_axis_afe6_tvalid                             ,
    output    wire                          m_axis_afe6_tlast                              ,
    input                                   m_axis_afe6_tready                             ,
    output    wire                          tgc6_slope                                     ,
    output    wire                          tgc6_up_dn                                     ,
    output    wire                          tgc6_prof1                                     ,
    output    wire                          tgc6_prof2                                     ,
    output    wire      [511:0]             m_axis_afe7_tdata                              ,
    output    wire      [63:0]              m_axis_afe7_tkeep                              ,
    output    wire                          m_axis_afe7_tvalid                             ,
    output    wire                          m_axis_afe7_tlast                              ,
    input                                   m_axis_afe7_tready                             ,
    output    wire                          tgc7_slope                                     ,
    output    wire                          tgc7_up_dn                                     ,
    output    wire                          tgc7_prof1                                     ,
    output    wire                          tgc7_prof2
);

parameter                                   UDLY                     = 1                   ;

wire                    [31:0]              adc_ctl                                        ;
wire                    [31:0]              frm_cfg                                        ;
wire                    [ 3:0]              chn0_tgc                                       ;
wire                    [ 3:0]              chn1_tgc                                       ;
wire                    [ 3:0]              chn2_tgc                                       ;
wire                    [ 3:0]              chn3_tgc                                       ;
wire                    [ 3:0]              chn4_tgc                                       ;
wire                    [ 3:0]              chn5_tgc                                       ;
wire                    [ 3:0]              chn6_tgc                                       ;
wire                    [ 3:0]              chn7_tgc                                       ;
wire                    [ 7:0]              tgc_done                                       ;
wire                    [ 7:0]              link_ready                                     ;
wire                    [ 7:0]              fifo_empty                                     ;
wire                    [ 7:0]              chn_idle                                       ;
wire                    [ 7:0]              pll_lock                                       ;
wire                    [ 7:0]              rx_reset_done                                  ;
wire                    [15:0]              lane_ready                                     ;
wire                    [15:0]              byte_aligned                                   ;
wire                    [15:0]              comma_detected                                 ;
wire                    [ 7:0]              link_error                                     ;
wire                    [ 7:0]              sysref_seen                                    ;
wire                    [15:0]              disparity                                      ;
wire                    [15:0]              notintable                                     ;
wire                    [ 7:0]              fifo_overflow                                  ;
wire                    [ 7:0]              fifo_full                                      ;
wire                    [ 7:0]              data_error                                     ;
wire                    [ 7:0]              link_ready_sync                                ;
wire                    [ 7:0]              fifo_empty_sync                                ;
wire                    [ 7:0]              fifo_full_sync                                 ;
wire                    [ 7:0]              chn_idle_sync                                  ;
wire                    [ 7:0]              pll_lock_sync                                  ;
wire                    [ 7:0]              rx_reset_done_sync                             ;
wire                    [15:0]              lane_ready_sync                                ;
wire                    [15:0]              byte_aligned_sync                              ;
wire                    [15:0]              comma_detected_sync                            ;
wire                                        sysref_sync                                    ;
wire                    [ 7:0]              fifo_overflow_sync                             ;
wire                    [ 7:0]              data_error_sync                                ;
wire                    [ 7:0]              link_error_sync                                ;
wire                    [ 7:0]              sysref_seen_sync                               ;
wire                    [15:0]              disparity_sync                                 ;
wire                    [15:0]              notintable_sync                                ;

//////////////////////////////////////////////////
//1. Register And CDC Concentration
//////////////////////////////////////////////////
ADC_REG adc_reg(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .s_axi_awaddr                        (s_axi_awaddr                                 ),
    .s_axi_awvalid                       (s_axi_awvalid                                ),
    .s_axi_awready                       (s_axi_awready                                ),
    .s_axi_wdata                         (s_axi_wdata                                  ),
    .s_axi_wstrb                         (s_axi_wstrb                                  ),
    .s_axi_wvalid                        (s_axi_wvalid                                 ),
    .s_axi_wready                        (s_axi_wready                                 ),
    .s_axi_bresp                         (s_axi_bresp                                  ),
    .s_axi_bvalid                        (s_axi_bvalid                                 ),
    .s_axi_bready                        (s_axi_bready                                 ),
    .s_axi_araddr                        (s_axi_araddr                                 ),
    .s_axi_arvalid                       (s_axi_arvalid                                ),
    .s_axi_arready                       (s_axi_arready                                ),
    .s_axi_rdata                         (s_axi_rdata                                  ),
    .s_axi_rresp                         (s_axi_rresp                                  ),
    .s_axi_rvalid                        (s_axi_rvalid                                 ),
    .s_axi_rready                        (s_axi_rready                                 ),
    .link_ready                          (link_ready_sync                              ),
    .fifo_empty                          (fifo_empty_sync                              ),
    .fifo_full                           (fifo_full_sync                               ),
    .chn_idle                            (chn_idle_sync                                ),
    .pll_lock                            (pll_lock_sync                                ),
    .rx_reset_done                       (rx_reset_done_sync                           ),
    .lane_ready                          (lane_ready_sync                              ),
    .byte_aligned                        (byte_aligned_sync                            ),
    .comma_detected                      (comma_detected_sync                          ),
    .sysref_level                        (sysref_sync                                  ),
    .fifo_overflow_sync                  (fifo_overflow_sync                           ),
    .data_error_sync                     (data_error_sync                              ),
    .link_error_sync                     (link_error_sync                              ),
    .sysref_seen_sync                    (sysref_seen_sync                             ),
    .disparity_sync                      (disparity_sync                               ),
    .notintable_sync                     (notintable_sync                              ),
    .tgc_done                            (tgc_done                                     ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .chn0_tgc                            (chn0_tgc                                     ),
    .chn1_tgc                            (chn1_tgc                                     ),
    .chn2_tgc                            (chn2_tgc                                     ),
    .chn3_tgc                            (chn3_tgc                                     ),
    .chn4_tgc                            (chn4_tgc                                     ),
    .chn5_tgc                            (chn5_tgc                                     ),
    .chn6_tgc                            (chn6_tgc                                     ),
    .chn7_tgc                            (chn7_tgc                                     )
);

ADC_SYNC adc_sync(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .sysref                              (sysref_in                                    ),
    .sysref_sync                         (sysref_sync                                  ),
    .link_ready                          (link_ready                                   ),
    .link_ready_sync                     (link_ready_sync                              ),
    .fifo_empty                          (fifo_empty                                   ),
    .fifo_empty_sync                     (fifo_empty_sync                              ),
    .fifo_full                           (fifo_full                                    ),
    .fifo_full_sync                      (fifo_full_sync                               ),
    .chn_idle                            (chn_idle                                     ),
    .chn_idle_sync                       (chn_idle_sync                                ),
    .pll_lock                            (pll_lock                                     ),
    .pll_lock_sync                       (pll_lock_sync                                ),
    .rx_reset_done                       (rx_reset_done                                ),
    .rx_reset_done_sync                  (rx_reset_done_sync                           ),
    .lane_ready                          (lane_ready                                   ),
    .lane_ready_sync                     (lane_ready_sync                              ),
    .byte_aligned                        (byte_aligned                                 ),
    .byte_aligned_sync                   (byte_aligned_sync                            ),
    .comma_detected                      (comma_detected                               ),
    .comma_detected_sync                 (comma_detected_sync                          ),
    .fifo_overflow                       (fifo_overflow                                ),
    .fifo_overflow_sync                  (fifo_overflow_sync                           ),
    .data_error                          (data_error                                   ),
    .data_error_sync                     (data_error_sync                              ),
    .link_error                          (link_error                                   ),
    .link_error_sync                     (link_error_sync                              ),
    .sysref_seen                         (sysref_seen                                  ),
    .sysref_seen_sync                    (sysref_seen_sync                             ),
    .disparity                           (disparity                                    ),
    .disparity_sync                      (disparity_sync                               ),
    .notintable                          (notintable                                   ),
    .notintable_sync                     (notintable_sync                              )
);

//////////////////////////////////////////////////
//2. Acquisition Channels
//////////////////////////////////////////////////
ADC_CHN adc_chn0(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[0]                                  ),
    .jesd_rst_n                          (jesd_rst_n[0]                                ),
    .chn_en                              (adc_ctl[0]                                   ),
    .fifo_clr                            (adc_ctl[8]                                   ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe0_rx_data                                 ),
    .phy_rx_charisk                      (afe0_rx_charisk                              ),
    .phy_rx_disperr                      (afe0_rx_disperr                              ),
    .phy_rx_notintable                   (afe0_rx_notintable                           ),
    .phy_rx_reset_done                   (afe0_rx_reset_done                           ),
    .phy_pll_lock                        (afe0_pll_lock                                ),
    .phy_byte_aligned                    (afe0_byte_aligned                            ),
    .phy_rx_encommalign                  (afe0_rx_encommalign                          ),
    .phy_sync_n                          (afe0_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe0_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe0_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe0_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe0_tlast                            ),
    .m_axis_tready                       (m_axis_afe0_tready                           ),
    .link_ready_sync                     (link_ready[0]                                ),
    .rx_fifo_empt                        (fifo_empty[0]                                ),
    .chn_idle                            (chn_idle[0]                                  ),
    .phy_pll_lock_sync                   (pll_lock[0]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[0]                             ),
    .lane_ready_sync                     (lane_ready[0 +: 2]                           ),
    .phy_byte_aligned_sync               (byte_aligned[0 +: 2]                         ),
    .cgs_ready_sync                      (comma_detected[0 +: 2]                       ),
    .fifo_overflow                       (fifo_overflow[0]                             ),
    .link_error_sync                     (link_error[0]                                ),
    .sysref_seen_sync                    (sysref_seen[0]                               ),
    .phy_disparity_sync                  (disparity[0 +: 2]                            ),
    .phy_notintable_sync                 (notintable[0 +: 2]                           ),
    .chn_tgc                             (chn0_tgc                                     ),
    .tgc_done                            (tgc_done[0]                                  ),
    .tgc_slope                           (tgc0_slope                                   ),
    .tgc_up_dn                           (tgc0_up_dn                                   ),
    .tgc_prof1                           (tgc0_prof1                                   ),
    .tgc_prof2                           (tgc0_prof2                                   ),
    .fifo_full                           (fifo_full[0]                                 ),
    .data_error                          (data_error[0]                                )
);

ADC_CHN adc_chn1(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[1]                                  ),
    .jesd_rst_n                          (jesd_rst_n[1]                                ),
    .chn_en                              (adc_ctl[1]                                   ),
    .fifo_clr                            (adc_ctl[9]                                   ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe1_rx_data                                 ),
    .phy_rx_charisk                      (afe1_rx_charisk                              ),
    .phy_rx_disperr                      (afe1_rx_disperr                              ),
    .phy_rx_notintable                   (afe1_rx_notintable                           ),
    .phy_rx_reset_done                   (afe1_rx_reset_done                           ),
    .phy_pll_lock                        (afe1_pll_lock                                ),
    .phy_byte_aligned                    (afe1_byte_aligned                            ),
    .phy_rx_encommalign                  (afe1_rx_encommalign                          ),
    .phy_sync_n                          (afe1_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe1_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe1_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe1_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe1_tlast                            ),
    .m_axis_tready                       (m_axis_afe1_tready                           ),
    .link_ready_sync                     (link_ready[1]                                ),
    .rx_fifo_empt                        (fifo_empty[1]                                ),
    .chn_idle                            (chn_idle[1]                                  ),
    .phy_pll_lock_sync                   (pll_lock[1]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[1]                             ),
    .lane_ready_sync                     (lane_ready[2 +: 2]                           ),
    .phy_byte_aligned_sync               (byte_aligned[2 +: 2]                         ),
    .cgs_ready_sync                      (comma_detected[2 +: 2]                       ),
    .fifo_overflow                       (fifo_overflow[1]                             ),
    .link_error_sync                     (link_error[1]                                ),
    .sysref_seen_sync                    (sysref_seen[1]                               ),
    .phy_disparity_sync                  (disparity[2 +: 2]                            ),
    .phy_notintable_sync                 (notintable[2 +: 2]                           ),
    .chn_tgc                             (chn1_tgc                                     ),
    .tgc_done                            (tgc_done[1]                                  ),
    .tgc_slope                           (tgc1_slope                                   ),
    .tgc_up_dn                           (tgc1_up_dn                                   ),
    .tgc_prof1                           (tgc1_prof1                                   ),
    .tgc_prof2                           (tgc1_prof2                                   ),
    .fifo_full                           (fifo_full[1]                                 ),
    .data_error                          (data_error[1]                                )
);

ADC_CHN adc_chn2(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[2]                                  ),
    .jesd_rst_n                          (jesd_rst_n[2]                                ),
    .chn_en                              (adc_ctl[2]                                   ),
    .fifo_clr                            (adc_ctl[10]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe2_rx_data                                 ),
    .phy_rx_charisk                      (afe2_rx_charisk                              ),
    .phy_rx_disperr                      (afe2_rx_disperr                              ),
    .phy_rx_notintable                   (afe2_rx_notintable                           ),
    .phy_rx_reset_done                   (afe2_rx_reset_done                           ),
    .phy_pll_lock                        (afe2_pll_lock                                ),
    .phy_byte_aligned                    (afe2_byte_aligned                            ),
    .phy_rx_encommalign                  (afe2_rx_encommalign                          ),
    .phy_sync_n                          (afe2_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe2_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe2_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe2_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe2_tlast                            ),
    .m_axis_tready                       (m_axis_afe2_tready                           ),
    .link_ready_sync                     (link_ready[2]                                ),
    .rx_fifo_empt                        (fifo_empty[2]                                ),
    .chn_idle                            (chn_idle[2]                                  ),
    .phy_pll_lock_sync                   (pll_lock[2]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[2]                             ),
    .lane_ready_sync                     (lane_ready[4 +: 2]                           ),
    .phy_byte_aligned_sync               (byte_aligned[4 +: 2]                         ),
    .cgs_ready_sync                      (comma_detected[4 +: 2]                       ),
    .fifo_overflow                       (fifo_overflow[2]                             ),
    .link_error_sync                     (link_error[2]                                ),
    .sysref_seen_sync                    (sysref_seen[2]                               ),
    .phy_disparity_sync                  (disparity[4 +: 2]                            ),
    .phy_notintable_sync                 (notintable[4 +: 2]                           ),
    .chn_tgc                             (chn2_tgc                                     ),
    .tgc_done                            (tgc_done[2]                                  ),
    .tgc_slope                           (tgc2_slope                                   ),
    .tgc_up_dn                           (tgc2_up_dn                                   ),
    .tgc_prof1                           (tgc2_prof1                                   ),
    .tgc_prof2                           (tgc2_prof2                                   ),
    .fifo_full                           (fifo_full[2]                                 ),
    .data_error                          (data_error[2]                                )
);

ADC_CHN adc_chn3(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[3]                                  ),
    .jesd_rst_n                          (jesd_rst_n[3]                                ),
    .chn_en                              (adc_ctl[3]                                   ),
    .fifo_clr                            (adc_ctl[11]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe3_rx_data                                 ),
    .phy_rx_charisk                      (afe3_rx_charisk                              ),
    .phy_rx_disperr                      (afe3_rx_disperr                              ),
    .phy_rx_notintable                   (afe3_rx_notintable                           ),
    .phy_rx_reset_done                   (afe3_rx_reset_done                           ),
    .phy_pll_lock                        (afe3_pll_lock                                ),
    .phy_byte_aligned                    (afe3_byte_aligned                            ),
    .phy_rx_encommalign                  (afe3_rx_encommalign                          ),
    .phy_sync_n                          (afe3_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe3_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe3_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe3_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe3_tlast                            ),
    .m_axis_tready                       (m_axis_afe3_tready                           ),
    .link_ready_sync                     (link_ready[3]                                ),
    .rx_fifo_empt                        (fifo_empty[3]                                ),
    .chn_idle                            (chn_idle[3]                                  ),
    .phy_pll_lock_sync                   (pll_lock[3]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[3]                             ),
    .lane_ready_sync                     (lane_ready[6 +: 2]                           ),
    .phy_byte_aligned_sync               (byte_aligned[6 +: 2]                         ),
    .cgs_ready_sync                      (comma_detected[6 +: 2]                       ),
    .fifo_overflow                       (fifo_overflow[3]                             ),
    .link_error_sync                     (link_error[3]                                ),
    .sysref_seen_sync                    (sysref_seen[3]                               ),
    .phy_disparity_sync                  (disparity[6 +: 2]                            ),
    .phy_notintable_sync                 (notintable[6 +: 2]                           ),
    .chn_tgc                             (chn3_tgc                                     ),
    .tgc_done                            (tgc_done[3]                                  ),
    .tgc_slope                           (tgc3_slope                                   ),
    .tgc_up_dn                           (tgc3_up_dn                                   ),
    .tgc_prof1                           (tgc3_prof1                                   ),
    .tgc_prof2                           (tgc3_prof2                                   ),
    .fifo_full                           (fifo_full[3]                                 ),
    .data_error                          (data_error[3]                                )
);

ADC_CHN adc_chn4(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[4]                                  ),
    .jesd_rst_n                          (jesd_rst_n[4]                                ),
    .chn_en                              (adc_ctl[4]                                   ),
    .fifo_clr                            (adc_ctl[12]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe4_rx_data                                 ),
    .phy_rx_charisk                      (afe4_rx_charisk                              ),
    .phy_rx_disperr                      (afe4_rx_disperr                              ),
    .phy_rx_notintable                   (afe4_rx_notintable                           ),
    .phy_rx_reset_done                   (afe4_rx_reset_done                           ),
    .phy_pll_lock                        (afe4_pll_lock                                ),
    .phy_byte_aligned                    (afe4_byte_aligned                            ),
    .phy_rx_encommalign                  (afe4_rx_encommalign                          ),
    .phy_sync_n                          (afe4_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe4_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe4_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe4_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe4_tlast                            ),
    .m_axis_tready                       (m_axis_afe4_tready                           ),
    .link_ready_sync                     (link_ready[4]                                ),
    .rx_fifo_empt                        (fifo_empty[4]                                ),
    .chn_idle                            (chn_idle[4]                                  ),
    .phy_pll_lock_sync                   (pll_lock[4]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[4]                             ),
    .lane_ready_sync                     (lane_ready[8 +: 2]                           ),
    .phy_byte_aligned_sync               (byte_aligned[8 +: 2]                         ),
    .cgs_ready_sync                      (comma_detected[8 +: 2]                       ),
    .fifo_overflow                       (fifo_overflow[4]                             ),
    .link_error_sync                     (link_error[4]                                ),
    .sysref_seen_sync                    (sysref_seen[4]                               ),
    .phy_disparity_sync                  (disparity[8 +: 2]                            ),
    .phy_notintable_sync                 (notintable[8 +: 2]                           ),
    .chn_tgc                             (chn4_tgc                                     ),
    .tgc_done                            (tgc_done[4]                                  ),
    .tgc_slope                           (tgc4_slope                                   ),
    .tgc_up_dn                           (tgc4_up_dn                                   ),
    .tgc_prof1                           (tgc4_prof1                                   ),
    .tgc_prof2                           (tgc4_prof2                                   ),
    .fifo_full                           (fifo_full[4]                                 ),
    .data_error                          (data_error[4]                                )
);

ADC_CHN adc_chn5(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[5]                                  ),
    .jesd_rst_n                          (jesd_rst_n[5]                                ),
    .chn_en                              (adc_ctl[5]                                   ),
    .fifo_clr                            (adc_ctl[13]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe5_rx_data                                 ),
    .phy_rx_charisk                      (afe5_rx_charisk                              ),
    .phy_rx_disperr                      (afe5_rx_disperr                              ),
    .phy_rx_notintable                   (afe5_rx_notintable                           ),
    .phy_rx_reset_done                   (afe5_rx_reset_done                           ),
    .phy_pll_lock                        (afe5_pll_lock                                ),
    .phy_byte_aligned                    (afe5_byte_aligned                            ),
    .phy_rx_encommalign                  (afe5_rx_encommalign                          ),
    .phy_sync_n                          (afe5_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe5_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe5_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe5_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe5_tlast                            ),
    .m_axis_tready                       (m_axis_afe5_tready                           ),
    .link_ready_sync                     (link_ready[5]                                ),
    .rx_fifo_empt                        (fifo_empty[5]                                ),
    .chn_idle                            (chn_idle[5]                                  ),
    .phy_pll_lock_sync                   (pll_lock[5]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[5]                             ),
    .lane_ready_sync                     (lane_ready[10 +: 2]                          ),
    .phy_byte_aligned_sync               (byte_aligned[10 +: 2]                        ),
    .cgs_ready_sync                      (comma_detected[10 +: 2]                      ),
    .fifo_overflow                       (fifo_overflow[5]                             ),
    .link_error_sync                     (link_error[5]                                ),
    .sysref_seen_sync                    (sysref_seen[5]                               ),
    .phy_disparity_sync                  (disparity[10 +: 2]                           ),
    .phy_notintable_sync                 (notintable[10 +: 2]                          ),
    .chn_tgc                             (chn5_tgc                                     ),
    .tgc_done                            (tgc_done[5]                                  ),
    .tgc_slope                           (tgc5_slope                                   ),
    .tgc_up_dn                           (tgc5_up_dn                                   ),
    .tgc_prof1                           (tgc5_prof1                                   ),
    .tgc_prof2                           (tgc5_prof2                                   ),
    .fifo_full                           (fifo_full[5]                                 ),
    .data_error                          (data_error[5]                                )
);

ADC_CHN adc_chn6(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[6]                                  ),
    .jesd_rst_n                          (jesd_rst_n[6]                                ),
    .chn_en                              (adc_ctl[6]                                   ),
    .fifo_clr                            (adc_ctl[14]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe6_rx_data                                 ),
    .phy_rx_charisk                      (afe6_rx_charisk                              ),
    .phy_rx_disperr                      (afe6_rx_disperr                              ),
    .phy_rx_notintable                   (afe6_rx_notintable                           ),
    .phy_rx_reset_done                   (afe6_rx_reset_done                           ),
    .phy_pll_lock                        (afe6_pll_lock                                ),
    .phy_byte_aligned                    (afe6_byte_aligned                            ),
    .phy_rx_encommalign                  (afe6_rx_encommalign                          ),
    .phy_sync_n                          (afe6_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe6_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe6_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe6_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe6_tlast                            ),
    .m_axis_tready                       (m_axis_afe6_tready                           ),
    .link_ready_sync                     (link_ready[6]                                ),
    .rx_fifo_empt                        (fifo_empty[6]                                ),
    .chn_idle                            (chn_idle[6]                                  ),
    .phy_pll_lock_sync                   (pll_lock[6]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[6]                             ),
    .lane_ready_sync                     (lane_ready[12 +: 2]                          ),
    .phy_byte_aligned_sync               (byte_aligned[12 +: 2]                        ),
    .cgs_ready_sync                      (comma_detected[12 +: 2]                      ),
    .fifo_overflow                       (fifo_overflow[6]                             ),
    .link_error_sync                     (link_error[6]                                ),
    .sysref_seen_sync                    (sysref_seen[6]                               ),
    .phy_disparity_sync                  (disparity[12 +: 2]                           ),
    .phy_notintable_sync                 (notintable[12 +: 2]                          ),
    .chn_tgc                             (chn6_tgc                                     ),
    .tgc_done                            (tgc_done[6]                                  ),
    .tgc_slope                           (tgc6_slope                                   ),
    .tgc_up_dn                           (tgc6_up_dn                                   ),
    .tgc_prof1                           (tgc6_prof1                                   ),
    .tgc_prof2                           (tgc6_prof2                                   ),
    .fifo_full                           (fifo_full[6]                                 ),
    .data_error                          (data_error[6]                                )
);

ADC_CHN adc_chn7(
    .sys_clk                             (sys_clk                                      ),
    .sys_rst_n                           (sys_rst_n                                    ),
    .adc_clk                             (adc_clk                                      ),
    .adc_rst_n                           (adc_rst_n                                    ),
    .afe_clk                             (afe_clk                                      ),
    .afe_rst_n                           (afe_rst_n                                    ),
    .jesd_clk                            (jesd_clk[7]                                  ),
    .jesd_rst_n                          (jesd_rst_n[7]                                ),
    .chn_en                              (adc_ctl[7]                                   ),
    .fifo_clr                            (adc_ctl[15]                                  ),
    .sysref                              (sysref_in                                    ),
    .adc_ctl                             (adc_ctl                                      ),
    .frm_cfg                             (frm_cfg                                      ),
    .phy_rx_data                         (afe7_rx_data                                 ),
    .phy_rx_charisk                      (afe7_rx_charisk                              ),
    .phy_rx_disperr                      (afe7_rx_disperr                              ),
    .phy_rx_notintable                   (afe7_rx_notintable                           ),
    .phy_rx_reset_done                   (afe7_rx_reset_done                           ),
    .phy_pll_lock                        (afe7_pll_lock                                ),
    .phy_byte_aligned                    (afe7_byte_aligned                            ),
    .phy_rx_encommalign                  (afe7_rx_encommalign                          ),
    .phy_sync_n                          (afe7_sync_n                                  ),
    .m_axis_tdata                        (m_axis_afe7_tdata                            ),
    .m_axis_tkeep                        (m_axis_afe7_tkeep                            ),
    .m_axis_tvalid                       (m_axis_afe7_tvalid                           ),
    .m_axis_tlast                        (m_axis_afe7_tlast                            ),
    .m_axis_tready                       (m_axis_afe7_tready                           ),
    .link_ready_sync                     (link_ready[7]                                ),
    .rx_fifo_empt                        (fifo_empty[7]                                ),
    .chn_idle                            (chn_idle[7]                                  ),
    .phy_pll_lock_sync                   (pll_lock[7]                                  ),
    .phy_rx_reset_done_sync              (rx_reset_done[7]                             ),
    .lane_ready_sync                     (lane_ready[14 +: 2]                          ),
    .phy_byte_aligned_sync               (byte_aligned[14 +: 2]                        ),
    .cgs_ready_sync                      (comma_detected[14 +: 2]                      ),
    .fifo_overflow                       (fifo_overflow[7]                             ),
    .link_error_sync                     (link_error[7]                                ),
    .sysref_seen_sync                    (sysref_seen[7]                               ),
    .phy_disparity_sync                  (disparity[14 +: 2]                           ),
    .phy_notintable_sync                 (notintable[14 +: 2]                          ),
    .chn_tgc                             (chn7_tgc                                     ),
    .tgc_done                            (tgc_done[7]                                  ),
    .tgc_slope                           (tgc7_slope                                   ),
    .tgc_up_dn                           (tgc7_up_dn                                   ),
    .tgc_prof1                           (tgc7_prof1                                   ),
    .tgc_prof2                           (tgc7_prof2                                   ),
    .fifo_full                           (fifo_full[7]                                 ),
    .data_error                          (data_error[7]                                )
);

endmodule
