`timescale 1ns / 1ps

module ADC_TOP(
    input                                   sys_clk                                        ,
    input                                   sys_rst_n                                      ,
    input                                   adc_clk                                        ,
    input                                   adc_rst_n                                      ,
    input                                   afe_clk                                        ,
    input                                   afe_rst_n                                      ,
    input               [7:0]               jesd_clk                                       ,
    input               [7:0]               jesd_rst_n                                     ,
    input                                   sysref_in                                      ,
    input               [15:0]              s_axi_awaddr                                   ,
    input                                   s_axi_awvalid                                  ,
    output    wire                          s_axi_awready                                  ,
    input               [31:0]              s_axi_wdata                                    ,
    input               [3:0]               s_axi_wstrb                                    ,
    input                                   s_axi_wvalid                                   ,
    output    wire                          s_axi_wready                                   ,
    output    wire      [1:0]               s_axi_bresp                                    ,
    output    wire                          s_axi_bvalid                                   ,
    input                                   s_axi_bready                                   ,
    input               [15:0]              s_axi_araddr                                   ,
    input                                   s_axi_arvalid                                  ,
    output    wire                          s_axi_arready                                  ,
    output    wire      [31:0]              s_axi_rdata                                    ,
    output    wire      [1:0]               s_axi_rresp                                    ,
    output    wire                          s_axi_rvalid                                   ,
    input                                   s_axi_rready                                   ,
    input               [63:0]              afe0_rx_data                                   ,
    input               [7:0]               afe0_rx_charisk                                ,
    input               [7:0]               afe0_rx_disperr                                ,
    input               [7:0]               afe0_rx_notintable                             ,
    input                                   afe0_rx_reset_done                             ,
    input                                   afe0_pll_lock                                  ,
    input               [1:0]               afe0_byte_aligned                              ,
    output    wire                          afe0_rx_encommalign                            ,
    output    wire                          afe0_sync_n                                    ,
    input               [63:0]              afe1_rx_data                                   ,
    input               [7:0]               afe1_rx_charisk                                ,
    input               [7:0]               afe1_rx_disperr                                ,
    input               [7:0]               afe1_rx_notintable                             ,
    input                                   afe1_rx_reset_done                             ,
    input                                   afe1_pll_lock                                  ,
    input               [1:0]               afe1_byte_aligned                              ,
    output    wire                          afe1_rx_encommalign                            ,
    output    wire                          afe1_sync_n                                    ,
    input               [63:0]              afe2_rx_data                                   ,
    input               [7:0]               afe2_rx_charisk                                ,
    input               [7:0]               afe2_rx_disperr                                ,
    input               [7:0]               afe2_rx_notintable                             ,
    input                                   afe2_rx_reset_done                             ,
    input                                   afe2_pll_lock                                  ,
    input               [1:0]               afe2_byte_aligned                              ,
    output    wire                          afe2_rx_encommalign                            ,
    output    wire                          afe2_sync_n                                    ,
    input               [63:0]              afe3_rx_data                                   ,
    input               [7:0]               afe3_rx_charisk                                ,
    input               [7:0]               afe3_rx_disperr                                ,
    input               [7:0]               afe3_rx_notintable                             ,
    input                                   afe3_rx_reset_done                             ,
    input                                   afe3_pll_lock                                  ,
    input               [1:0]               afe3_byte_aligned                              ,
    output    wire                          afe3_rx_encommalign                            ,
    output    wire                          afe3_sync_n                                    ,
    input               [63:0]              afe4_rx_data                                   ,
    input               [7:0]               afe4_rx_charisk                                ,
    input               [7:0]               afe4_rx_disperr                                ,
    input               [7:0]               afe4_rx_notintable                             ,
    input                                   afe4_rx_reset_done                             ,
    input                                   afe4_pll_lock                                  ,
    input               [1:0]               afe4_byte_aligned                              ,
    output    wire                          afe4_rx_encommalign                            ,
    output    wire                          afe4_sync_n                                    ,
    input               [63:0]              afe5_rx_data                                   ,
    input               [7:0]               afe5_rx_charisk                                ,
    input               [7:0]               afe5_rx_disperr                                ,
    input               [7:0]               afe5_rx_notintable                             ,
    input                                   afe5_rx_reset_done                             ,
    input                                   afe5_pll_lock                                  ,
    input               [1:0]               afe5_byte_aligned                              ,
    output    wire                          afe5_rx_encommalign                            ,
    output    wire                          afe5_sync_n                                    ,
    input               [63:0]              afe6_rx_data                                   ,
    input               [7:0]               afe6_rx_charisk                                ,
    input               [7:0]               afe6_rx_disperr                                ,
    input               [7:0]               afe6_rx_notintable                             ,
    input                                   afe6_rx_reset_done                             ,
    input                                   afe6_pll_lock                                  ,
    input               [1:0]               afe6_byte_aligned                              ,
    output    wire                          afe6_rx_encommalign                            ,
    output    wire                          afe6_sync_n                                    ,
    input               [63:0]              afe7_rx_data                                   ,
    input               [7:0]               afe7_rx_charisk                                ,
    input               [7:0]               afe7_rx_disperr                                ,
    input               [7:0]               afe7_rx_notintable                             ,
    input                                   afe7_rx_reset_done                             ,
    input                                   afe7_pll_lock                                  ,
    input               [1:0]               afe7_byte_aligned                              ,
    output    wire                          afe7_rx_encommalign                            ,
    output    wire                          afe7_sync_n                                    ,
    output    wire      [511:0]             m_axis_afe0_tdata                              ,
    output    wire      [63:0]              m_axis_afe0_tkeep                              ,
    output    wire                          m_axis_afe0_tvalid                             ,
    output    wire                          m_axis_afe0_tlast                              ,
    input                                   m_axis_afe0_tready                             ,
    output    wire                          tgc0_slope                                     ,
    output    wire                          tgc0_up_dn                                     ,
    output    wire                          tgc0_prof1                                     ,
    output    wire                          tgc0_prof2                                     ,
    output    wire      [511:0]             m_axis_afe1_tdata                              ,
    output    wire      [63:0]              m_axis_afe1_tkeep                              ,
    output    wire                          m_axis_afe1_tvalid                             ,
    output    wire                          m_axis_afe1_tlast                              ,
    input                                   m_axis_afe1_tready                             ,
    output    wire                          tgc1_slope                                     ,
    output    wire                          tgc1_up_dn                                     ,
    output    wire                          tgc1_prof1                                     ,
    output    wire                          tgc1_prof2                                     ,
    output    wire      [511:0]             m_axis_afe2_tdata                              ,
    output    wire      [63:0]              m_axis_afe2_tkeep                              ,
    output    wire                          m_axis_afe2_tvalid                             ,
    output    wire                          m_axis_afe2_tlast                              ,
    input                                   m_axis_afe2_tready                             ,
    output    wire                          tgc2_slope                                     ,
    output    wire                          tgc2_up_dn                                     ,
    output    wire                          tgc2_prof1                                     ,
    output    wire                          tgc2_prof2                                     ,
    output    wire      [511:0]             m_axis_afe3_tdata                              ,
    output    wire      [63:0]              m_axis_afe3_tkeep                              ,
    output    wire                          m_axis_afe3_tvalid                             ,
    output    wire                          m_axis_afe3_tlast                              ,
    input                                   m_axis_afe3_tready                             ,
    output    wire                          tgc3_slope                                     ,
    output    wire                          tgc3_up_dn                                     ,
    output    wire                          tgc3_prof1                                     ,
    output    wire                          tgc3_prof2                                     ,
    output    wire      [511:0]             m_axis_afe4_tdata                              ,
    output    wire      [63:0]              m_axis_afe4_tkeep                              ,
    output    wire                          m_axis_afe4_tvalid                             ,
    output    wire                          m_axis_afe4_tlast                              ,
    input                                   m_axis_afe4_tready                             ,
    output    wire                          tgc4_slope                                     ,
    output    wire                          tgc4_up_dn                                     ,
    output    wire                          tgc4_prof1                                     ,
    output    wire                          tgc4_prof2                                     ,
    output    wire      [511:0]             m_axis_afe5_tdata                              ,
    output    wire      [63:0]              m_axis_afe5_tkeep                              ,
    output    wire                          m_axis_afe5_tvalid                             ,
    output    wire                          m_axis_afe5_tlast                              ,
    input                                   m_axis_afe5_tready                             ,
    output    wire                          tgc5_slope                                     ,
    output    wire                          tgc5_up_dn                                     ,
    output    wire                          tgc5_prof1                                     ,
    output    wire                          tgc5_prof2                                     ,
    output    wire      [511:0]             m_axis_afe6_tdata                              ,
    output    wire      [63:0]              m_axis_afe6_tkeep                              ,
    output    wire                          m_axis_afe6_tvalid                             ,
    output    wire                          m_axis_afe6_tlast                              ,
    input                                   m_axis_afe6_tready                             ,
    output    wire                          tgc6_slope                                     ,
    output    wire                          tgc6_up_dn                                     ,
    output    wire                          tgc6_prof1                                     ,
    output    wire                          tgc6_prof2                                     ,
    output    wire      [511:0]             m_axis_afe7_tdata                              ,
    output    wire      [63:0]              m_axis_afe7_tkeep                              ,
    output    wire                          m_axis_afe7_tvalid                             ,
    output    wire                          m_axis_afe7_tlast                              ,
    input                                   m_axis_afe7_tready                             ,
    output    wire                          tgc7_slope                                     ,
    output    wire                          tgc7_up_dn                                     ,
    output    wire                          tgc7_prof1                                     ,
    output    wire                          tgc7_prof2
);

parameter                                   UDLY                     = 1                   ;

wire                    [31:0]              adc_ctl                                        ;
wire                    [31:0]              frm_cfg                                        ;
wire                    [7:0]               tgc_cmd_evt_sys                                ;
wire                    [15:0]              tgc_profile_sys                                ;
wire                    [7:0]               tgc_up_dn_sys                                  ;
wire                    [7:0]               tgc_cmd_evt_afe                                ;
wire                    [15:0]              tgc_profile_afe                                ;
wire                    [7:0]               tgc_up_dn_afe                                  ;
wire                    [7:0]               tgc_done_evt_afe                               ;
wire                    [7:0]               tgc_done_evt_sys                               ;
wire                    [7:0]               tgc_slope_vec                                  ;
wire                    [7:0]               tgc_up_dn_vec                                  ;
wire                    [7:0]               tgc_prof1_vec                                  ;
wire                    [7:0]               tgc_prof2_vec                                  ;
wire                    [7:0]               link_ready_adc                                 ;
wire                    [7:0]               fifo_empty_adc                                 ;
wire                    [7:0]               chn_idle_adc                                   ;
wire                    [7:0]               pll_lock_adc                                   ;
wire                    [7:0]               rx_reset_done_adc                              ;
wire                    [15:0]              lane_ready_adc                                 ;
wire                    [15:0]              byte_aligned_adc                               ;
wire                    [15:0]              comma_detected_adc                             ;
wire                    [7:0]               fifo_overflow_evt_afe                          ;
wire                    [7:0]               data_error_evt_afe                             ;
wire                    [7:0]               link_error_evt_adc                             ;
wire                    [7:0]               sysref_seen_evt_adc                            ;
wire                    [15:0]              disparity_evt_adc                              ;
wire                    [15:0]              notintable_evt_adc                             ;
wire                    [7:0]               fifo_full_afe                                  ;
wire                    [7:0]               link_ready_sys                                 ;
wire                    [7:0]               fifo_empty_sys                                 ;
wire                    [7:0]               fifo_full_sys                                  ;
wire                    [7:0]               chn_idle_sys                                   ;
wire                    [7:0]               pll_lock_sys                                   ;
wire                    [7:0]               rx_reset_done_sys                              ;
wire                    [15:0]              lane_ready_sys                                 ;
wire                    [15:0]              byte_aligned_sys                               ;
wire                    [15:0]              comma_detected_sys                             ;
wire                                        sysref_level_sys                               ;
wire                    [7:0]               fifo_overflow_evt_sys                          ;
wire                    [7:0]               data_error_evt_sys                             ;
wire                    [7:0]               link_error_evt_sys                             ;
wire                    [7:0]               sysref_seen_evt_sys                            ;
wire                    [15:0]              disparity_evt_sys                              ;
wire                    [15:0]              notintable_evt_sys                             ;
assign tgc0_slope = tgc_slope_vec[0];
assign tgc0_up_dn = tgc_up_dn_vec[0];
assign tgc0_prof1 = tgc_prof1_vec[0];
assign tgc0_prof2 = tgc_prof2_vec[0];
assign tgc1_slope = tgc_slope_vec[1];
assign tgc1_up_dn = tgc_up_dn_vec[1];
assign tgc1_prof1 = tgc_prof1_vec[1];
assign tgc1_prof2 = tgc_prof2_vec[1];
assign tgc2_slope = tgc_slope_vec[2];
assign tgc2_up_dn = tgc_up_dn_vec[2];
assign tgc2_prof1 = tgc_prof1_vec[2];
assign tgc2_prof2 = tgc_prof2_vec[2];
assign tgc3_slope = tgc_slope_vec[3];
assign tgc3_up_dn = tgc_up_dn_vec[3];
assign tgc3_prof1 = tgc_prof1_vec[3];
assign tgc3_prof2 = tgc_prof2_vec[3];
assign tgc4_slope = tgc_slope_vec[4];
assign tgc4_up_dn = tgc_up_dn_vec[4];
assign tgc4_prof1 = tgc_prof1_vec[4];
assign tgc4_prof2 = tgc_prof2_vec[4];
assign tgc5_slope = tgc_slope_vec[5];
assign tgc5_up_dn = tgc_up_dn_vec[5];
assign tgc5_prof1 = tgc_prof1_vec[5];
assign tgc5_prof2 = tgc_prof2_vec[5];
assign tgc6_slope = tgc_slope_vec[6];
assign tgc6_up_dn = tgc_up_dn_vec[6];
assign tgc6_prof1 = tgc_prof1_vec[6];
assign tgc6_prof2 = tgc_prof2_vec[6];
assign tgc7_slope = tgc_slope_vec[7];
assign tgc7_up_dn = tgc_up_dn_vec[7];
assign tgc7_prof1 = tgc_prof1_vec[7];
assign tgc7_prof2 = tgc_prof2_vec[7];

ADC_REG #(
    .UDLY                               (UDLY                                         )
) adc_reg(
    .sys_clk                             (sys_clk),
    .sys_rst_n                           (sys_rst_n),
    .s_axi_awaddr                        (s_axi_awaddr),
    .s_axi_awvalid                       (s_axi_awvalid),
    .s_axi_awready                       (s_axi_awready),
    .s_axi_wdata                         (s_axi_wdata),
    .s_axi_wstrb                         (s_axi_wstrb),
    .s_axi_wvalid                        (s_axi_wvalid),
    .s_axi_wready                        (s_axi_wready),
    .s_axi_bresp                         (s_axi_bresp),
    .s_axi_bvalid                        (s_axi_bvalid),
    .s_axi_bready                        (s_axi_bready),
    .s_axi_araddr                        (s_axi_araddr),
    .s_axi_arvalid                       (s_axi_arvalid),
    .s_axi_arready                       (s_axi_arready),
    .s_axi_rdata                         (s_axi_rdata),
    .s_axi_rresp                         (s_axi_rresp),
    .s_axi_rvalid                        (s_axi_rvalid),
    .s_axi_rready                        (s_axi_rready),
    .link_ready                          (link_ready_sys),
    .fifo_empty                          (fifo_empty_sys),
    .fifo_full                           (fifo_full_sys),
    .chn_idle                            (chn_idle_sys),
    .pll_lock                            (pll_lock_sys),
    .rx_reset_done                       (rx_reset_done_sys),
    .lane_ready                          (lane_ready_sys),
    .byte_aligned                        (byte_aligned_sys),
    .comma_detected                      (comma_detected_sys),
    .sysref_level                        (sysref_level_sys),
    .fifo_overflow_evt                   (fifo_overflow_evt_sys),
    .data_error_evt                      (data_error_evt_sys),
    .link_error_evt                      (link_error_evt_sys),
    .sysref_seen_evt                     (sysref_seen_evt_sys),
    .disparity_evt                       (disparity_evt_sys),
    .notintable_evt                      (notintable_evt_sys),
    .tgc_done_evt                        (tgc_done_evt_sys),
    .adc_ctl                             (adc_ctl),
    .frm_cfg                             (frm_cfg),
    .tgc_cmd_evt                         (tgc_cmd_evt_sys),
    .tgc_profile                         (tgc_profile_sys),
    .tgc_up_dn                           (tgc_up_dn_sys)
);

ADC_SYNC #(
    .UDLY                               (UDLY                                         )
) adc_sync(
    .sys_clk                             (sys_clk),
    .sys_rst_n                           (sys_rst_n),
    .adc_clk                             (adc_clk),
    .adc_rst_n                           (adc_rst_n),
    .afe_clk                             (afe_clk),
    .afe_rst_n                           (afe_rst_n),
    .sysref                              (sysref_in),
    .link_ready_adc                      (link_ready_adc),
    .fifo_empty_adc                      (fifo_empty_adc),
    .afe_idle_adc                        (chn_idle_adc),
    .pll_lock_adc                        (pll_lock_adc),
    .rx_reset_done_adc                   (rx_reset_done_adc),
    .lane_ready_adc                      (lane_ready_adc),
    .byte_aligned_adc                    (byte_aligned_adc),
    .comma_detected_adc                  (comma_detected_adc),
    .link_error_evt_adc                  (link_error_evt_adc),
    .sysref_seen_evt_adc                 (sysref_seen_evt_adc),
    .disparity_evt_adc                   (disparity_evt_adc),
    .notintable_evt_adc                  (notintable_evt_adc),
    .fifo_overflow_evt_afe               (fifo_overflow_evt_afe),
    .link_ready_sys                      (link_ready_sys),
    .fifo_empty_sys                      (fifo_empty_sys),
    .fifo_full_sys                       (fifo_full_sys),
    .afe_idle_sys                        (chn_idle_sys),
    .pll_lock_sys                        (pll_lock_sys),
    .rx_reset_done_sys                   (rx_reset_done_sys),
    .lane_ready_sys                      (lane_ready_sys),
    .byte_aligned_sys                    (byte_aligned_sys),
    .comma_detected_sys                  (comma_detected_sys),
    .sysref_level_sys                    (sysref_level_sys),
    .fifo_overflow_evt_sys               (fifo_overflow_evt_sys),
    .data_error_evt_sys                  (data_error_evt_sys),
    .link_error_evt_sys                  (link_error_evt_sys),
    .sysref_seen_evt_sys                 (sysref_seen_evt_sys),
    .disparity_evt_sys                   (disparity_evt_sys),
    .notintable_evt_sys                  (notintable_evt_sys),
    .tgc_cmd_evt_sys                     (tgc_cmd_evt_sys),
    .tgc_profile_sys                     (tgc_profile_sys),
    .tgc_up_dn_sys                       (tgc_up_dn_sys),
    .tgc_done_evt_afe                    (tgc_done_evt_afe),
    .tgc_cmd_evt_afe                     (tgc_cmd_evt_afe),
    .tgc_profile_afe                     (tgc_profile_afe),
    .tgc_up_dn_afe                       (tgc_up_dn_afe),
    .tgc_done_evt_sys                    (tgc_done_evt_sys),
    .fifo_full_afe                       (fifo_full_afe),
    .data_error_evt_afe                  (data_error_evt_afe)
);

ADC_CHN #(.UDLY(UDLY)) adc_chn0(
    .adc_clk                (adc_clk                 ),
    .adc_rst_n              (adc_rst_n               ),
    .afe_clk                (afe_clk                 ),
    .afe_rst_n              (afe_rst_n               ),
    .jesd_clk               (jesd_clk[0]             ),
    .jesd_rst_n             (jesd_rst_n[0]           ),
    .chn_id                 (3'd0                    ),
    .chn_en                 (adc_ctl[0]              ),
    .fifo_clr               (adc_ctl[8]              ),
    .sysref                 (sysref_in               ),
    .adc_ctl                (adc_ctl                 ),
    .frm_cfg                (frm_cfg                 ),
    .phy_rx_data            (afe0_rx_data            ),
    .phy_rx_charisk         (afe0_rx_charisk         ),
    .phy_rx_disperr         (afe0_rx_disperr         ),
    .phy_rx_notintable      (afe0_rx_notintable      ),
    .phy_rx_reset_done      (afe0_rx_reset_done      ),
    .phy_pll_lock           (afe0_pll_lock           ),
    .phy_byte_aligned       (afe0_byte_aligned       ),
    .phy_rx_encommalign     (afe0_rx_encommalign     ),
    .phy_sync_n             (afe0_sync_n             ),
    .m_axis_tdata           (m_axis_afe0_tdata       ),
    .m_axis_tkeep           (m_axis_afe0_tkeep       ),
    .m_axis_tvalid          (m_axis_afe0_tvalid      ),
    .m_axis_tlast           (m_axis_afe0_tlast       ),
    .m_axis_tready          (m_axis_afe0_tready      ),
    .link_ready_sync        (link_ready_adc[0]       ),
    .rx_fifo_empt           (fifo_empty_adc[0]       ),
    .chn_idle_adc           (chn_idle_adc[0]         ),
    .phy_pll_lock_sync      (pll_lock_adc[0]         ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[0]    ),
    .lane_ready_sync        (lane_ready_adc[1:0]     ),
    .phy_byte_aligned_sync  (byte_aligned_adc[1:0]   ),
    .cgs_ready_sync         (comma_detected_adc[1:0] ),
    .rx_fifo_of             (fifo_overflow_evt_afe[0]),
    .link_error_sync        (link_error_evt_adc[0]   ),
    .sysref_seen_sync       (sysref_seen_evt_adc[0]  ),
    .phy_disparity_sync     (disparity_evt_adc[1:0]  ),
    .phy_notintable_sync    (notintable_evt_adc[1:0] ),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[0]      ),
    .tgc_profile            (tgc_profile_afe[1:0]    ),
    .tgc_up_dn              (tgc_up_dn_afe[0]        ),
    .tgc_done_evt           (tgc_done_evt_afe[0]     ),
    .tgc_slope              (tgc_slope_vec[0]        ),
    .tgc_up_dn_o            (tgc_up_dn_vec[0]        ),
    .tgc_prof1              (tgc_prof1_vec[0]        ),
    .tgc_prof2              (tgc_prof2_vec[0]        ),
    .fifo_full_afe          (fifo_full_afe[0]        ),
    .data_error_evt         (data_error_evt_afe[0]   )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn1(
    .adc_clk                (adc_clk                 ),
    .adc_rst_n              (adc_rst_n               ),
    .afe_clk                (afe_clk                 ),
    .afe_rst_n              (afe_rst_n               ),
    .jesd_clk               (jesd_clk[1]             ),
    .jesd_rst_n             (jesd_rst_n[1]           ),
    .chn_id                 (3'd1                    ),
    .chn_en                 (adc_ctl[1]              ),
    .fifo_clr               (adc_ctl[9]              ),
    .sysref                 (sysref_in               ),
    .adc_ctl                (adc_ctl                 ),
    .frm_cfg                (frm_cfg                 ),
    .phy_rx_data            (afe1_rx_data            ),
    .phy_rx_charisk         (afe1_rx_charisk         ),
    .phy_rx_disperr         (afe1_rx_disperr         ),
    .phy_rx_notintable      (afe1_rx_notintable      ),
    .phy_rx_reset_done      (afe1_rx_reset_done      ),
    .phy_pll_lock           (afe1_pll_lock           ),
    .phy_byte_aligned       (afe1_byte_aligned       ),
    .phy_rx_encommalign     (afe1_rx_encommalign     ),
    .phy_sync_n             (afe1_sync_n             ),
    .m_axis_tdata           (m_axis_afe1_tdata       ),
    .m_axis_tkeep           (m_axis_afe1_tkeep       ),
    .m_axis_tvalid          (m_axis_afe1_tvalid      ),
    .m_axis_tlast           (m_axis_afe1_tlast       ),
    .m_axis_tready          (m_axis_afe1_tready      ),
    .link_ready_sync        (link_ready_adc[1]       ),
    .rx_fifo_empt           (fifo_empty_adc[1]       ),
    .chn_idle_adc           (chn_idle_adc[1]         ),
    .phy_pll_lock_sync      (pll_lock_adc[1]         ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[1]    ),
    .lane_ready_sync        (lane_ready_adc[3:2]     ),
    .phy_byte_aligned_sync  (byte_aligned_adc[3:2]   ),
    .cgs_ready_sync         (comma_detected_adc[3:2] ),
    .rx_fifo_of             (fifo_overflow_evt_afe[1]),
    .link_error_sync        (link_error_evt_adc[1]   ),
    .sysref_seen_sync       (sysref_seen_evt_adc[1]  ),
    .phy_disparity_sync     (disparity_evt_adc[3:2]  ),
    .phy_notintable_sync    (notintable_evt_adc[3:2] ),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[1]      ),
    .tgc_profile            (tgc_profile_afe[3:2]    ),
    .tgc_up_dn              (tgc_up_dn_afe[1]        ),
    .tgc_done_evt           (tgc_done_evt_afe[1]     ),
    .tgc_slope              (tgc_slope_vec[1]        ),
    .tgc_up_dn_o            (tgc_up_dn_vec[1]        ),
    .tgc_prof1              (tgc_prof1_vec[1]        ),
    .tgc_prof2              (tgc_prof2_vec[1]        ),
    .fifo_full_afe          (fifo_full_afe[1]        ),
    .data_error_evt         (data_error_evt_afe[1]   )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn2(
    .adc_clk                (adc_clk                 ),
    .adc_rst_n              (adc_rst_n               ),
    .afe_clk                (afe_clk                 ),
    .afe_rst_n              (afe_rst_n               ),
    .jesd_clk               (jesd_clk[2]             ),
    .jesd_rst_n             (jesd_rst_n[2]           ),
    .chn_id                 (3'd2                    ),
    .chn_en                 (adc_ctl[2]              ),
    .fifo_clr               (adc_ctl[10]             ),
    .sysref                 (sysref_in               ),
    .adc_ctl                (adc_ctl                 ),
    .frm_cfg                (frm_cfg                 ),
    .phy_rx_data            (afe2_rx_data            ),
    .phy_rx_charisk         (afe2_rx_charisk         ),
    .phy_rx_disperr         (afe2_rx_disperr         ),
    .phy_rx_notintable      (afe2_rx_notintable      ),
    .phy_rx_reset_done      (afe2_rx_reset_done      ),
    .phy_pll_lock           (afe2_pll_lock           ),
    .phy_byte_aligned       (afe2_byte_aligned       ),
    .phy_rx_encommalign     (afe2_rx_encommalign     ),
    .phy_sync_n             (afe2_sync_n             ),
    .m_axis_tdata           (m_axis_afe2_tdata       ),
    .m_axis_tkeep           (m_axis_afe2_tkeep       ),
    .m_axis_tvalid          (m_axis_afe2_tvalid      ),
    .m_axis_tlast           (m_axis_afe2_tlast       ),
    .m_axis_tready          (m_axis_afe2_tready      ),
    .link_ready_sync        (link_ready_adc[2]       ),
    .rx_fifo_empt           (fifo_empty_adc[2]       ),
    .chn_idle_adc           (chn_idle_adc[2]         ),
    .phy_pll_lock_sync      (pll_lock_adc[2]         ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[2]    ),
    .lane_ready_sync        (lane_ready_adc[5:4]     ),
    .phy_byte_aligned_sync  (byte_aligned_adc[5:4]   ),
    .cgs_ready_sync         (comma_detected_adc[5:4] ),
    .rx_fifo_of             (fifo_overflow_evt_afe[2]),
    .link_error_sync        (link_error_evt_adc[2]   ),
    .sysref_seen_sync       (sysref_seen_evt_adc[2]  ),
    .phy_disparity_sync     (disparity_evt_adc[5:4]  ),
    .phy_notintable_sync    (notintable_evt_adc[5:4] ),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[2]      ),
    .tgc_profile            (tgc_profile_afe[5:4]    ),
    .tgc_up_dn              (tgc_up_dn_afe[2]        ),
    .tgc_done_evt           (tgc_done_evt_afe[2]     ),
    .tgc_slope              (tgc_slope_vec[2]        ),
    .tgc_up_dn_o            (tgc_up_dn_vec[2]        ),
    .tgc_prof1              (tgc_prof1_vec[2]        ),
    .tgc_prof2              (tgc_prof2_vec[2]        ),
    .fifo_full_afe          (fifo_full_afe[2]        ),
    .data_error_evt         (data_error_evt_afe[2]   )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn3(
    .adc_clk                (adc_clk                 ),
    .adc_rst_n              (adc_rst_n               ),
    .afe_clk                (afe_clk                 ),
    .afe_rst_n              (afe_rst_n               ),
    .jesd_clk               (jesd_clk[3]             ),
    .jesd_rst_n             (jesd_rst_n[3]           ),
    .chn_id                 (3'd3                    ),
    .chn_en                 (adc_ctl[3]              ),
    .fifo_clr               (adc_ctl[11]             ),
    .sysref                 (sysref_in               ),
    .adc_ctl                (adc_ctl                 ),
    .frm_cfg                (frm_cfg                 ),
    .phy_rx_data            (afe3_rx_data            ),
    .phy_rx_charisk         (afe3_rx_charisk         ),
    .phy_rx_disperr         (afe3_rx_disperr         ),
    .phy_rx_notintable      (afe3_rx_notintable      ),
    .phy_rx_reset_done      (afe3_rx_reset_done      ),
    .phy_pll_lock           (afe3_pll_lock           ),
    .phy_byte_aligned       (afe3_byte_aligned       ),
    .phy_rx_encommalign     (afe3_rx_encommalign     ),
    .phy_sync_n             (afe3_sync_n             ),
    .m_axis_tdata           (m_axis_afe3_tdata       ),
    .m_axis_tkeep           (m_axis_afe3_tkeep       ),
    .m_axis_tvalid          (m_axis_afe3_tvalid      ),
    .m_axis_tlast           (m_axis_afe3_tlast       ),
    .m_axis_tready          (m_axis_afe3_tready      ),
    .link_ready_sync        (link_ready_adc[3]       ),
    .rx_fifo_empt           (fifo_empty_adc[3]       ),
    .chn_idle_adc           (chn_idle_adc[3]         ),
    .phy_pll_lock_sync      (pll_lock_adc[3]         ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[3]    ),
    .lane_ready_sync        (lane_ready_adc[7:6]     ),
    .phy_byte_aligned_sync  (byte_aligned_adc[7:6]   ),
    .cgs_ready_sync         (comma_detected_adc[7:6] ),
    .rx_fifo_of             (fifo_overflow_evt_afe[3]),
    .link_error_sync        (link_error_evt_adc[3]   ),
    .sysref_seen_sync       (sysref_seen_evt_adc[3]  ),
    .phy_disparity_sync     (disparity_evt_adc[7:6]  ),
    .phy_notintable_sync    (notintable_evt_adc[7:6] ),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[3]      ),
    .tgc_profile            (tgc_profile_afe[7:6]    ),
    .tgc_up_dn              (tgc_up_dn_afe[3]        ),
    .tgc_done_evt           (tgc_done_evt_afe[3]     ),
    .tgc_slope              (tgc_slope_vec[3]        ),
    .tgc_up_dn_o            (tgc_up_dn_vec[3]        ),
    .tgc_prof1              (tgc_prof1_vec[3]        ),
    .tgc_prof2              (tgc_prof2_vec[3]        ),
    .fifo_full_afe          (fifo_full_afe[3]        ),
    .data_error_evt         (data_error_evt_afe[3]   )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn4(
    .adc_clk                (adc_clk                 ),
    .adc_rst_n              (adc_rst_n               ),
    .afe_clk                (afe_clk                 ),
    .afe_rst_n              (afe_rst_n               ),
    .jesd_clk               (jesd_clk[4]             ),
    .jesd_rst_n             (jesd_rst_n[4]           ),
    .chn_id                 (3'd4                    ),
    .chn_en                 (adc_ctl[4]              ),
    .fifo_clr               (adc_ctl[12]             ),
    .sysref                 (sysref_in               ),
    .adc_ctl                (adc_ctl                 ),
    .frm_cfg                (frm_cfg                 ),
    .phy_rx_data            (afe4_rx_data            ),
    .phy_rx_charisk         (afe4_rx_charisk         ),
    .phy_rx_disperr         (afe4_rx_disperr         ),
    .phy_rx_notintable      (afe4_rx_notintable      ),
    .phy_rx_reset_done      (afe4_rx_reset_done      ),
    .phy_pll_lock           (afe4_pll_lock           ),
    .phy_byte_aligned       (afe4_byte_aligned       ),
    .phy_rx_encommalign     (afe4_rx_encommalign     ),
    .phy_sync_n             (afe4_sync_n             ),
    .m_axis_tdata           (m_axis_afe4_tdata       ),
    .m_axis_tkeep           (m_axis_afe4_tkeep       ),
    .m_axis_tvalid          (m_axis_afe4_tvalid      ),
    .m_axis_tlast           (m_axis_afe4_tlast       ),
    .m_axis_tready          (m_axis_afe4_tready      ),
    .link_ready_sync        (link_ready_adc[4]       ),
    .rx_fifo_empt           (fifo_empty_adc[4]       ),
    .chn_idle_adc           (chn_idle_adc[4]         ),
    .phy_pll_lock_sync      (pll_lock_adc[4]         ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[4]    ),
    .lane_ready_sync        (lane_ready_adc[9:8]     ),
    .phy_byte_aligned_sync  (byte_aligned_adc[9:8]   ),
    .cgs_ready_sync         (comma_detected_adc[9:8] ),
    .rx_fifo_of             (fifo_overflow_evt_afe[4]),
    .link_error_sync        (link_error_evt_adc[4]   ),
    .sysref_seen_sync       (sysref_seen_evt_adc[4]  ),
    .phy_disparity_sync     (disparity_evt_adc[9:8]  ),
    .phy_notintable_sync    (notintable_evt_adc[9:8] ),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[4]      ),
    .tgc_profile            (tgc_profile_afe[9:8]    ),
    .tgc_up_dn              (tgc_up_dn_afe[4]        ),
    .tgc_done_evt           (tgc_done_evt_afe[4]     ),
    .tgc_slope              (tgc_slope_vec[4]        ),
    .tgc_up_dn_o            (tgc_up_dn_vec[4]        ),
    .tgc_prof1              (tgc_prof1_vec[4]        ),
    .tgc_prof2              (tgc_prof2_vec[4]        ),
    .fifo_full_afe          (fifo_full_afe[4]        ),
    .data_error_evt         (data_error_evt_afe[4]   )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn5(
    .adc_clk                (adc_clk                  ),
    .adc_rst_n              (adc_rst_n                ),
    .afe_clk                (afe_clk                  ),
    .afe_rst_n              (afe_rst_n                ),
    .jesd_clk               (jesd_clk[5]              ),
    .jesd_rst_n             (jesd_rst_n[5]            ),
    .chn_id                 (3'd5                     ),
    .chn_en                 (adc_ctl[5]               ),
    .fifo_clr               (adc_ctl[13]              ),
    .sysref                 (sysref_in                ),
    .adc_ctl                (adc_ctl                  ),
    .frm_cfg                (frm_cfg                  ),
    .phy_rx_data            (afe5_rx_data             ),
    .phy_rx_charisk         (afe5_rx_charisk          ),
    .phy_rx_disperr         (afe5_rx_disperr          ),
    .phy_rx_notintable      (afe5_rx_notintable       ),
    .phy_rx_reset_done      (afe5_rx_reset_done       ),
    .phy_pll_lock           (afe5_pll_lock            ),
    .phy_byte_aligned       (afe5_byte_aligned        ),
    .phy_rx_encommalign     (afe5_rx_encommalign      ),
    .phy_sync_n             (afe5_sync_n              ),
    .m_axis_tdata           (m_axis_afe5_tdata        ),
    .m_axis_tkeep           (m_axis_afe5_tkeep        ),
    .m_axis_tvalid          (m_axis_afe5_tvalid       ),
    .m_axis_tlast           (m_axis_afe5_tlast        ),
    .m_axis_tready          (m_axis_afe5_tready       ),
    .link_ready_sync        (link_ready_adc[5]        ),
    .rx_fifo_empt           (fifo_empty_adc[5]        ),
    .chn_idle_adc           (chn_idle_adc[5]          ),
    .phy_pll_lock_sync      (pll_lock_adc[5]          ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[5]     ),
    .lane_ready_sync        (lane_ready_adc[11:10]    ),
    .phy_byte_aligned_sync  (byte_aligned_adc[11:10]  ),
    .cgs_ready_sync         (comma_detected_adc[11:10]),
    .rx_fifo_of             (fifo_overflow_evt_afe[5] ),
    .link_error_sync        (link_error_evt_adc[5]    ),
    .sysref_seen_sync       (sysref_seen_evt_adc[5]   ),
    .phy_disparity_sync     (disparity_evt_adc[11:10] ),
    .phy_notintable_sync    (notintable_evt_adc[11:10]),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[5]       ),
    .tgc_profile            (tgc_profile_afe[11:10]   ),
    .tgc_up_dn              (tgc_up_dn_afe[5]         ),
    .tgc_done_evt           (tgc_done_evt_afe[5]      ),
    .tgc_slope              (tgc_slope_vec[5]         ),
    .tgc_up_dn_o            (tgc_up_dn_vec[5]         ),
    .tgc_prof1              (tgc_prof1_vec[5]         ),
    .tgc_prof2              (tgc_prof2_vec[5]         ),
    .fifo_full_afe          (fifo_full_afe[5]         ),
    .data_error_evt         (data_error_evt_afe[5]    )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn6(
    .adc_clk                (adc_clk                  ),
    .adc_rst_n              (adc_rst_n                ),
    .afe_clk                (afe_clk                  ),
    .afe_rst_n              (afe_rst_n                ),
    .jesd_clk               (jesd_clk[6]              ),
    .jesd_rst_n             (jesd_rst_n[6]            ),
    .chn_id                 (3'd6                     ),
    .chn_en                 (adc_ctl[6]               ),
    .fifo_clr               (adc_ctl[14]              ),
    .sysref                 (sysref_in                ),
    .adc_ctl                (adc_ctl                  ),
    .frm_cfg                (frm_cfg                  ),
    .phy_rx_data            (afe6_rx_data             ),
    .phy_rx_charisk         (afe6_rx_charisk          ),
    .phy_rx_disperr         (afe6_rx_disperr          ),
    .phy_rx_notintable      (afe6_rx_notintable       ),
    .phy_rx_reset_done      (afe6_rx_reset_done       ),
    .phy_pll_lock           (afe6_pll_lock            ),
    .phy_byte_aligned       (afe6_byte_aligned        ),
    .phy_rx_encommalign     (afe6_rx_encommalign      ),
    .phy_sync_n             (afe6_sync_n              ),
    .m_axis_tdata           (m_axis_afe6_tdata        ),
    .m_axis_tkeep           (m_axis_afe6_tkeep        ),
    .m_axis_tvalid          (m_axis_afe6_tvalid       ),
    .m_axis_tlast           (m_axis_afe6_tlast        ),
    .m_axis_tready          (m_axis_afe6_tready       ),
    .link_ready_sync        (link_ready_adc[6]        ),
    .rx_fifo_empt           (fifo_empty_adc[6]        ),
    .chn_idle_adc           (chn_idle_adc[6]          ),
    .phy_pll_lock_sync      (pll_lock_adc[6]          ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[6]     ),
    .lane_ready_sync        (lane_ready_adc[13:12]    ),
    .phy_byte_aligned_sync  (byte_aligned_adc[13:12]  ),
    .cgs_ready_sync         (comma_detected_adc[13:12]),
    .rx_fifo_of             (fifo_overflow_evt_afe[6] ),
    .link_error_sync        (link_error_evt_adc[6]    ),
    .sysref_seen_sync       (sysref_seen_evt_adc[6]   ),
    .phy_disparity_sync     (disparity_evt_adc[13:12] ),
    .phy_notintable_sync    (notintable_evt_adc[13:12]),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[6]       ),
    .tgc_profile            (tgc_profile_afe[13:12]   ),
    .tgc_up_dn              (tgc_up_dn_afe[6]         ),
    .tgc_done_evt           (tgc_done_evt_afe[6]      ),
    .tgc_slope              (tgc_slope_vec[6]         ),
    .tgc_up_dn_o            (tgc_up_dn_vec[6]         ),
    .tgc_prof1              (tgc_prof1_vec[6]         ),
    .tgc_prof2              (tgc_prof2_vec[6]         ),
    .fifo_full_afe          (fifo_full_afe[6]         ),
    .data_error_evt         (data_error_evt_afe[6]    )
);
ADC_CHN #(.UDLY(UDLY)) adc_chn7(
    .adc_clk                (adc_clk                  ),
    .adc_rst_n              (adc_rst_n                ),
    .afe_clk                (afe_clk                  ),
    .afe_rst_n              (afe_rst_n                ),
    .jesd_clk               (jesd_clk[7]              ),
    .jesd_rst_n             (jesd_rst_n[7]            ),
    .chn_id                 (3'd7                     ),
    .chn_en                 (adc_ctl[7]               ),
    .fifo_clr               (adc_ctl[15]              ),
    .sysref                 (sysref_in                ),
    .adc_ctl                (adc_ctl                  ),
    .frm_cfg                (frm_cfg                  ),
    .phy_rx_data            (afe7_rx_data             ),
    .phy_rx_charisk         (afe7_rx_charisk          ),
    .phy_rx_disperr         (afe7_rx_disperr          ),
    .phy_rx_notintable      (afe7_rx_notintable       ),
    .phy_rx_reset_done      (afe7_rx_reset_done       ),
    .phy_pll_lock           (afe7_pll_lock            ),
    .phy_byte_aligned       (afe7_byte_aligned        ),
    .phy_rx_encommalign     (afe7_rx_encommalign      ),
    .phy_sync_n             (afe7_sync_n              ),
    .m_axis_tdata           (m_axis_afe7_tdata        ),
    .m_axis_tkeep           (m_axis_afe7_tkeep        ),
    .m_axis_tvalid          (m_axis_afe7_tvalid       ),
    .m_axis_tlast           (m_axis_afe7_tlast        ),
    .m_axis_tready          (m_axis_afe7_tready       ),
    .link_ready_sync        (link_ready_adc[7]        ),
    .rx_fifo_empt           (fifo_empty_adc[7]        ),
    .chn_idle_adc           (chn_idle_adc[7]          ),
    .phy_pll_lock_sync      (pll_lock_adc[7]          ),
    .phy_rx_reset_done_sync (rx_reset_done_adc[7]     ),
    .lane_ready_sync        (lane_ready_adc[15:14]    ),
    .phy_byte_aligned_sync  (byte_aligned_adc[15:14]  ),
    .cgs_ready_sync         (comma_detected_adc[15:14]),
    .rx_fifo_of             (fifo_overflow_evt_afe[7] ),
    .link_error_sync        (link_error_evt_adc[7]    ),
    .sysref_seen_sync       (sysref_seen_evt_adc[7]   ),
    .phy_disparity_sync     (disparity_evt_adc[15:14] ),
    .phy_notintable_sync    (notintable_evt_adc[15:14]),
    .tgc_cmd_evt            (tgc_cmd_evt_afe[7]       ),
    .tgc_profile            (tgc_profile_afe[15:14]   ),
    .tgc_up_dn              (tgc_up_dn_afe[7]         ),
    .tgc_done_evt           (tgc_done_evt_afe[7]      ),
    .tgc_slope              (tgc_slope_vec[7]         ),
    .tgc_up_dn_o            (tgc_up_dn_vec[7]         ),
    .tgc_prof1              (tgc_prof1_vec[7]         ),
    .tgc_prof2              (tgc_prof2_vec[7]         ),
    .fifo_full_afe          (fifo_full_afe[7]         ),
    .data_error_evt         (data_error_evt_afe[7]    )
);

endmodule
