`timescale 1ns / 1ps

module DMA_TOP_WRAPPER #(
    parameter integer                       AXI_ADDR_WIDTH              = 15            ,
    parameter integer                       UDLY                        = 1
)(
    input  wire                             SYS_CLK                                     ,
    input  wire                             SYS_RST_N                                   ,
    input  wire                             DMA_AXIS_RST_N                              ,
    input  wire                             M_AXI_ACLK                                  ,
    input  wire                             DMA_RST_N                                   ,
    input  wire [AXI_ADDR_WIDTH-1:0]        S_AXI_AWADDR                               ,
    input  wire [2:0]                       S_AXI_AWPROT                               ,
    input  wire                             S_AXI_AWVALID                              ,
    output wire                             S_AXI_AWREADY                              ,
    input  wire [31:0]                      S_AXI_WDATA                                ,
    input  wire [3:0]                       S_AXI_WSTRB                                ,
    input  wire                             S_AXI_WVALID                               ,
    output wire                             S_AXI_WREADY                               ,
    output wire [1:0]                       S_AXI_BRESP                                ,
    output wire                             S_AXI_BVALID                               ,
    input  wire                             S_AXI_BREADY                               ,
    input  wire [AXI_ADDR_WIDTH-1:0]        S_AXI_ARADDR                               ,
    input  wire [2:0]                       S_AXI_ARPROT                               ,
    input  wire                             S_AXI_ARVALID                              ,
    output wire                             S_AXI_ARREADY                              ,
    output wire [31:0]                      S_AXI_RDATA                                ,
    output wire [1:0]                       S_AXI_RRESP                                ,
    output wire                             S_AXI_RVALID                               ,
    input  wire                             S_AXI_RREADY                               ,
    input  wire [511:0]                     S_AXIS_TDATA0                              ,
    input  wire [63:0]                      S_AXIS_TKEEP0                              ,
    input  wire                             S_AXIS_TLAST0                              ,
    input  wire                             S_AXIS_TVALID0                             ,
    output wire                             S_AXIS_TREADY0                             ,
    input  wire [511:0]                     S_AXIS_TDATA1                              ,
    input  wire [63:0]                      S_AXIS_TKEEP1                              ,
    input  wire                             S_AXIS_TLAST1                              ,
    input  wire                             S_AXIS_TVALID1                             ,
    output wire                             S_AXIS_TREADY1                             ,
    input  wire [511:0]                     S_AXIS_TDATA2                              ,
    input  wire [63:0]                      S_AXIS_TKEEP2                              ,
    input  wire                             S_AXIS_TLAST2                              ,
    input  wire                             S_AXIS_TVALID2                             ,
    output wire                             S_AXIS_TREADY2                             ,
    input  wire [511:0]                     S_AXIS_TDATA3                              ,
    input  wire [63:0]                      S_AXIS_TKEEP3                              ,
    input  wire                             S_AXIS_TLAST3                              ,
    input  wire                             S_AXIS_TVALID3                             ,
    output wire                             S_AXIS_TREADY3                             ,
    input  wire [511:0]                     S_AXIS_TDATA4                              ,
    input  wire [63:0]                      S_AXIS_TKEEP4                              ,
    input  wire                             S_AXIS_TLAST4                              ,
    input  wire                             S_AXIS_TVALID4                             ,
    output wire                             S_AXIS_TREADY4                             ,
    input  wire [511:0]                     S_AXIS_TDATA5                              ,
    input  wire [63:0]                      S_AXIS_TKEEP5                              ,
    input  wire                             S_AXIS_TLAST5                              ,
    input  wire                             S_AXIS_TVALID5                             ,
    output wire                             S_AXIS_TREADY5                             ,
    input  wire [511:0]                     S_AXIS_TDATA6                              ,
    input  wire [63:0]                      S_AXIS_TKEEP6                              ,
    input  wire                             S_AXIS_TLAST6                              ,
    input  wire                             S_AXIS_TVALID6                             ,
    output wire                             S_AXIS_TREADY6                             ,
    input  wire [511:0]                     S_AXIS_TDATA7                              ,
    input  wire [63:0]                      S_AXIS_TKEEP7                              ,
    input  wire                             S_AXIS_TLAST7                              ,
    input  wire                             S_AXIS_TVALID7                             ,
    output wire                             S_AXIS_TREADY7                             ,
    output wire [31:0]                      M_AXI_AWADDR                               ,
    output wire [7:0]                       M_AXI_AWLEN                                ,
    output wire [2:0]                       M_AXI_AWSIZE                               ,
    output wire [1:0]                       M_AXI_AWBURST                              ,
    output wire                             M_AXI_AWLOCK                               ,
    output wire [3:0]                       M_AXI_AWCACHE                              ,
    output wire [2:0]                       M_AXI_AWPROT                               ,
    output wire [3:0]                       M_AXI_AWQOS                                ,
    output wire [3:0]                       M_AXI_AWREGION                             ,
    output wire                             M_AXI_AWVALID                              ,
    input  wire                             M_AXI_AWREADY                              ,
    output wire [511:0]                     M_AXI_WDATA                                ,
    output wire [63:0]                      M_AXI_WSTRB                                ,
    output wire                             M_AXI_WLAST                                ,
    output wire                             M_AXI_WVALID                               ,
    input  wire                             M_AXI_WREADY                               ,
    input  wire [1:0]                       M_AXI_BRESP                                ,
    input  wire                             M_AXI_BVALID                               ,
    output wire                             M_AXI_BREADY                               ,
    output wire                             DMA_IRQ
);

    DMA_TOP #(.AXI_ADDR_WIDTH(AXI_ADDR_WIDTH), .UDLY(UDLY)) u_dma_top (
        .SYS_CLK(SYS_CLK), .SYS_RST_N(SYS_RST_N), .DMA_AXIS_RST_N(DMA_AXIS_RST_N),
        .M_AXI_ACLK(M_AXI_ACLK), .DMA_RST_N(DMA_RST_N),
        .S_AXI_AWADDR(S_AXI_AWADDR), .S_AXI_AWPROT(S_AXI_AWPROT), .S_AXI_AWVALID(S_AXI_AWVALID), .S_AXI_AWREADY(S_AXI_AWREADY),
        .S_AXI_WDATA(S_AXI_WDATA), .S_AXI_WSTRB(S_AXI_WSTRB), .S_AXI_WVALID(S_AXI_WVALID), .S_AXI_WREADY(S_AXI_WREADY),
        .S_AXI_BRESP(S_AXI_BRESP), .S_AXI_BVALID(S_AXI_BVALID), .S_AXI_BREADY(S_AXI_BREADY),
        .S_AXI_ARADDR(S_AXI_ARADDR), .S_AXI_ARPROT(S_AXI_ARPROT), .S_AXI_ARVALID(S_AXI_ARVALID), .S_AXI_ARREADY(S_AXI_ARREADY),
        .S_AXI_RDATA(S_AXI_RDATA), .S_AXI_RRESP(S_AXI_RRESP), .S_AXI_RVALID(S_AXI_RVALID), .S_AXI_RREADY(S_AXI_RREADY),
        .S_AXIS_TDATA0(S_AXIS_TDATA0), .S_AXIS_TKEEP0(S_AXIS_TKEEP0), .S_AXIS_TLAST0(S_AXIS_TLAST0), .S_AXIS_TVALID0(S_AXIS_TVALID0), .S_AXIS_TREADY0(S_AXIS_TREADY0),
        .S_AXIS_TDATA1(S_AXIS_TDATA1), .S_AXIS_TKEEP1(S_AXIS_TKEEP1), .S_AXIS_TLAST1(S_AXIS_TLAST1), .S_AXIS_TVALID1(S_AXIS_TVALID1), .S_AXIS_TREADY1(S_AXIS_TREADY1),
        .S_AXIS_TDATA2(S_AXIS_TDATA2), .S_AXIS_TKEEP2(S_AXIS_TKEEP2), .S_AXIS_TLAST2(S_AXIS_TLAST2), .S_AXIS_TVALID2(S_AXIS_TVALID2), .S_AXIS_TREADY2(S_AXIS_TREADY2),
        .S_AXIS_TDATA3(S_AXIS_TDATA3), .S_AXIS_TKEEP3(S_AXIS_TKEEP3), .S_AXIS_TLAST3(S_AXIS_TLAST3), .S_AXIS_TVALID3(S_AXIS_TVALID3), .S_AXIS_TREADY3(S_AXIS_TREADY3),
        .S_AXIS_TDATA4(S_AXIS_TDATA4), .S_AXIS_TKEEP4(S_AXIS_TKEEP4), .S_AXIS_TLAST4(S_AXIS_TLAST4), .S_AXIS_TVALID4(S_AXIS_TVALID4), .S_AXIS_TREADY4(S_AXIS_TREADY4),
        .S_AXIS_TDATA5(S_AXIS_TDATA5), .S_AXIS_TKEEP5(S_AXIS_TKEEP5), .S_AXIS_TLAST5(S_AXIS_TLAST5), .S_AXIS_TVALID5(S_AXIS_TVALID5), .S_AXIS_TREADY5(S_AXIS_TREADY5),
        .S_AXIS_TDATA6(S_AXIS_TDATA6), .S_AXIS_TKEEP6(S_AXIS_TKEEP6), .S_AXIS_TLAST6(S_AXIS_TLAST6), .S_AXIS_TVALID6(S_AXIS_TVALID6), .S_AXIS_TREADY6(S_AXIS_TREADY6),
        .S_AXIS_TDATA7(S_AXIS_TDATA7), .S_AXIS_TKEEP7(S_AXIS_TKEEP7), .S_AXIS_TLAST7(S_AXIS_TLAST7), .S_AXIS_TVALID7(S_AXIS_TVALID7), .S_AXIS_TREADY7(S_AXIS_TREADY7),
        .M_AXI_AWADDR(M_AXI_AWADDR), .M_AXI_AWLEN(M_AXI_AWLEN), .M_AXI_AWSIZE(M_AXI_AWSIZE), .M_AXI_AWBURST(M_AXI_AWBURST), .M_AXI_AWLOCK(M_AXI_AWLOCK),
        .M_AXI_AWCACHE(M_AXI_AWCACHE), .M_AXI_AWPROT(M_AXI_AWPROT), .M_AXI_AWQOS(M_AXI_AWQOS), .M_AXI_AWREGION(M_AXI_AWREGION), .M_AXI_AWVALID(M_AXI_AWVALID), .M_AXI_AWREADY(M_AXI_AWREADY),
        .M_AXI_WDATA(M_AXI_WDATA), .M_AXI_WSTRB(M_AXI_WSTRB), .M_AXI_WLAST(M_AXI_WLAST), .M_AXI_WVALID(M_AXI_WVALID), .M_AXI_WREADY(M_AXI_WREADY),
        .M_AXI_BRESP(M_AXI_BRESP), .M_AXI_BVALID(M_AXI_BVALID), .M_AXI_BREADY(M_AXI_BREADY), .DMA_IRQ(DMA_IRQ)
    );
endmodule
`default_nettype wire

